//图标选择器配置
export default {
	icons: [
		{
			name: "箭头",
			namee: "Arrows",
			icons: [
				{ name: "arrow-left-up", desc: "corner,左上" },
				{ name: "arrow-up", desc: "send,箭头,向上,发送" },
				{ name: "arrow-right-up", desc: "send,corner,右上,发送" },
				{ name: "arrow-right", desc: "forward,箭头,向右" },
				{ name: "arrow-right-down", desc: "corner,右下" },
				{ name: "arrow-down", desc: "receive,箭头,向下,接收,收款" },
				{
					name: "arrow-left-down",
					desc: "receive,corner,箭头,左下,接收,收款",
				},
				{ name: "arrow-left", desc: "backward,箭头,向左,返回" },
				{ name: "corner-right-up", desc: "arrow,箭头,右上" },
				{ name: "corner-up-left", desc: "arrow,箭头,上左" },
				{ name: "corner-up-right", desc: "arrow,箭头,上右" },
				{ name: "corner-right-down", desc: "arrow,箭头,右下" },
				{ name: "corner-down-left", desc: "arrow,箭头,下左" },
				{ name: "corner-left-up", desc: "arrow,箭头,左上" },
				{ name: "corner-left-down", desc: "arrow,箭头,左下" },
				{ name: "corner-down-right", desc: "arrow,箭头,下右" },
				{ name: "arrow-up-circle", desc: "箭头,向上" },
				{ name: "arrow-right-circle", desc: "forward,箭头,向右" },
				{ name: "arrow-down-circle", desc: "箭头,向下,下载" },
				{ name: "arrow-left-circle", desc: "backward,箭头,向左,返回" },
				{ name: "arrow-up-s", desc: "chevron,箭头,向上" },
				{ name: "arrow-right-s", desc: "chevron,forward,箭头,向右" },
				{ name: "arrow-down-s", desc: "chevron,箭头,向下" },
				{
					name: "arrow-left-s",
					desc: "chevron,backward,箭头,向左,返回",
				},
				{
					name: "skip-up",
					desc: "arrow,unfold,top,expend,置顶,展开,收起",
				},
				{
					name: "skip-right",
					desc: "arrow,unfold,next,expend,跳过,展开,收起",
				},
				{
					name: "skip-down",
					desc: "arrow,unfold,next,expend,跳过,展开,收起",
				},
				{
					name: "skip-left",
					desc: "arrow,unfold,expend,bottom,展开,收起",
				},
				{
					name: "arrow-left-right",
					desc: "exchange,swap,箭头,左右,交换,换算,兑换",
				},
				{
					name: "arrow-up-down",
					desc: "exchange,swap,箭头,上下,交换,换算,兑换",
				},
				{ name: "arrow-drop-up", desc: "chevron,箭头,向上" },
				{ name: "arrow-drop-right", desc: "chevron,forward,箭头,向右" },
				{ name: "arrow-drop-down", desc: "chevron,箭头,向下" },
				{
					name: "arrow-drop-left",
					desc: "chevron,backward,箭头,向左,返回",
				},
				{
					name: "arrow-up-double",
					desc: "unfold,expend,top,chevron,展开,收起",
				},
				{
					name: "arrow-right-double",
					desc: "unfold,expend,chevron,展开,收起",
				},
				{
					name: "arrow-down-double",
					desc: "unfold,expend,chevron,展开,收起",
				},
				{
					name: "arrow-left-double",
					desc: "unfold,expend,chevron,展开,收起",
				},
				{
					name: "corner-up-left-double",
					desc: "arrow,replay-all,回复全部",
				},
				{
					name: "corner-up-right-double",
					desc: "arrow,forward-all,转发全部",
				},
				{ name: "drag-move", desc: "arrow,拖拽,移动,箭头" },
				{ name: "expand-left", desc: "slide,pull,unfold,arrow" },
				{ name: "expand-right", desc: "arrow,展开,收起,右" },
				{ name: "contract-left", desc: "slide,pull,fold,arrow" },
				{
					name: "contract-right",
					desc: "arrow,slide,pull,fold,展开,收起,右",
				},
				{
					name: "expand-up-down",
					desc: "arrow,unfold,dropdown,switch,展开",
				},
				{
					name: "expand-left-right",
					desc: "arrow,unfold,dropdown,switch",
				},
				{ name: "contract-up-down", desc: "arrow,fold,收起" },
				{ name: "contract-left-right", desc: "arrow,fold,收起" },
				{ name: "drag-move-2", desc: "arrow,拖拽,移动,箭头" },
				{ name: "arrow-go-back", desc: "undo,箭头,返回,撤销,撤回" },
				{ name: "arrow-go-forward", desc: "redo,箭头,重做,撤销,撤回" },
				{ name: "arrow-turn-forward", desc: "箭头,掉头" },
				{ name: "arrow-turn-back", desc: "箭头,掉头" },
			],
			size: 54,
		},
		{
			name: "建筑",
			namee: "Buildings",
			icons: [
				{ name: "home", desc: "house,房子,家,主页" },
				{ name: "home-2", desc: "house,房子,家,主页" },
				{ name: "home-3", desc: "house,房子,家,主页" },
				{ name: "home-4", desc: "house,房子,家,主页" },
				{ name: "home-5", desc: "house,房子,家,主页" },
				{ name: "home-6", desc: "house,房子,家,主页" },
				{ name: "home-7", desc: "house,房子,家,主页" },
				{ name: "home-8", desc: "house,房子,家,主页" },
				{ name: "home-gear", desc: "house,房子,工厂" },
				{ name: "home-wifi", desc: "smart home,房子,家具,智能家居" },
				{
					name: "home-smile",
					desc: "house,smart home,smile,房子,智能家居,微笑",
				},
				{
					name: "home-smile-2",
					desc: "house,smart home,smile,房子,智能家居,微笑",
				},
				{ name: "home-heart", desc: "house,心,房子,家,主页,孤儿院" },
				{ name: "home-office", desc: "居家办公" },
				{
					name: "building",
					desc: "city,office,enterprise,建筑,城市,楼,办公楼,写字楼,企业",
				},
				{
					name: "building-2",
					desc: "city,office,construction,enterprise,城市,建筑,楼,企业",
				},
				{
					name: "building-3",
					desc: "factory,plant,enterprise,工厂,建筑,楼,企业",
				},
				{
					name: "building-4",
					desc: "city,office,enterprise,建筑,城市,楼,办公楼,写字楼,企业",
				},
				{
					name: "hotel",
					desc: "building,hotel,office,enterprise,tavern,建筑,酒店,楼,办公楼,写字楼,企业",
				},
				{ name: "community", desc: "building,hotel,社区,建筑,酒店" },
				{ name: "school", desc: "college,university,学校,学院" },
				{ name: "government", desc: "building,政府,建筑,大会堂" },
				{
					name: "bank",
					desc: "bank,finance,savings,banking,银行,交易所",
				},
				{
					name: "store",
					desc: "shop,mall,supermarket,retail,商店,超市,店铺,商家",
				},
				{
					name: "store-2",
					desc: "shop,mall,supermarket,retail,商店,超市,店铺,商家",
				},
				{
					name: "store-3",
					desc: "shop,mall,supermarket,retail,商店,超市,店铺,商家",
				},
				{ name: "hospital", desc: "medical,health,医院" },
				{
					name: "ancient-gate",
					desc: "historical,genre,scenic,trip,travel,旅行,旅游,城门,古代,历史,景区",
				},
				{
					name: "ancient-pavilion",
					desc: "historical,genre,scenic,trip,travel,旅行,旅游,凉亭,古代,历史,景区",
				},
				{ name: "tent", desc: "camping,帐篷,露营,营地" },
			],
			size: 30,
		},
		{
			name: "商务",
			namee: "Business",
			icons: [
				{
					name: "mail",
					desc: "envelope,email,inbox,信封,邮箱,邮件,收件箱",
				},
				{
					name: "mail-open",
					desc: "envelope,email,inbox,信封,邮箱,邮件,收件箱",
				},
				{
					name: "mail-send",
					desc: "envelope,email,inbox,zoom,whoosh,信封,邮箱,邮件,发送,发件箱",
				},
				{
					name: "mail-unread",
					desc: "envelope,email,inbox,信封,邮箱,邮件,未读",
				},
				{
					name: "mail-add",
					desc: "envelope,email,inbox,add,信封,邮箱,邮件,新增,添加",
				},
				{
					name: "mail-check",
					desc: "envelope,email,inbox,read,信封,邮箱,邮件,已读",
				},
				{
					name: "mail-close",
					desc: "envelope,email,inbox,failed,x,信封,邮箱,邮件,失败",
				},
				{
					name: "mail-download",
					desc: "envelope,email,inbox,download,信封,邮箱,邮件,下载",
				},
				{
					name: "mail-forbid",
					desc: "envelope,email,inbox,privacy,信封,邮箱,邮件,禁止",
				},
				{
					name: "mail-lock",
					desc: "envelope,email,inbox,lock,信封,邮箱,邮件,加密",
				},
				{
					name: "mail-settings",
					desc: "envelope,email,inbox,settings,信封,邮箱,邮件,设置",
				},
				{
					name: "mail-star",
					desc: "envelope,email,inbox,favorite,信封,邮箱,邮件,收藏,喜欢",
				},
				{
					name: "mail-volume",
					desc: "envelope,email,inbox,promotional email,email campaign,subscription,sound,信封,邮箱,邮件,收件箱,推广,订阅",
				},
				{ name: "inbox", desc: "收件箱" },
				{ name: "inbox-2", desc: "收件箱" },
				{ name: "inbox-archive", desc: "收件箱,归档,收纳" },
				{
					name: "inbox-unarchive",
					desc: "unzip,unpack,extract,收件箱,取消归档,还原,解压缩",
				},
				{ name: "cloud", desc: "weather,云端" },
				{
					name: "cloud-off",
					desc: "offline mode,connection fail,slash,weather,云端,断网,无信号,连接失败",
				},
				{ name: "attachment", desc: "annex,paperclip,附件,曲别针" },
				{ name: "profile", desc: "id,档案,资料,身份证,证件" },
				{ name: "archive", desc: "box,收纳,归档,存档,盒子,纸箱" },
				{ name: "archive-2", desc: "box,收纳,归档,存档,盒子,纸箱" },
				{
					name: "archive-drawer",
					desc: "night table,收纳,抽屉,归档,存档,床头柜",
				},
				{
					name: "archive-stack",
					desc: "box,收纳,归档,存档,盒子,纸箱,堆叠",
				},
				{ name: "at", desc: "@,mention,提到,在" },
				{
					name: "award",
					desc: "medal,achievement,badge,成就,奖牌,金牌,勋章",
				},
				{
					name: "medal",
					desc: "award,achievement,badge,成就,奖牌,金牌,勋章",
				},
				{
					name: "medal-2",
					desc: "award,achievement,badge,成就,奖牌,金牌,勋章",
				},
				{ name: "verified-badge", desc: "认证标志" },
				{
					name: "bar-chart",
					desc: "statistics,rhythm,柱状图,统计,韵律,节奏",
				},
				{
					name: "bar-chart-horizontal",
					desc: "statistics,rhythm,柱状图,统计,韵律,节奏",
				},
				{
					name: "bar-chart-2",
					desc: "statistics,rhythm,柱状图,统计,排行,节奏",
				},
				{
					name: "bar-chart-box",
					desc: "statistics,rhythm,柱状图,统计,节奏",
				},
				{
					name: "bar-chart-grouped",
					desc: "statistics,rhythm,柱状图,统计,分组",
				},
				{
					name: "bubble-chart",
					desc: "data,analysis,statistics,circles,气泡图,统计",
				},
				{
					name: "pie-chart",
					desc: "data,analysis,饼图,饼状图,数据,分析",
				},
				{
					name: "pie-chart-2",
					desc: "data,analysis,饼图,饼状图,数据,分析",
				},
				{
					name: "pie-chart-box",
					desc: "data,analysis,饼图,饼状图,数据,分析",
				},
				{
					name: "donut-chart",
					desc: "data,analysis,circle,pie,环形图,数据,分析",
				},
				{
					name: "line-chart",
					desc: "data,analysis,stats,折线图,数据,分析",
				},
				{ name: "bookmark", desc: "tag,书签,标记" },
				{ name: "bookmark-2", desc: "tag,书签,标记" },
				{ name: "bookmark-3", desc: "tag,书签,标记,荣誉" },
				{
					name: "briefcase",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
				},
				{
					name: "briefcase-2",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
				},
				{
					name: "briefcase-3",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
				},
				{
					name: "briefcase-4",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
				},
				{
					name: "briefcase-5",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
				},
				{ name: "calculator", desc: "计算器,计算机" },
				{
					name: "calendar",
					desc: "date,plan,schedule,agenda,日历,日期,月份,计划,日程,时间表",
				},
				{
					name: "calendar-2",
					desc: "date,plan,schedule,agenda,日历,日期,月份,计划,日程,时间表",
				},
				{
					name: "calendar-event",
					desc: "date,plan,schedule,agenda,日历,日期,月份,计划,日程,时间表",
				},
				{
					name: "calendar-todo",
					desc: "date,plan,schedule,agenda,日历,日期,月份,计划,日程,时间表",
				},
				{
					name: "calendar-check",
					desc: "date,plan,schedule,agenda,check-in,punch,日历,日期,月份,计划,日程,时间表,签到,打卡",
				},
				{
					name: "calendar-close",
					desc: "date,plan,schedule,agenda,error,cancel,日历,日期,月份,计划,日程,时间表,取消,错误",
				},
				{
					name: "calendar-schedule",
					desc: "date,plan,schedule,agenda,date,time,日历,日期,月份,计划,日程,时间表,预定,预约",
				},
				{
					name: "customer-service",
					desc: "headset,headphones,earphones,客服,售后,耳机,耳麦",
				},
				{
					name: "customer-service-2",
					desc: "headset,headphones,earphones,smile,客服,售后,耳机,耳麦",
				},
				{ name: "flag", desc: "banner,pin,旗帜,旗子,国旗,标记" },
				{ name: "flag-2", desc: "banner,pin,旗帜,旗子,国旗,标记" },
				{
					name: "global",
					desc: "earth,union,world,language,地球,联合,世界,全球,语言",
				},
				{ name: "honour", desc: "honor,glory,锦旗,荣誉,荣耀,军衔" },
				{ name: "links", desc: "connection,address,联系,链接,地址" },
				{ name: "printer", desc: "打印机" },
				{ name: "printer-cloud", desc: "network,打印机,云打印" },
				{
					name: "record-mail",
					desc: "voice mail,tape,录音,留言,语音信箱,磁带",
				},
				{ name: "reply", desc: "forward,回复全部,回复所有" },
				{ name: "reply-all", desc: "forward,回复,答复,留言,转发" },
				{ name: "send-plane", desc: "发送,纸飞机" },
				{ name: "send-plane-2", desc: "发送,纸飞机" },
				{ name: "projector", desc: "projection,meeting,投影仪,会议室" },
				{
					name: "projector-2",
					desc: "projection,meeting,投影仪,会议室,极米",
				},
				{
					name: "slideshow",
					desc: "presentation,meeting,PPT,keynote,投影,放映,演示,演讲,幻灯片,会议室",
				},
				{
					name: "slideshow-2",
					desc: "presentation,meeting,投影,放映,演示,演讲,幻灯片,会议室",
				},
				{
					name: "slideshow-3",
					desc: "presentation,meeting,投影,放映,演示,演讲,视频会议,幻灯片,会议室",
				},
				{
					name: "slideshow-4",
					desc: "presentation,meeting,投影,放映,演示,演讲,可视对讲,幻灯片,会议室",
				},
				{
					name: "presentation",
					desc: "teaching,training,演讲,老师,培训",
				},
				{
					name: "window",
					desc: "browser,program,web,窗口,浏览器,程序,网站",
				},
				{
					name: "window-2",
					desc: "browser,program,web,窗口,浏览器,程序,网站",
				},
				{ name: "stack", desc: "layers,图层,叠加,堆栈" },
				{
					name: "shake-hands",
					desc: "cooperation,business,握手,合作,商务",
				},
				{
					name: "service",
					desc: "heart,handshake,cooperation,client,服务,握手,心,合作",
				},
				{ name: "registered", desc: "注册,商标" },
				{ name: "trademark", desc: "注册,商标" },
				{ name: "advertisement", desc: "ad,广告,推广" },
				{ name: "copyleft", desc: "著佐权" },
				{ name: "copyright", desc: "版权" },
				{ name: "creative-commons", desc: "知识共享" },
				{
					name: "creative-commons-by",
					desc: "attribution,copyright,版权,知识共享,署名",
				},
				{
					name: "creative-commons-nc",
					desc: "noncommercial,copyright,版权,知识共享,非商业用途",
				},
				{
					name: "creative-commons-nd",
					desc: "no derivative works,copyright,版权,知识共享,禁止演绎",
				},
				{
					name: "creative-commons-sa",
					desc: "share alike,copyright,版权,知识共享,相同方式共享",
				},
				{
					name: "creative-commons-zero",
					desc: "cc0,copyright,版权,知识共享",
				},
				{
					name: "megaphone",
					desc: "bullhorn,loudspeaker,commercial,campaign,扩音器,喇叭,广告,活动",
				},
				{ name: "pass-valid", desc: "passport,护照有效" },
				{ name: "pass-pending", desc: "passport,护照等待" },
				{ name: "pass-expired", desc: "passport,护照过期" },
				{ name: "seo", desc: "搜索引擎优化" },
			],
			size: 99,
		},
		{
			name: "社交",
			namee: "Communication",
			icons: [
				{
					name: "chat-1",
					desc: "message,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "chat-2",
					desc: "message,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "chat-3",
					desc: "message,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "chat-4",
					desc: "message,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "message",
					desc: "chat,comment,reply,消息,聊天,回复,评论",
				},
				{
					name: "message-2",
					desc: "chat,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "message-3",
					desc: "chat,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "chat-check",
					desc: "message,reply,comment,消息,聊天,回复,评论,已阅",
				},
				{
					name: "chat-delete",
					desc: "message,comment,消息,聊天,回复,评论,清除,删除",
				},
				{
					name: "chat-forward",
					desc: "message,comment,消息,聊天,转发",
				},
				{ name: "chat-upload", desc: "message,comment,消息,聊天,上传" },
				{ name: "chat-download", desc: "message,comment,消息,下载" },
				{
					name: "chat-new",
					desc: "message,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "chat-settings",
					desc: "message,comment,消息,聊天,回复,评论,设置",
				},
				{
					name: "chat-smile",
					desc: "message,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "chat-smile-2",
					desc: "message,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "chat-smile-3",
					desc: "message,reply,comment,消息,聊天,回复,评论",
				},
				{
					name: "chat-heart",
					desc: "message,reply,comment,消息,聊天,回复,评论,心,点赞,收藏",
				},
				{
					name: "chat-off",
					desc: "message,reply,comment,slash,消息,聊天,回复,评论,禁止,关闭",
				},
				{
					name: "feedback",
					desc: "message,comment,消息,聊天,回复,评论,反馈",
				},
				{
					name: "discuss",
					desc: "message,reply,comment,消息,聊天,回复,评论,讨论,群聊",
				},
				{
					name: "question-answer",
					desc: "message,reply,comment,消息,聊天,回复,评论,讨论,群聊",
				},
				{
					name: "questionnaire",
					desc: "message,comment,help,消息,聊天,回复,评论,讨论,调查问卷,帮助",
				},
				{ name: "video-chat", desc: "message,comment,消息,视频聊天" },
				{ name: "chat-voice", desc: "message,comment,消息,语音消息" },
				{
					name: "chat-quote",
					desc: "message,reply,comment,消息,引用回复",
				},
				{
					name: "chat-follow-up",
					desc: "message,reply,comment,消息,+1,跟帖",
				},
				{
					name: "chat-poll",
					desc: "message,vote,questionnaire,消息,投票,问卷调查",
				},
				{ name: "chat-history", desc: "message,历史消息,消息记录" },
				{ name: "chat-private", desc: "message,私密消息,密聊" },
				{ name: "chat-thread", desc: "topic,hashtag,话题,井号,哈希" },
				{ name: "speak", desc: "voice,讲话,声音" },
				{ name: "emoji-sticker", desc: "表情,贴纸" },
			],
			size: 33,
		},
		{
			name: "设计",
			namee: "Design",
			icons: [
				{ name: "pencil", desc: "edit,铅笔,编辑" },
				{ name: "edit", desc: "pencil,铅笔,编辑" },
				{ name: "edit-2", desc: "pencil,铅笔,编辑" },
				{ name: "ball-pen", desc: "圆珠笔" },
				{ name: "quill-pen", desc: "羽毛笔,钢笔,编辑" },
				{ name: "pen-nib", desc: "钢笔,笔尖" },
				{ name: "ink-bottle", desc: "墨水瓶" },
				{ name: "mark-pen", desc: "马克笔" },
				{ name: "markup", desc: "标记,马克" },
				{ name: "edit-box", desc: "编辑" },
				{ name: "edit-circle", desc: "编辑" },
				{ name: "sip", desc: "吸管,取色器" },
				{ name: "brush", desc: "笔刷,画笔,刷子" },
				{ name: "brush-2", desc: "刷子" },
				{ name: "brush-3", desc: "刷子" },
				{ name: "brush-4", desc: "刷子" },
				{ name: "paint-brush", desc: "填色,填充,刷子" },
				{
					name: "contrast",
					desc: "brightness,tonalit,对比度,亮度,色调",
				},
				{
					name: "contrast-2",
					desc: "moon,dark,brightness,tonalit,月亮,夜间,对比度,亮度,色调",
				},
				{ name: "drop", desc: "water,blur,模糊,水,滴" },
				{
					name: "blur-off",
					desc: "water,drop,slash,模糊,水,滴,禁止,关闭",
				},
				{
					name: "contrast-drop",
					desc: "water,brightness,tonalit,水,对比度,亮度,色调,滴",
				},
				{
					name: "contrast-drop-2",
					desc: "water,brightness,tonalit,水,对比度,亮度,色调,滴",
				},
				{ name: "color-filter", desc: "effect,滤镜,特效" },
				{ name: "compasses", desc: "圆规" },
				{ name: "compasses-2", desc: "圆规" },
				{ name: "scissors", desc: "剪刀,裁剪" },
				{ name: "scissors-cut", desc: "剪刀,裁剪" },
				{ name: "scissors-2", desc: "剪刀,裁剪,截屏" },
				{ name: "slice", desc: "knife,切图,切片,刀" },
				{
					name: "eraser",
					desc: "remove formatting,橡皮,擦除,清除格式",
				},
				{ name: "ruler", desc: "尺子" },
				{ name: "ruler-2", desc: "尺子" },
				{ name: "pencil-ruler", desc: "design,铅笔,尺子,文具,设计" },
				{ name: "pencil-ruler-2", desc: "design,铅笔,尺子,文具,设计" },
				{ name: "t-box", desc: "文字,字体,字号" },
				{ name: "input-method", desc: "输入法,文字" },
				{ name: "artboard", desc: "grid,crop,画板,裁切" },
				{ name: "artboard-2", desc: "画板" },
				{ name: "crop", desc: "裁切" },
				{ name: "crop-2", desc: "裁切" },
				{ name: "screenshot", desc: "capture,屏幕截图,截屏" },
				{ name: "screenshot-2", desc: "capture,屏幕截图,截屏" },
				{ name: "focus", desc: "aim,target,goal,焦点,聚焦,目标,靶心" },
				{
					name: "focus-2",
					desc: "aim,target,goal,bullseye,焦点,聚焦,目标,靶心",
				},
				{
					name: "focus-3",
					desc: "aim,target,goal,bullseye,crosshair,locate,焦点,聚焦,目标,靶心,瞄准镜,准心,定位",
				},
				{
					name: "crosshair",
					desc: "aim,target,goal,bullseye,crosshair,locate,焦点,聚焦,目标,靶心,瞄准镜,准心,定位",
				},
				{
					name: "crosshair-2",
					desc: "aim,target,goal,bullseye,crosshair,locate,焦点,聚焦,目标,靶心,瞄准镜,准心,定位",
				},
				{ name: "paint", desc: "fill,填色,填充,油漆桶" },
				{ name: "palette", desc: "color,调色盘,色板" },
				{ name: "pantone", desc: "color,色板,潘通色,色号" },
				{ name: "shape", desc: "border,形状,描边,边框" },
				{ name: "shape-2", desc: "border,形状,描边,边框" },
				{
					name: "magic",
					desc: "fantasy,magic stick,beautify,wand,魔法棒,美化,幻想,魔幻",
				},
				{
					name: "anticlockwise",
					desc: "rotate,left,counterclockwise,左翻转,左旋转",
				},
				{
					name: "anticlockwise-2",
					desc: "rotate,left,counterclockwise,左翻转,左旋转",
				},
				{ name: "clockwise", desc: "rotate,right,右翻转,右旋转" },
				{ name: "clockwise-2", desc: "rotate,right,右翻转,右旋转" },
				{ name: "hammer", desc: "tool,锤子" },
				{
					name: "tools",
					desc: "settings,screwdriver,configuration,工具,设置",
				},
				{ name: "drag-drop", desc: "drag and drop,mouse,拖拽,鼠标" },
				{ name: "table", desc: "表格" },
				{ name: "table-alt", desc: "表格" },
				{ name: "layout", desc: "布局" },
				{ name: "layout-2", desc: "collage,布局,拼贴画" },
				{ name: "layout-3", desc: "collage,布局,拼贴画" },
				{ name: "layout-4", desc: "collage,布局,拼贴画" },
				{ name: "layout-5", desc: "collage,布局,拼贴画" },
				{ name: "layout-6", desc: "collage,布局,拼贴画" },
				{ name: "layout-column", desc: "左右布局" },
				{ name: "layout-row", desc: "上下布局" },
				{ name: "layout-top", desc: "顶部布局,顶部导航" },
				{ name: "layout-right", desc: "右侧布局,右侧导航" },
				{ name: "layout-bottom", desc: "底部布局,底部导航" },
				{ name: "layout-left", desc: "左侧布局,左侧导航" },
				{ name: "layout-top-2", desc: "顶部布局,顶部导航" },
				{ name: "layout-right-2", desc: "右侧布局,右侧导航" },
				{ name: "layout-bottom-2", desc: "底部布局,底部导航" },
				{ name: "layout-left-2", desc: "左侧布局,左侧导航" },
				{ name: "layout-grid", desc: "卡片布局,网格" },
				{ name: "layout-masonry", desc: "collage,瀑布流布局,拼贴画" },
				{ name: "collage", desc: "瀑布流布局,拼贴画" },
				{ name: "grid", desc: "table,网格,表格" },
				{ name: "circle", desc: "圆形" },
				{ name: "triangle", desc: "三角形" },
				{ name: "pentagon", desc: "五边形,五角形" },
				{ name: "hexagon", desc: "六边形" },
				{ name: "octagon", desc: "八边形" },
				{ name: "square", desc: "正方形" },
				{ name: "rectangle", desc: "长方形,矩形" },
				{ name: "shapes", desc: "形状,模块" },
				{ name: "shadow", desc: "投影,影子" },
			],
			size: 92,
		},
		{
			name: "开发",
			namee: "Development",
			icons: [
				{ name: "bug", desc: "虫子" },
				{ name: "bug-2", desc: "虫子" },
				{ name: "code", desc: "代码,编程" },
				{ name: "code-s", desc: "代码,编程" },
				{ name: "code-s-slash", desc: "代码,编程" },
				{ name: "code-box", desc: "代码,编程" },
				{
					name: "terminal-box",
					desc: "code,command line,prompt,终端,代码,命令行",
				},
				{
					name: "terminal",
					desc: "code,command line,prompt,终端,代码,命令行",
				},
				{
					name: "terminal-window",
					desc: "code,command line,browser,app,ui,终端,代码,命令行",
				},
				{ name: "parentheses", desc: "code,math,小括号" },
				{ name: "brackets", desc: "code,math,中括号" },
				{ name: "braces", desc: "code,math,大括号,花括号" },
				{
					name: "command",
					desc: "apple key,place of interest,modified key,花键,苹果键",
				},
				{ name: "cursor", desc: "mouse,pointer,arrow,指针,鼠标" },
				{
					name: "git-commit",
					desc: "node,onewheel,circle line,dot line,history point,提交",
				},
				{ name: "git-pull-request", desc: "合并申请" },
				{
					name: "git-merge",
					desc: "combine,unite,branch,split,diverge,合并",
				},
				{
					name: "git-branch",
					desc: "combine,unite,split,diverge,分支",
				},
				{ name: "git-fork", desc: "" },
				{ name: "git-close-pull-request", desc: "取消,关闭" },
				{ name: "git-repository", desc: "book,bookmark,仓库" },
				{
					name: "git-repository-commits",
					desc: "book,upload,仓库,提交",
				},
				{
					name: "git-repository-private",
					desc: "lock,secure,私密仓库,私人仓库",
				},
				{ name: "html5", desc: "html,h5,web" },
				{ name: "css3", desc: "css,web,styles" },
				{ name: "javascript", desc: "js,脚本" },
				{ name: "puzzle", desc: "plugins,拼图,插件" },
				{ name: "puzzle-2", desc: "plugins,拼图,插件" },
			],
			size: 28,
		},
		{
			name: "设备",
			namee: "Device",
			icons: [
				{ name: "tv", desc: "television,antenna,rabbet ears,电视" },
				{
					name: "tv-2",
					desc: "monitor,display,screen,television,电视,显示器",
				},
				{
					name: "computer",
					desc: "pc,monitor,display,screen,电脑,显示器",
				},
				{
					name: "mac",
					desc: "monitor,imac,display,computer,screen,显示器",
				},
				{ name: "macbook", desc: "laptop,computer,笔记本" },
				{ name: "cellphone", desc: "手机,电话" },
				{ name: "smartphone", desc: "mobile,手机" },
				{ name: "tablet", desc: "平板电脑" },
				{ name: "device", desc: "设备" },
				{ name: "phone", desc: "电话" },
				{ name: "instance", desc: "box,nft,cvm,实例,盒子,虚拟机" },
				{
					name: "database",
					desc: "storage,resource,bars,progress,数据库,存储",
				},
				{
					name: "database-2",
					desc: "storage,discs,silo,platter,数据库,存储",
				},
				{ name: "server", desc: "服务器" },
				{ name: "hard-drive", desc: "disc,storage,硬盘,存储" },
				{
					name: "hard-drive-2",
					desc: "disc,server,storage,硬盘,服务器,存储",
				},
				{
					name: "hard-drive-3",
					desc: "disc,server,storage,硬盘,服务器,存储",
				},
				{ name: "install", desc: "安装" },
				{ name: "uninstall", desc: "卸载" },
				{ name: "save", desc: "floppy,保存,软盘" },
				{ name: "save-2", desc: "floppy,保存,软盘" },
				{ name: "save-3", desc: "floppy,保存,软盘" },
				{ name: "sd-card", desc: "内存卡" },
				{ name: "sd-card-mini", desc: "内存卡" },
				{ name: "sim-card", desc: "电话卡" },
				{ name: "sim-card-2", desc: "电话卡" },
				{ name: "dual-sim-1", desc: "sim card,电话卡,卡槽,双卡双待" },
				{ name: "dual-sim-2", desc: "sim card,电话卡,卡槽,双卡双待" },
				{ name: "u-disk", desc: "U盘,优盘" },
				{ name: "battery", desc: "电池" },
				{ name: "battery-charge", desc: "电池,充电" },
				{ name: "battery-low", desc: "电池,低电量" },
				{ name: "battery-2", desc: "电池" },
				{ name: "battery-2-charge", desc: "电池,充电" },
				{ name: "battery-saver", desc: "电池,省电模式" },
				{ name: "battery-share", desc: "电池共享,共享电量" },
				{ name: "cast", desc: "mirroring,投屏,无线,广播" },
				{ name: "airplay", desc: "mirroring,投屏,无线" },
				{ name: "cpu", desc: "中央处理器" },
				{ name: "gradienter", desc: "水平仪" },
				{ name: "keyboard", desc: "input,键盘,输入" },
				{ name: "keyboard-box", desc: "input,键盘,输入" },
				{ name: "mouse", desc: "鼠标" },
				{ name: "sensor", desc: "capacitor,传感器,电容器" },
				{
					name: "router",
					desc: "wifi,signal tower,radio,station,路由器,信号塔,广播,基站,流量",
				},
				{
					name: "radar",
					desc: "satellite receiver,雷达,卫星接收器,锅",
				},
				{ name: "gamepad", desc: "consoles,controller,游戏手柄" },
				{ name: "remote-control", desc: "controller,遥控器" },
				{ name: "remote-control-2", desc: "controller,遥控器" },
				{ name: "device-recover", desc: "恢复出厂设置" },
				{ name: "hotspot", desc: "手机热点" },
				{ name: "phone-find", desc: "找回手机" },
				{ name: "phone-lock", desc: "锁定手机" },
				{ name: "rotate-lock", desc: "锁定旋转屏幕" },
				{ name: "restart", desc: "reload,refresh,重启" },
				{ name: "shut-down", desc: "power off,关机" },
				{ name: "fingerprint", desc: "指纹" },
				{ name: "fingerprint-2", desc: "指纹" },
				{ name: "barcode", desc: "scan,扫码,条形码,条码" },
				{ name: "barcode-box", desc: "scan,扫码,条形码,条码" },
				{ name: "qr-code", desc: "二维码" },
				{ name: "qr-scan", desc: "二维码,扫描" },
				{ name: "qr-scan-2", desc: "二维码,扫描" },
				{ name: "scan", desc: "扫描" },
				{ name: "scan-2", desc: "扫描" },
				{ name: "rss", desc: "feed,subscribe,订阅" },
				{ name: "gps", desc: "signal,定位,信号" },
				{
					name: "base-station",
					desc: "wifi,signal tower,router,cast,基站,信号塔,路由器,广播,流量",
				},
				{ name: "bluetooth", desc: "wireless,蓝牙,无线" },
				{ name: "bluetooth-connect", desc: "wireless,蓝牙,连接,无线" },
				{ name: "wifi", desc: "无线网" },
				{
					name: "wifi-off",
					desc: "slash,offline,connection-fail,无线网,关闭,断网,链接失败",
				},
				{ name: "signal-wifi", desc: "cellular,strength,无线网,信号" },
				{
					name: "signal-wifi-1",
					desc: "cellular,strength,无线网,信号",
				},
				{
					name: "signal-wifi-2",
					desc: "cellular,strength,无线网,信号",
				},
				{
					name: "signal-wifi-3",
					desc: "cellular,strength,无线网,信号",
				},
				{
					name: "signal-wifi-error",
					desc: "cellular,offline,connection-fail,无线网,断网,链接失败,无信号",
				},
				{
					name: "signal-wifi-off",
					desc: "cellular,slash,offline,connection-fail,无线网,关闭,断网,链接失败",
				},
				{
					name: "wireless-charging",
					desc: "power,flash,无线充电,闪充",
				},
				{ name: "dashboard-2", desc: "仪表盘" },
				{ name: "dashboard-3", desc: "仪表盘" },
				{ name: "usb", desc: "优盘" },
				{
					name: "rfid",
					desc: "radio,frequency,identification,devices,无线,射频识别",
				},
				{ name: "ram-2", desc: "memory,electronics,内存条,记忆卡" },
				{ name: "ram", desc: "memory,electronics,内存条,记忆卡" },
			],
			size: 85,
		},
		{
			name: "文档",
			namee: "Document",
			icons: [
				{ name: "file", desc: "new,paper,文件,文档,新建" },
				{ name: "file-2", desc: "new,paper,文件,文档,新建" },
				{ name: "file-3", desc: "new,paper,文件,文档,新建" },
				{ name: "file-4", desc: "new,paper,文件,文档,新建" },
				{
					name: "sticky-note",
					desc: "new,paper,文件,文档,新建,便签纸,便利贴",
				},
				{
					name: "sticky-note-add",
					desc: "new,paper,文件,文档,新建,便签纸,便利贴,添加",
				},
				{
					name: "sticky-note-2",
					desc: "new,paper,文件,文档,新建,便签纸,便利贴",
				},
				{ name: "file-edit", desc: "文件,文档,编辑" },
				{ name: "draft", desc: "草稿箱,文件,文档,编辑" },
				{ name: "file-paper", desc: "文件,文档,纸,谱" },
				{ name: "file-paper-2", desc: "文件,文档,纸,谱" },
				{ name: "receipt", desc: "收据,凭据" },
				{ name: "file-text", desc: "文件,文档,文本" },
				{ name: "file-list", desc: "清单,列表" },
				{ name: "file-list-2", desc: "清单,列表" },
				{ name: "file-list-3", desc: "newspaper,清单,列表,报纸" },
				{ name: "bill", desc: "账单" },
				{ name: "file-copy", desc: "duplicate,clone,复制,克隆" },
				{ name: "file-copy-2", desc: "duplicate,clone,复制,克隆" },
				{ name: "clipboard", desc: "copy,复制,剪切板" },
				{
					name: "survey",
					desc: "research,questionnaire,clipboard,checkboxes,form,census,调查,问卷,调研",
				},
				{
					name: "article",
					desc: "newspaper,document,publisher,print,page,word,file,publication,文章,报纸",
				},
				{ name: "newspaper", desc: "新闻,报纸" },
				{ name: "news", desc: "blog,新闻,博客" },
				{ name: "file-zip", desc: "7z,rar,压缩包" },
				{ name: "file-marked", desc: "文件,文档,标记" },
				{ name: "task", desc: "todo,任务,待办" },
				{ name: "todo", desc: "待办" },
				{
					name: "book",
					desc: "read,dictionary,booklet,书,阅读,字典,小册子",
				},
				{
					name: "book-marked",
					desc: "read,dictionary,booklet,书,阅读,字典,小册子,书签",
				},
				{
					name: "book-2",
					desc: "read,dictionary,booklet,书,阅读,字典,小册子",
				},
				{
					name: "book-3",
					desc: "read,dictionary,booklet,书,阅读,字典,小册子",
				},
				{
					name: "book-open",
					desc: "read,booklet,magazine,书,阅读,小册子,杂志",
				},
				{
					name: "book-read",
					desc: "booklet,magazine,书,阅读,小册子,杂志",
				},
				{ name: "contacts-book", desc: "通讯录,联系人" },
				{ name: "contacts-book-2", desc: "通讯录,联系人" },
				{
					name: "contacts-book-upload",
					desc: "upload,通讯录,联系人,上传",
				},
				{ name: "booklet", desc: "notebook,手册,笔记本,小册子" },
				{ name: "contacts-book-3", desc: "通讯录,联系人" },
				{
					name: "file-code",
					desc: "config,文件,文档,代码,脚本,配置文件",
				},
				{ name: "file-pdf", desc: "文件,文档" },
				{ name: "file-pdf-2", desc: "文件,文档" },
				{ name: "file-word", desc: "文档" },
				{ name: "file-ppt", desc: "文件,文档" },
				{ name: "file-excel", desc: "文档,表单" },
				{ name: "file-word-2", desc: "文档" },
				{ name: "file-ppt-2", desc: "文件,文档" },
				{ name: "file-excel-2", desc: "文档,表单" },
				{ name: "file-hwp", desc: "文件,文档,hangul word processor" },
				{ name: "keynote", desc: "演示文稿,幻灯片,讲演" },
				{ name: "numbers", desc: "表格" },
				{
					name: "pages",
					desc: "website,browser,ui,blocks,prototype,文稿",
				},
				{ name: "file-search", desc: "文件,文档,搜索" },
				{
					name: "file-add",
					desc: "page,document,new,plus,add,文件,文档,新建",
				},
				{
					name: "file-reduce",
					desc: "page,document,subtract,delete,文件,文档,减",
				},
				{
					name: "file-settings",
					desc: "page,document,cog,gear,文件,文档,设置",
				},
				{ name: "file-upload", desc: "page,document,文件,文档,上传" },
				{ name: "file-transfer", desc: "page,document,文件,文档,传输" },
				{ name: "file-download", desc: "page,document,文件,文档,下载" },
				{ name: "file-lock", desc: "page,document,文件,文档,锁" },
				{
					name: "file-chart",
					desc: "page,document,report,文件,文档,柱状图,报表",
				},
				{ name: "file-chart-2", desc: "report,文件,文档,饼图,报表" },
				{ name: "file-image", desc: "文件,文档,图片" },
				{ name: "file-music", desc: "文件,文档,音乐" },
				{ name: "file-video", desc: "文件,文档,视频" },
				{ name: "file-gif", desc: "文件,文档,动图" },
				{ name: "file-check", desc: "文件,文档,对勾" },
				{ name: "file-close", desc: "文件,文档,关闭,删除,错误" },
				{ name: "file-forbid", desc: "文件,文档,禁用" },
				{ name: "file-info", desc: "文件,文档,信息" },
				{
					name: "file-warning",
					desc: "page,document,paper,!,alert,important,exclamation,文件,文档,警告,提醒",
				},
				{ name: "file-unknow", desc: "文件,文档,未知,问号" },
				{ name: "file-user", desc: "文件,文档,用户" },
				{
					name: "file-shield",
					desc: "protected,secured,文件,文档,盾牌,保护,安全",
				},
				{
					name: "file-shield-2",
					desc: "protected,secured,文件,文档,盾牌,保护,安全",
				},
				{
					name: "file-damage",
					desc: "breakdown,broken,corrupt,文件,文档,损坏,破损,破裂",
				},
				{ name: "file-history", desc: "record,文件,文档,记录,历史" },
				{
					name: "file-shred",
					desc: "shredder,shred,destroy,cut,文档,销毁,碎纸机,破裂,粉碎",
				},
				{ name: "file-cloud", desc: "network,文件,文档,云" },
				{
					name: "contract",
					desc: "examine,apporove,合约,合同,考试,审批通过",
				},
				{ name: "folder", desc: "directory,file,文件夹,目录,文档" },
				{ name: "folder-2", desc: "directory,file,文件夹,目录,文档" },
				{ name: "folder-3", desc: "directory,file,文件夹,目录,文档" },
				{ name: "folder-4", desc: "directory,file,文件夹,目录,文档" },
				{ name: "folder-5", desc: "directory,file,文件夹,目录,文档" },
				{ name: "folder-6", desc: "directory,file,文件夹,目录,文档" },
				{
					name: "folders",
					desc: "directory,file,文件夹,目录,文档,批量",
				},
				{
					name: "folder-add",
					desc: "directory,file,文件夹,目录,文档,添加",
				},
				{
					name: "folder-reduce",
					desc: "directory,file,remove,subtract,文件夹,目录,文档,减",
				},
				{
					name: "folder-settings",
					desc: "directory,file,文件夹,目录,文档,设置",
				},
				{
					name: "folder-upload",
					desc: "directory,file,文件夹,目录,文档,上传",
				},
				{
					name: "folder-transfer",
					desc: "directory,file,文件夹,目录,文档,传输",
				},
				{
					name: "folder-download",
					desc: "directory,file,文件夹,目录,文档,下载",
				},
				{
					name: "folder-lock",
					desc: "directory,file,文件夹,目录,文档,锁",
				},
				{
					name: "folder-chart",
					desc: "report,文件夹,目录,文档,柱状图,报表",
				},
				{
					name: "folder-chart-2",
					desc: "report,文件夹,目录,文档,饼图,报表",
				},
				{
					name: "folder-music",
					desc: "directory,file,audio,sound,文件夹,目录,文档,音乐",
				},
				{
					name: "folder-image",
					desc: "directory,file,文件夹,目录,文档,图片",
				},
				{
					name: "folder-video",
					desc: "directory,file,文件夹,目录,文档,视频",
				},
				{
					name: "folder-check",
					desc: "directory,file,文件夹,目录,文档,对勾",
				},
				{
					name: "folder-close",
					desc: "directory,file,文件夹,目录,文档,错误",
				},
				{
					name: "folder-forbid",
					desc: "directory,file,文件夹,目录,文档,禁用",
				},
				{
					name: "folder-info",
					desc: "directory,file,文件夹,目录,文档,信息",
				},
				{
					name: "folder-warning",
					desc: "!,alert,important,exclamation,alert,directory,file,文件夹,目录,文档,警告,提醒",
				},
				{
					name: "folder-unknow",
					desc: "directory,file,文件夹,目录,文档,未知",
				},
				{
					name: "folder-user",
					desc: "directory,file,文件夹,目录,文档,用户",
				},
				{
					name: "folder-shield",
					desc: "directory,file,protected,secured,文件夹,目录,文档,保护,盾牌,安全",
				},
				{
					name: "folder-shield-2",
					desc: "directory,file,protected,secured,文件夹,目录,文档,保护,盾牌,安全",
				},
				{
					name: "folder-shared",
					desc: "directory,file,文件夹,目录,文档,分享",
				},
				{
					name: "folder-received",
					desc: "directory,file,文件夹,目录,文档,接收",
				},
				{
					name: "folder-open",
					desc: "directory,file,文件夹,目录,文档,打开",
				},
				{
					name: "folder-keyhole",
					desc: "directory,encryption,file,文件夹,目录,文档,打开,加密文档",
				},
				{
					name: "folder-zip",
					desc: "directory,file,文件夹,目录,文档,打开,压缩",
				},
				{
					name: "folder-history",
					desc: "directory,file,record,文件夹,目录,文档,记录,历史",
				},
				{
					name: "folder-cloud",
					desc: "directory,file,云文件夹,目录,云文档",
				},
				{ name: "markdown", desc: "arrow,箭头,下" },
			],
			size: 116,
		},
		{
			name: "编辑",
			namee: "Editor",
			icons: [
				{ name: "bold", desc: "加粗" },
				{ name: "italic", desc: "斜体" },
				{ name: "heading", desc: "标题" },
				{ name: "text", desc: "字体" },
				{ name: "font-family", desc: "字体" },
				{ name: "font-sans-serif", desc: "衬线体" },
				{ name: "font-sans", desc: "非衬线体" },
				{ name: "font-mono", desc: "等宽字体" },
				{ name: "font-color", desc: "文字色" },
				{ name: "font-size", desc: "字号,字体大小" },
				{ name: "font-size-2", desc: "字号,字体大小" },
				{ name: "underline", desc: "下划线" },
				{ name: "overline", desc: "上划线" },
				{ name: "emphasis", desc: "着重号" },
				{ name: "emphasis-cn", desc: "着重号" },
				{ name: "strikethrough", desc: "remove formatting,del,删除线" },
				{
					name: "strikethrough-2",
					desc: "remove formatting,del,删除线",
				},
				{ name: "format-clear", desc: "remove formatting,清除格式" },
				{ name: "align-left", desc: "ragged right,左对齐" },
				{ name: "align-center", desc: "居中对齐" },
				{ name: "align-right", desc: "ragged left,右对齐" },
				{
					name: "align-justify",
					desc: "four,lines,ruled,left-right,full width,排列对齐",
				},
				{
					name: "align-top",
					desc: "two arrows up,double-up,start,顶部对齐",
				},
				{
					name: "align-vertically",
					desc: "centered,middle,balance,垂直对齐",
				},
				{
					name: "align-bottom",
					desc: "two arrows down,double-down,end,底部对齐",
				},
				{ name: "list-check", desc: "check list,清单列表" },
				{ name: "list-check-2", desc: "check list,清单列表" },
				{ name: "list-check-3", desc: "check list,清单列表,问卷,task" },
				{ name: "list-ordered", desc: "numbered list,有序列表" },
				{ name: "list-ordered-2", desc: "numbered list,有序列表" },
				{ name: "list-unordered", desc: "bullet list,无序列表" },
				{ name: "list-radio", desc: "vote,投票,列表" },
				{ name: "list-indefinite", desc: "列表" },
				{ name: "indent-decrease", desc: "indent more,quote,缩进" },
				{ name: "indent-increase", desc: "indent less,quote,缩进" },
				{ name: "line-height", desc: "leading,行高" },
				{
					name: "text-spacing",
					desc: "letter spacing,character spacing,kerning,tracking,字间距",
				},
				{ name: "text-wrap", desc: "return,文本换行" },
				{ name: "attachment-2", desc: "annex,paperclip,附件,曲别针" },
				{ name: "link", desc: "connection,address,联系,链接,地址" },
				{
					name: "link-unlink",
					desc: "connection,remove address,去除链接",
				},
				{ name: "link-m", desc: "connection,address,联系,链接,地址" },
				{
					name: "link-unlink-m",
					desc: "connection,remove address,去除链接",
				},
				{ name: "separator", desc: "分割线" },
				{ name: "space", desc: "空格" },
				{ name: "page-separator", desc: "insert,分页符,插入" },
				{ name: "code-view", desc: "代码视图" },
				{ name: "quote-text", desc: "引用" },
				{ name: "double-quotes-l", desc: "left,quotaion marks,双引号" },
				{
					name: "double-quotes-r",
					desc: "right,quotaion marks,双引号",
				},
				{ name: "single-quotes-l", desc: "left,quotaion marks,单引号" },
				{
					name: "single-quotes-r",
					desc: "right,quotaion marks,单引号",
				},
				{ name: "table-2", desc: "表格" },
				{ name: "table-3", desc: "表格" },
				{ name: "subscript", desc: "角标,下标,脚注" },
				{ name: "subscript-2", desc: "角标,下标,脚注" },
				{ name: "superscript", desc: "角标,上标" },
				{ name: "superscript-2", desc: "角标,上标" },
				{ name: "paragraph", desc: "¶,pilcrow,段落" },
				{ name: "text-direction-l", desc: "文本左对齐" },
				{ name: "text-direction-r", desc: "文本左对齐" },
				{ name: "functions", desc: "Σ,sum,sigma,功能" },
				{ name: "omega", desc: "Ω,horseshoe,特殊符号" },
				{ name: "hashtag", desc: "#,pound,number,井号" },
				{ name: "asterisk", desc: "*,all,everything,wildcard,星号" },
				{ name: "question-mark", desc: "?,问号" },
				{ name: "info-i", desc: "information,信息" },
				{ name: "translate", desc: "translator,翻译" },
				{ name: "translate-2", desc: "translator,翻译" },
				{
					name: "a-b",
					desc: "a/b testing,ab testing,split test,either-or,ab测试",
				},
				{ name: "english-input", desc: "英文输入法" },
				{ name: "pinyin-input", desc: "拼音输入法" },
				{ name: "wubi-input", desc: "五笔输入法" },
				{ name: "input-cursor-move", desc: "移动输入光标" },
				{ name: "number-1", desc: "1,一,数字" },
				{ name: "number-2", desc: "2,二,数字" },
				{ name: "number-3", desc: "3,三,数字" },
				{ name: "number-4", desc: "4,四,数字" },
				{ name: "number-5", desc: "5,五,数字" },
				{ name: "number-6", desc: "6,六,数字" },
				{ name: "number-7", desc: "7,七,数字" },
				{ name: "number-8", desc: "8,八,数字" },
				{ name: "number-9", desc: "9,九,数字" },
				{ name: "number-0", desc: "0,零,数字" },
				{
					name: "sort-asc",
					desc: "ranking,ordering,sorting,ascending,descending,升序排列,排序,顺序",
				},
				{ name: "sort-desc", desc: "ranking,ordering,降序排列,排序" },
				{
					name: "sort-alphabet-asc",
					desc: "ranking,ordering,升序排列,数字排序,顺序",
				},
				{
					name: "sort-alphabet-desc",
					desc: "ranking,ordering,降序排列,字母排序,倒序,倒序",
				},
				{
					name: "sort-number-asc",
					desc: "ranking,ordering,升序排列,数字排序,顺序",
				},
				{
					name: "sort-number-desc",
					desc: "ranking,ordering,降序排列,数字排序,倒序",
				},
				{ name: "bring-forward", desc: "arrange,层级,向上一层" },
				{ name: "send-backward", desc: "arrange,层级,向下一层" },
				{ name: "bring-to-front", desc: "arrange,层级,移到最前面" },
				{ name: "send-to-back", desc: "arrange,层级,移到最后面" },
				{ name: "h-1", desc: "heading,一级标题" },
				{ name: "h-2", desc: "heading,一级标题" },
				{ name: "h-3", desc: "heading,一级标题" },
				{ name: "h-4", desc: "heading,一级标题" },
				{ name: "h-5", desc: "heading,一级标题" },
				{ name: "h-6", desc: "heading,一级标题" },
				{ name: "insert-column-left", desc: "添加列,左侧" },
				{ name: "insert-column-right", desc: "添加列,右侧" },
				{ name: "insert-row-top", desc: "添加行,顶部" },
				{ name: "insert-row-bottom", desc: "添加行,底部" },
				{ name: "delete-column", desc: "删除列,底部" },
				{ name: "delete-row", desc: "添加行,底部" },
				{ name: "merge-cells-horizontal", desc: "合并单元格" },
				{ name: "merge-cells-vertical", desc: "合并单元格" },
				{ name: "split-cells-horizontal", desc: "拆分单元格" },
				{ name: "split-cells-vertical", desc: "拆分单元格" },
				{ name: "flow-chart", desc: "流程图" },
				{ name: "mind-map", desc: "mindmap,脑图,思维导图" },
				{ name: "node-tree", desc: "节点,层级关系图" },
				{ name: "organization-chart", desc: "组织架构图,局域网" },
				{ name: "rounded-corner", desc: "圆角" },
				{ name: "sketching", desc: "signature,手写,手绘,签名" },
				{ name: "draggable", desc: "move,reorder,拖拽,排序" },
				{ name: "slash-commands", desc: "命令,斜线" },
				{ name: "slash-commands-2", desc: "命令,斜线" },
				{ name: "ai-generate", desc: "AI自动生成" },
				{ name: "dropdown-list", desc: "下拉菜单" },
				{ name: "code-block", desc: "代码块" },
				{ name: "text-snippet", desc: "文字片段,剪切板" },
				{ name: "text-block", desc: "文字块,文字片段" },
				{ name: "table-view", desc: "表格视图" },
				{ name: "kanban-view", desc: "看板视图" },
				{ name: "kanban-view-2", desc: "看板视图" },
				{ name: "gallery-view", desc: "画廊视图" },
				{ name: "gallery-view-2", desc: "画廊视图" },
				{ name: "timeline-view", desc: "时间轴视图,甘特图" },
				{ name: "calendar-view", desc: "日历视图" },
				{ name: "list-view", desc: "列表视图" },
				{ name: "focus-mode", desc: "聚焦模式,沉浸模式" },
				{ name: "slideshow-view", desc: "幻灯片视图" },
				{ name: "stacked-view", desc: "堆叠视图" },
				{ name: "carousel-view", desc: "循环播放视图" },
				{ name: "input-field", desc: "cursor,输入框,光标" },
				{ name: "hand", desc: "手,拖拽" },
			],
			size: 138,
		},
		{
			name: "金融",
			namee: "Finance",
			icons: [
				{ name: "wallet", desc: "pocketbook,钱包,卡包" },
				{ name: "wallet-2", desc: "money clip,钱包,卡包" },
				{ name: "wallet-3", desc: "money clip,钱包,卡包" },
				{
					name: "bank-card",
					desc: "credit,purchase,payment,cc,银行卡,信用卡,购买,消费,支付",
				},
				{
					name: "bank-card-2",
					desc: "credit,purchase,payment,cc,银行卡,信用卡,购买,消费,支付",
				},
				{
					name: "secure-payment",
					desc: "credit,purchase,payment,cc,银行卡,信用卡,购买,消费,支付,安全",
				},
				{
					name: "refund",
					desc: "credit card,repayment,cc,银行卡,信用卡还款",
				},
				{
					name: "refund-2",
					desc: "credit card,repayment,cc,银行卡,信用卡还款",
				},
				{ name: "safe", desc: "vault,secure,保险柜,保险箱" },
				{
					name: "safe-2",
					desc: "vault,insecure,unlocked,保险柜,保险箱",
				},
				{ name: "price-tag", desc: "label,标签,价签" },
				{ name: "price-tag-2", desc: "label,标签,价签" },
				{ name: "price-tag-3", desc: "label,标签,价签" },
				{ name: "ticket", desc: "coupon,票,优惠券,代金券" },
				{ name: "ticket-2", desc: "coupon,票,优惠券,代金券" },
				{ name: "coupon", desc: "ticket,票,优惠券,代金券" },
				{ name: "coupon-2", desc: "ticket,票,优惠券,代金券" },
				{ name: "coupon-3", desc: "ticket,票,优惠券,代金券" },
				{ name: "coupon-4", desc: "优惠券,代金券" },
				{ name: "coupon-5", desc: "优惠券,代金券" },
				{ name: "shopping-bag", desc: "purse,购物袋,购买,消费,商城" },
				{ name: "shopping-bag-2", desc: "购物袋,购买,消费,商城" },
				{ name: "shopping-bag-3", desc: "购物袋,购买,消费,商城" },
				{ name: "shopping-basket", desc: "购物篮,购买,消费,商城" },
				{ name: "shopping-basket-2", desc: "购物篮,购买,消费,商城" },
				{ name: "shopping-cart", desc: "购物车,购买,消费,商城" },
				{ name: "shopping-cart-2", desc: "购物车,购买,消费,商城" },
				{ name: "vip", desc: "会员" },
				{
					name: "vip-crown",
					desc: "king,queen,皇冠,会员,国王,女王,王后",
				},
				{
					name: "vip-crown-2",
					desc: "king,queen,皇冠,会员,国王,女王,王后",
				},
				{ name: "vip-diamond", desc: "钻石,会员" },
				{ name: "trophy", desc: "奖品,奖杯,金杯" },
				{ name: "exchange", desc: "swap,交换,换算,兑换,交易" },
				{ name: "exchange-box", desc: "swap,交换,换算,兑换,交易" },
				{ name: "exchange-2", desc: "swap,交换,换算,兑换,交易" },
				{ name: "swap", desc: "exchange,交换,换算,兑换,交易" },
				{ name: "swap-box", desc: "exchange,交换,换算,兑换,交易" },
				{
					name: "swap-2",
					desc: "flow direction,exchange,交换,换算,兑换,交易",
				},
				{
					name: "swap-3",
					desc: "flow direction,exchange,交换,换算,兑换,交易",
				},
				{
					name: "exchange-dollar",
					desc: "swap,transfer,交换,换算,兑换,美元,转账,交易",
				},
				{
					name: "exchange-cny",
					desc: "swap,transfer,交换,换算,兑换,人民币,转账,交易",
				},
				{
					name: "exchange-funds",
					desc: "swap,transfer,交换,换算,兑换,基金,股票,转账,交易",
				},
				{ name: "increase-decrease", desc: "计算器" },
				{ name: "percent", desc: "百分之,百分比" },
				{
					name: "copper-coin",
					desc: "currency,payment,铜币,硬币,货币,钱,支付",
				},
				{
					name: "copper-diamond",
					desc: "currency,coins,金币,钻石,货币,钱,支付",
				},
				{
					name: "money-cny-box",
					desc: "currency,payment,货币,钱,支付,人民币",
				},
				{
					name: "money-cny-circle",
					desc: "currency,coins,金币,payment,货币,钱,支付,人民币",
				},
				{
					name: "money-dollar-box",
					desc: "currency,payment,货币,钱,支付,美元",
				},
				{
					name: "money-dollar-circle",
					desc: "currency,coins,金币,payment,cent,penny,货币,钱,支付,美元,美分,便士",
				},
				{
					name: "money-euro-box",
					desc: "currency,payment,货币,钱,支付,欧元",
				},
				{
					name: "money-euro-circle",
					desc: "currency,coins,金币,payment,货币,钱,支付,欧元",
				},
				{
					name: "money-pound-box",
					desc: "currency,payment,货币,钱,支付,英镑",
				},
				{
					name: "money-pound-circle",
					desc: "currency,coins,金币,payment,货币,钱,支付,英镑",
				},
				{
					name: "money-rupee-circle",
					desc: "currency,coins,金币,payment,货币,钱,支付,卢比",
				},
				{ name: "bit-coin", desc: "currency,payment,货币,钱,比特币" },
				{ name: "coin", desc: "金币,硬币" },
				{ name: "cash", desc: "现金,钞票" },
				{ name: "coins", desc: "金币,硬币" },
				{ name: "currency", desc: "cash,payment,货币,钱" },
				{ name: "funds", desc: "foundation,stock,基金,股票" },
				{ name: "funds-box", desc: "foundation,stock,基金,股票" },
				{ name: "red-packet", desc: "红包" },
				{ name: "water-flash", desc: "水电费" },
				{ name: "stock", desc: "股票" },
				{ name: "auction", desc: "hammer,gavel,拍卖,锤子" },
				{ name: "gift", desc: "present,礼物" },
				{ name: "gift-2", desc: "present,礼物" },
				{ name: "hand-coin", desc: "donate,business,捐赠" },
				{
					name: "hand-heart",
					desc: "help,donate,volunteer,welfare,帮助,爱心,捐赠,志愿者,公益",
				},
				{ name: "24-hours", desc: "last,24小时营业" },
				{ name: "nft", desc: "token" },
				{ name: "p2p", desc: "trade,点对点,交易" },
				{
					name: "token-swap",
					desc: "cryptocurrency,数字货币,代币,兑换",
				},
				{ name: "btc", desc: "cryptocurrency,数字货币,bitcoin,比特币" },
				{
					name: "eth",
					desc: "cryptocurrency,数字货币,ethereum,以太坊",
				},
				{ name: "xtz", desc: "cryptocurrency,数字货币,tezos,兔子币" },
				{ name: "bnb", desc: "cryptocurrency,数字货币,binance,币安币" },
				{ name: "xrp", desc: "cryptocurrency,数字货币,ripple,瑞波币" },
				{
					name: "discount-percent",
					desc: "promotion,sale,折扣,促销,打折",
				},
			],
			size: 80,
		},
		{
			name: "食物",
			namee: "Food",
			icons: [
				{ name: "restaurant", desc: "餐厅,饭店" },
				{ name: "restaurant-2", desc: "餐厅,饭店" },
				{ name: "cup", desc: "tea,coffee,杯子,咖啡,茶" },
				{ name: "goblet", desc: "cup,wine glass,高脚杯,酒杯" },
				{ name: "beer", desc: "cup,啤酒杯" },
				{ name: "cake", desc: "anniversary,蛋糕" },
				{ name: "cake-2", desc: "anniversary,蛋糕,生日,蜡烛" },
				{ name: "cake-3", desc: "蛋糕,生日,蜡烛" },
				{ name: "knife", desc: "菜刀" },
				{ name: "knife-blood", desc: "crime,菜刀,犯罪,血,杀人" },
				{ name: "bread", desc: "toast,吐司面包" },
				{ name: "drinks", desc: "coffee,饮料,咖啡" },
				{ name: "drinks-2", desc: "juice,饮料,果汁" },
				{ name: "bowl", desc: "soup,碗,汤" },
			],
			size: 14,
		},
		{
			name: "医药",
			namee: "Health & Medical",
			icons: [
				{ name: "heart", desc: "like,love,favorite,心,喜欢,爱,收藏" },
				{ name: "heart-2", desc: "like,love,favorite,心,喜欢,爱,收藏" },
				{ name: "heart-3", desc: "like,love,favorite,心,喜欢,爱,收藏" },
				{
					name: "heart-add",
					desc: "like,love,favorite,心,喜欢,爱,收藏",
				},
				{
					name: "dislike",
					desc: "like,love,remove favorite,心,不喜欢,取消收藏",
				},
				{ name: "hearts", desc: "romance,爱情,浪漫,心" },
				{ name: "heart-pulse", desc: "heart rate,脉搏,心率" },
				{ name: "pulse", desc: "wave,heart rate,脉搏,心率,波" },
				{ name: "empathize", desc: "care,heart,同理心,关爱,心" },
				{ name: "nurse", desc: "doctors,医生,护士" },
				{ name: "dossier", desc: "病例" },
				{ name: "health-book", desc: "健康手册,医疗手册" },
				{ name: "first-aid-kit", desc: "case,急救箱" },
				{ name: "capsule", desc: "medicine, 胶囊,药" },
				{ name: "medicine-bottle", desc: "药瓶" },
				{
					name: "flask",
					desc: "testing,experimental,experiment,烧瓶,实验,试验",
				},
				{
					name: "test-tube",
					desc: "testing,experimental,experiment,试管,实验,试验",
				},
				{
					name: "microscope",
					desc: "testing,experimental,experiment,显微镜,实验,试验",
				},
				{ name: "hand-sanitizer", desc: "alcohol,酒精消毒洗手液" },
				{ name: "mental-health", desc: "心理健康" },
				{ name: "psychotherapy", desc: "心理治疗" },
				{ name: "stethoscope", desc: "听诊器" },
				{ name: "syringe", desc: "注射器" },
				{ name: "thermometer", desc: "体温计" },
				{ name: "infrared-thermometer", desc: "红外线体温计,体温枪" },
				{ name: "surgical-mask", desc: "外科医用口罩" },
				{ name: "virus", desc: "病毒" },
				{ name: "lungs", desc: "肺部" },
				{ name: "rest-time", desc: "close,休息时间,打烊" },
				{ name: "zzz", desc: "睡觉" },
				{ name: "brain", desc: "think,大脑,思考" },
			],
			size: 31,
		},
		{
			name: "商标",
			namee: "Logos",
			icons: [
				{ name: "alipay", desc: "zhifubao,支付宝" },
				{ name: "amazon", desc: "亚马逊" },
				{ name: "android", desc: "applications,安卓,应用" },
				{ name: "angularjs", desc: "angular,programing framework" },
				{ name: "app-store", desc: "applications,苹果应用商店" },
				{ name: "apple", desc: "苹果" },
				{ name: "baidu", desc: "du,claw,百度,爪" },
				{
					name: "bard",
					desc: "google,ai,magic,star,shining,sparkling,twinkle,人工智能,魔法,星星,闪烁",
				},
				{ name: "behance", desc: "behance" },
				{ name: "bilibili", desc: "哔哩哔哩" },
				{ name: "blender", desc: "3d" },
				{ name: "blogger", desc: "博客" },
				{ name: "bootstrap", desc: "bootstrap" },
				{ name: "centos", desc: "linux,system,系统" },
				{ name: "chrome", desc: "谷歌浏览器" },
				{ name: "codepen", desc: "代码笔" },
				{ name: "copilot", desc: "github,飞行员" },
				{ name: "coreos", desc: "linux,system,系统" },
				{ name: "dingding", desc: "钉钉" },
				{ name: "discord", desc: "game,chat" },
				{ name: "disqus", desc: "comments" },
				{ name: "douban", desc: "豆瓣" },
				{ name: "dribbble", desc: "追波" },
				{ name: "drive", desc: "google drive,谷歌云端硬盘" },
				{ name: "dropbox", desc: "多宝箱" },
				{ name: "edge", desc: "microsoft edge,edge浏览器" },
				{ name: "edge-new", desc: "microsoft-edge,浏览器" },
				{ name: "evernote", desc: "印象笔记" },
				{ name: "facebook", desc: "脸书" },
				{ name: "facebook-circle", desc: "脸书" },
				{ name: "facebook-box", desc: "脸书" },
				{ name: "finder", desc: "macintosh,仿达" },
				{ name: "firefox", desc: "火狐浏览器" },
				{ name: "flickr", desc: "flickr" },
				{ name: "flutter", desc: "flutter" },
				{ name: "gatsby", desc: "gatsby" },
				{ name: "github", desc: "github" },
				{ name: "gitlab", desc: "gitlab" },
				{ name: "google", desc: "google,谷歌" },
				{ name: "google-play", desc: "applications,谷歌应用商店" },
				{ name: "honor-of-kings", desc: "game,王者荣耀" },
				{ name: "ie", desc: "internet explorer,浏览器" },
				{ name: "instagram", desc: "instagram,照片墙" },
				{ name: "invision", desc: "invision" },
				{ name: "kakao-talk", desc: "kakao talk,chat" },
				{ name: "line", desc: "line,连我" },
				{ name: "linkedin", desc: "linkedin,领英" },
				{ name: "linkedin-box", desc: "linkedin,领英" },
				{ name: "kick", desc: "kick" },
				{ name: "microsoft-loop", desc: "Doc,笔记" },
				{ name: "mastercard", desc: "bank card,银行卡" },
				{ name: "mastodon", desc: "mastodon,长毛象" },
				{ name: "medium", desc: "medium,媒体" },
				{ name: "messenger", desc: "facebook,脸书,信使" },
				{ name: "meta", desc: "meta,元宇宙" },
				{ name: "microsoft", desc: "windows,窗户,微软" },
				{ name: "mini-program", desc: "微信小程序" },
				{
					name: "netease-cloud-music",
					desc: "netease cloud music,网易云音乐",
				},
				{ name: "netflix", desc: "网飞" },
				{ name: "notion", desc: "notes,doc,笔记,文档" },
				{ name: "npmjs", desc: "npm,nodejs" },
				{ name: "openai", desc: "人工智能" },
				{ name: "openbase", desc: "openbase" },
				{ name: "open-source", desc: "opensource,开源" },
				{ name: "opera", desc: "欧朋浏览器" },
				{ name: "patreon", desc: "donate,money,捐赠,打赏" },
				{ name: "paypal", desc: "贝宝" },
				{ name: "pinterest", desc: "拼趣" },
				{ name: "pixelfed", desc: "photography,pixelfed" },
				{ name: "playstation", desc: "ps" },
				{ name: "product-hunt", desc: "product hunt" },
				{ name: "qq", desc: "penguin,tencent,腾讯,企鹅" },
				{
					name: "reactjs",
					desc: "react,programing framework,facebook",
				},
				{ name: "reddit", desc: "reddit" },
				{ name: "remixicon", desc: "remix,图标" },
				{ name: "remix-run", desc: "remix" },
				{ name: "safari", desc: "safari浏览器" },
				{ name: "skype", desc: "skype" },
				{ name: "slack", desc: "slack" },
				{ name: "snapchat", desc: "ghost,色拉布,幽灵" },
				{ name: "soundcloud", desc: "声云" },
				{ name: "spectrum", desc: "spectrum" },
				{ name: "spotify", desc: "music,音乐" },
				{ name: "stack-overflow", desc: "stack overflow" },
				{ name: "stackshare", desc: "share,分享,技术栈" },
				{ name: "steam", desc: "game,store" },
				{ name: "supabase", desc: "supabase" },
				{ name: "svelte", desc: "svelte" },
				{ name: "switch", desc: "nintendo,任天堂" },
				{ name: "taobao", desc: "taobao,淘宝" },
				{ name: "telegram", desc: "telegram" },
				{ name: "threads", desc: "threads" },
				{ name: "tiktok", desc: "tiktok,抖音" },
				{ name: "trello", desc: "trello" },
				{ name: "tumblr", desc: "tumblr" },
				{ name: "twitch", desc: "twitch" },
				{ name: "twitter", desc: "twitter,推特" },
				{ name: "twitter-x", desc: "twitter,推特" },
				{ name: "ubuntu", desc: "linux,system,系统" },
				{ name: "unsplash", desc: "photos" },
				{ name: "vimeo", desc: "vimeo,视频" },
				{ name: "vk", desc: "vk" },
				{ name: "visa", desc: "bank card,银行卡" },
				{ name: "vuejs", desc: "vue,programing framework" },
				{ name: "wechat", desc: "wechat,微信" },
				{ name: "wechat-2", desc: "微信" },
				{ name: "wechat-channels", desc: "微信视频号" },
				{ name: "wechat-pay", desc: "微信支付" },
				{ name: "weibo", desc: "新浪微博" },
				{ name: "whatsapp", desc: "瓦次艾普" },
				{ name: "windows", desc: "microsoft,窗户,微软" },
				{ name: "wordpress", desc: "blog,博客" },
				{ name: "xbox", desc: "xbox" },
				{ name: "xing", desc: "xing" },
				{ name: "youtube", desc: "youtube,优兔,油管" },
				{ name: "yuque", desc: "yuque,语雀" },
				{ name: "zcool", desc: "zcool,站酷" },
				{ name: "zhihu", desc: "zhihu,知乎" },
			],
			size: 118,
		},
		{
			name: "地图",
			namee: "Map",
			icons: [
				{
					name: "map-pin",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
				},
				{
					name: "map-pin-2",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
				},
				{
					name: "map-pin-3",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
				},
				{
					name: "map-pin-4",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
				},
				{
					name: "map-pin-5",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
				},
				{
					name: "map-pin-add",
					desc: "location,navigation,地图,坐标,定位,导航,位置,新增,添加",
				},
				{
					name: "map-pin-range",
					desc: "location,navigation,地图,坐标,定位,导航,位置,范围",
				},
				{
					name: "map-pin-time",
					desc: "location,navigation,地图,坐标,定位,导航,位置,时间",
				},
				{
					name: "map-pin-user",
					desc: "location,navigation,地图,坐标,定位,导航,位置,用户",
				},
				{ name: "pin-distance", desc: "坐标,距离" },
				{ name: "pushpin", desc: "图钉" },
				{ name: "unpin", desc: "图钉,取消固定" },
				{ name: "pushpin-2", desc: "图钉" },
				{
					name: "compass",
					desc: "navigation,safari,direction,discover,指南针,导航,方向,发现,探索",
				},
				{
					name: "compass-2",
					desc: "navigation,direction,discover,指南针,导航,方向,发现,探索",
				},
				{
					name: "compass-3",
					desc: "navigation,safari,direction,discover,指南针,导航,方向,发现,探索",
				},
				{
					name: "compass-4",
					desc: "navigation,direction,discover,指南针,导航,方向,发现,探索",
				},
				{
					name: "compass-discover",
					desc: "navigation,direction,指南针,导航,方向,发现,探索",
				},
				{ name: "anchor", desc: "锚" },
				{ name: "china-railway", desc: "中铁,铁路,火车" },
				{ name: "space-ship", desc: "太空飞船" },
				{ name: "rocket", desc: "火箭" },
				{ name: "rocket-2", desc: "space ship,火箭,太空飞船" },
				{ name: "map", desc: "navigation,travel,地图,导航,旅行" },
				{
					name: "map-2",
					desc: "location,navigation,travel,地图,定位,导航,旅行",
				},
				{
					name: "treasure-map",
					desc: "thriller,adventure,地图,藏宝图",
				},
				{ name: "road-map", desc: "navigation,travel,地图,导航,旅行" },
				{
					name: "earth",
					desc: "global,union,world,language,地球,全球,联合,世界,语言",
				},
				{ name: "time-zone", desc: "global,地球,时区,时间" },
				{ name: "globe", desc: "earth,地球仪" },
				{ name: "planet", desc: "space,discover,星球,宇宙,探索,发现" },
				{ name: "parking", desc: "停车场" },
				{ name: "parking-box", desc: "停车场" },
				{ name: "route", desc: "path,路线" },
				{ name: "guide", desc: "path,指引,路线" },
				{ name: "gas-station", desc: "加气站,加油站" },
				{ name: "charging-pile", desc: "充电桩" },
				{ name: "charging-pile-2", desc: "充电桩" },
				{ name: "car", desc: "汽车" },
				{ name: "car-washing", desc: "汽车,洗车" },
				{ name: "roadster", desc: "car,汽车,跑车" },
				{ name: "taxi", desc: "car,出租车,汽车" },
				{ name: "taxi-wifi", desc: "car,出租车,汽车" },
				{ name: "police-car", desc: "汽车,警车" },
				{ name: "bus", desc: "大巴,巴士" },
				{ name: "bus-2", desc: "大巴,巴士" },
				{ name: "bus-wifi", desc: "大巴,巴士" },
				{ name: "truck", desc: "van,delivery,卡车,货车,运输" },
				{ name: "train", desc: "火车" },
				{ name: "train-wifi", desc: "火车" },
				{ name: "subway", desc: "地铁" },
				{ name: "subway-wifi", desc: "地铁" },
				{
					name: "flight-takeoff",
					desc: "airplane,plane,origin,起飞,出发,始发,起点,飞机",
				},
				{
					name: "flight-land",
					desc: "airplane,plane,destination,着陆,到达,抵达,终点,飞机",
				},
				{ name: "plane", desc: "fight,飞机,航班" },
				{ name: "sailboat", desc: "帆船" },
				{ name: "ship", desc: "轮船,航海,海运" },
				{ name: "ship-2", desc: "轮船" },
				{ name: "bike", desc: "自行车" },
				{ name: "e-bike", desc: "take out,takeaway,电动车,外卖" },
				{ name: "e-bike-2", desc: "take out,takeaway,电动车,外卖" },
				{ name: "takeaway", desc: "take out,takeaway,电动车,外卖" },
				{ name: "motorbike", desc: "摩托车" },
				{ name: "caravan", desc: "房车" },
				{ name: "walk", desc: "步行" },
				{ name: "run", desc: "奔跑,跑步" },
				{ name: "riding", desc: "bike,骑行,自行车" },
				{ name: "barricade", desc: "路障" },
				{ name: "footprint", desc: "脚印,足迹" },
				{ name: "traffic-light", desc: "交通,信号灯" },
				{
					name: "signal-tower",
					desc: "base station,antenna,信号塔,基站,天线",
				},
				{ name: "hotel-bed", desc: "酒店,床" },
				{ name: "navigation", desc: "gps,导航" },
				{ name: "oil", desc: "汽油,机油" },
				{ name: "direction", desc: "right,方向,右转" },
				{ name: "steering", desc: "drive,方向盘,驾车" },
				{ name: "steering-2", desc: "drive,方向盘,驾车" },
				{ name: "lifebuoy", desc: "life ring,救生圈" },
				{ name: "passport", desc: "passports,护照" },
				{ name: "suitcase", desc: "travel,旅行,行李箱" },
				{ name: "suitcase-2", desc: "travel,旅行,行李箱,拉杆箱" },
				{
					name: "suitcase-3",
					desc: "travel,旅行,boarding case,行李箱,拉杆箱,登机箱",
				},
				{
					name: "luggage-deposit",
					desc: "consignment,行李箱,行李寄存,托运",
				},
				{ name: "luggage-cart", desc: "行李车" },
				{ name: "signpost", desc: "mailestone,路标,路牌,里程碑" },
			],
			size: 85,
		},
		{
			name: "媒体",
			namee: "Media",
			icons: [
				{ name: "image", desc: "picture,photo,图片,照片" },
				{ name: "image-circle", desc: "picture,photo,图片,照片" },
				{ name: "image-2", desc: "picture,photo,图片,照片" },
				{ name: "image-add", desc: "picture,photo,图片,照片,添加" },
				{ name: "image-edit", desc: "picture,photo,图片,照片,编辑" },
				{ name: "landscape", desc: "picture,image,photo,图片,照片" },
				{ name: "gallery", desc: "picture,image,图片,相册" },
				{
					name: "gallery-upload",
					desc: "picture,image,图片,相册,上传",
				},
				{ name: "video", desc: "视频" },
				{ name: "movie", desc: "film,video,电影,硬盘,视频" },
				{ name: "movie-2", desc: "film,video,电影,硬盘,视频" },
				{ name: "film", desc: "movie,video,影片,电影,视频" },
				{ name: "clapperboard", desc: "movie,film,场记板,电影" },
				{ name: "vidicon", desc: "video,camera,摄像机,摄影机,视频" },
				{ name: "vidicon-2", desc: "camera,摄像机,摄影机" },
				{ name: "live", desc: "video,camera,摄像机,摄影机,视频,直播" },
				{ name: "video-add", desc: "camera,摄像机,摄影机,视频,添加" },
				{
					name: "video-upload",
					desc: "camera,摄像机,摄影机,视频,上传",
				},
				{
					name: "video-download",
					desc: "camera,摄像机,摄影机,视频,下载",
				},
				{ name: "dv", desc: "vidicon,camera,摄像机,摄影机" },
				{ name: "camera", desc: "photo,照相机,拍照,照片" },
				{
					name: "camera-off",
					desc: "photo,slash,照相机,拍照,照片,禁止,关闭",
				},
				{ name: "camera-2", desc: "photo,照相机,拍照,照片" },
				{ name: "camera-3", desc: "photo,照相机,拍照,照片" },
				{
					name: "camera-lens",
					desc: "aperture,photo,照相机,拍照,照片,朋友圈",
				},
				{ name: "camera-switch", desc: "照相机,拍照,翻转" },
				{ name: "polaroid", desc: "camera,相机,宝丽来" },
				{ name: "polaroid-2", desc: "camera,相机,宝丽来" },
				{ name: "phone-camera", desc: "手机相机,手机摄像头" },
				{ name: "webcam", desc: "摄像头" },
				{ name: "mv", desc: "music video,音乐" },
				{ name: "music", desc: "音乐" },
				{ name: "music-2", desc: "音乐" },
				{ name: "disc", desc: "music,album,音乐,唱片" },
				{ name: "album", desc: "music,唱片,音乐" },
				{ name: "dvd", desc: "cd,dvd,record,光盘,刻录" },
				{ name: "headphone", desc: "music,headset,耳机,音乐" },
				{ name: "radio", desc: "收音机,电台" },
				{ name: "radio-2", desc: "收音机,电台" },
				{ name: "tape", desc: "录音,磁带" },
				{ name: "mic", desc: "record,voice,话筒,语音,录音,声音" },
				{ name: "mic-2", desc: "record,voice,话筒,语音,录音,声音" },
				{
					name: "mic-off",
					desc: "record,voice,slash,关闭话筒,关闭语音,录音,关闭声音,静音,禁止",
				},
				{
					name: "volume-down",
					desc: "trumpet,sound,speaker,音量低,喇叭,声音,扬声器",
				},
				{
					name: "volume-mute",
					desc: "trumpet,sound,off,音量低,喇叭,声音,静音",
				},
				{
					name: "volume-up",
					desc: "trumpet,sound,speaker,音量高,喇叭,声音,扬声器",
				},
				{
					name: "volume-vibrate",
					desc: "trumpet,sound,speaker,喇叭,声音,扬声器,震动模式",
				},
				{
					name: "volume-off-vibrate",
					desc: "trumpet,sound,speaker,静音,喇叭,声音,扬声器,静音模式",
				},
				{ name: "speaker", desc: "音响" },
				{ name: "speaker-2", desc: "音响" },
				{ name: "speaker-3", desc: "音响" },
				{ name: "surround-sound", desc: "环绕立体声" },
				{ name: "broadcast", desc: "广播" },
				{ name: "notification", desc: "bell,alarm,通知,铃铛,提醒" },
				{ name: "notification-2", desc: "bell,alarm,通知,铃铛,提醒" },
				{ name: "notification-3", desc: "bell,alarm,通知,铃铛,提醒" },
				{ name: "notification-4", desc: "bell,alarm,通知,铃铛,提醒" },
				{
					name: "notification-off",
					desc: "bell,alarm,silent,slash,通知,铃铛,提醒,免打扰,静音,关闭,禁止",
				},
				{ name: "play-circle", desc: "start,播放,开始" },
				{ name: "pause-circle", desc: "暂停" },
				{ name: "record-circle", desc: "录音" },
				{ name: "stop-circle", desc: "停止" },
				{ name: "eject", desc: "推出" },
				{ name: "play", desc: "start,播放,开始" },
				{ name: "pause", desc: "暂停" },
				{ name: "stop", desc: "停止" },
				{ name: "rewind", desc: "fast,快退" },
				{ name: "speed", desc: "fast,快进" },
				{ name: "skip-back", desc: "上一曲" },
				{ name: "skip-forward", desc: "下一曲" },
				{ name: "play-mini", desc: "播放" },
				{ name: "pause-mini", desc: "暂停" },
				{ name: "stop-mini", desc: "停止" },
				{ name: "rewind-mini", desc: "fast,快退" },
				{ name: "speed-mini", desc: "fast,快进" },
				{ name: "skip-back-mini", desc: "上一曲" },
				{ name: "skip-forward-mini", desc: "下一曲" },
				{ name: "replay-5", desc: "playback,重播,回放" },
				{ name: "forward-5", desc: "skip,快进,快放,跳过" },
				{ name: "replay-10", desc: "playback,重播,回放" },
				{ name: "forward-10", desc: "skip,快进,快放,跳过" },
				{ name: "replay-15", desc: "playback,重播,回放" },
				{ name: "forward-15", desc: "skip,快进,快放,跳过" },
				{ name: "replay-30", desc: "playback,重播,回放" },
				{ name: "forward-30", desc: "skip,快进,快放,跳过" },
				{ name: "memories", desc: "回忆" },
				{ name: "repeat", desc: "swap,交换,循环播放" },
				{ name: "repeat-2", desc: "swap,交换,循环播放" },
				{ name: "repeat-one", desc: "单曲循环" },
				{ name: "order-play", desc: "顺序播放" },
				{ name: "shuffle", desc: "随机播放" },
				{ name: "play-list", desc: "播放列表" },
				{ name: "play-list-2", desc: "播放列表" },
				{ name: "play-list-add", desc: "列表,添加" },
				{ name: "fullscreen", desc: "maximize,全屏,最大化" },
				{ name: "fullscreen-exit", desc: "minimize,退出全屏,最小化" },
				{
					name: "equalizer",
					desc: "sliders,controls,settings,filter,均衡器,控制器,设置,筛选",
				},
				{
					name: "equalizer-2",
					desc: "sliders,controls,settings,filter,均衡器,控制器,设置,筛选",
				},
				{
					name: "equalizer-3",
					desc: "sliders,controls,settings,filter,均衡器,控制器,设置,筛选",
				},
				{
					name: "sound-module",
					desc: "sliders,controls,settings,filter,均衡器,控制器,设置,筛选",
				},
				{ name: "rhythm", desc: "节奏,韵律" },
				{ name: "voiceprint", desc: "声纹" },
				{ name: "speed-up", desc: "dashboard,快,加速,仪表盘" },
				{ name: "slow-down", desc: "dashboard,慢,减速,仪表盘" },
				{ name: "hq", desc: "high quality,高质量,高品质" },
				{ name: "hd", desc: "high definition,高清晰度" },
				{
					name: "4k",
					desc: "high definition,high quality,高清晰度,高品质,超清",
				},
				{ name: "closed-captioning", desc: "隐藏字幕" },
				{ name: "aspect-ratio", desc: "宽高比,比例" },
				{ name: "picture-in-picture", desc: "画中画,小窗" },
				{ name: "picture-in-picture-2", desc: "画中画,小窗" },
				{
					name: "picture-in-picture-exit",
					desc: "退出画中画,退出小窗",
				},
			],
			size: 112,
		},
		{
			name: "系统",
			namee: "System",
			icons: [
				{ name: "apps", desc: "应用" },
				{ name: "apps-2", desc: "应用" },
				{ name: "function", desc: "layout,功能,应用,卡片布局" },
				{ name: "dashboard", desc: "仪表盘" },
				{ name: "menu", desc: "navigation,hamburger,导航,菜单,汉堡包" },
				{
					name: "menu-2",
					desc: "navigation,hamburger,导航,菜单,汉堡包",
				},
				{
					name: "menu-3",
					desc: "navigation,hamburger,导航,菜单,汉堡包",
				},
				{
					name: "menu-4",
					desc: "navigation,hamburger,导航,菜单,汉堡包",
				},
				{
					name: "menu-5",
					desc: "navigation,hamburger,导航,菜单,汉堡包",
				},
				{
					name: "menu-add",
					desc: "navigation,hamburger,导航,菜单,汉堡包,添加",
				},
				{
					name: "menu-fold",
					desc: "navigation,hamburger,导航,菜单,汉堡包,收起,展开",
				},
				{
					name: "menu-unfold",
					desc: "expend,navigation,hamburger,导航,菜单,汉堡包,收起,展开",
				},
				{ name: "menu-search", desc: "category,菜单,搜索" },
				{ name: "more", desc: "ellipsis,更多,省略" },
				{ name: "more-2", desc: "ellipsis,更多,省略" },
				{ name: "star", desc: "favorite,like,mark,星星,星标,喜欢" },
				{
					name: "star-s",
					desc: "favorite,like,mark,星星,星标,喜欢,半星",
				},
				{
					name: "star-half",
					desc: "favorite,like,mark,星星,星标,喜欢",
				},
				{
					name: "star-half-s",
					desc: "favorite,like,mark,星星,星标,喜欢,半星",
				},
				{
					name: "settings",
					desc: "edit,gear,preferences,偏好设置,编辑,齿轮",
				},
				{
					name: "settings-2",
					desc: "edit,gear,preferences,偏好设置,编辑,齿轮",
				},
				{
					name: "settings-3",
					desc: "edit,gear,preferences,偏好设置,编辑,齿轮",
				},
				{
					name: "settings-4",
					desc: "edit,gear,preferences,偏好设置,编辑,齿轮",
				},
				{
					name: "settings-5",
					desc: "edit,gear,preferences,偏好设置,编辑,齿轮",
				},
				{
					name: "settings-6",
					desc: "edit,gear,preferences,偏好设置,编辑,齿轮",
				},
				{ name: "list-settings", desc: "列表,设置" },
				{ name: "forbid", desc: "prohibited,slash,ban,禁止,禁用" },
				{ name: "forbid-2", desc: "prohibited,slash,ban,禁止,禁用" },
				{ name: "prohibited", desc: "forbid,lash,ban,禁止,禁用" },
				{ name: "information", desc: "i,信息" },
				{ name: "information-2", desc: "i,信息" },
				{
					name: "error-warning",
					desc: "!,alert,important,alert,exclamation,警告,错误",
				},
				{ name: "question", desc: "help,问号,帮助" },
				{ name: "alert", desc: "提醒,警告" },
				{ name: "spam", desc: "alert,垃圾邮件,警告" },
				{ name: "spam-2", desc: "block,alert,垃圾邮件,警告,拦截" },
				{ name: "spam-3", desc: "block,alert,垃圾邮件,警告,拦截" },
				{ name: "checkbox-blank", desc: "复选框,空" },
				{ name: "checkbox", desc: "复选框" },
				{ name: "checkbox-indeterminate", desc: "复选框" },
				{ name: "add-box", desc: "plus,new,复选框,添加,加号,新增" },
				{ name: "checkbox-blank-circle", desc: "复选框,空" },
				{ name: "checkbox-circle", desc: "复选框" },
				{ name: "indeterminate-circle", desc: "slash,ban,复选框,禁" },
				{ name: "add-circle", desc: "plus,new,复选框,添加,加号,新增" },
				{
					name: "close-circle",
					desc: "cancel,remove,delete,empty,x,关闭,取消,移除,删除,清空",
				},
				{ name: "radio-button", desc: "单选框" },
				{ name: "checkbox-multiple-blank", desc: "复选框,空" },
				{ name: "checkbox-multiple", desc: "复选框,空" },
				{ name: "check", desc: "对勾" },
				{
					name: "check-double",
					desc: "read,done,double-tick,双对勾,已读",
				},
				{
					name: "close",
					desc: "cancel,remove,delete,empty,x,关闭,取消,移除,删除,清空",
				},
				{ name: "add", desc: "plus,new,添加,新增,加号" },
				{ name: "subtract", desc: "minus,减" },
				{ name: "divide", desc: "除以" },
				{ name: "equal", desc: "sum,result,等于" },
				{ name: "download", desc: "receive,下载,接收" },
				{ name: "upload", desc: "send,上传,发送" },
				{ name: "download-2", desc: "下载" },
				{ name: "upload-2", desc: "上传" },
				{ name: "import", desc: "导入" },
				{ name: "export", desc: "导出" },
				{ name: "download-cloud", desc: "下载,云" },
				{ name: "upload-cloud", desc: "上传,云" },
				{ name: "download-cloud-2", desc: "下载,云" },
				{ name: "upload-cloud-2", desc: "上传,云" },
				{ name: "login-box", desc: "sign in,登录" },
				{ name: "logout-box", desc: "sign out,登出,注销" },
				{ name: "logout-box-r", desc: "sign out,登出,注销" },
				{ name: "login-circle", desc: "sign in,登录" },
				{ name: "logout-circle", desc: "sign out,登出,注销" },
				{ name: "logout-circle-r", desc: "sign out,登出,注销" },
				{ name: "shield", desc: "safety,protect,盾牌,卫士,安全,防御" },
				{
					name: "shield-cross",
					desc: "safety,protect,盾牌,卫士,安全,防御,闪电",
				},
				{
					name: "shield-flash",
					desc: "safety,protect,盾牌,卫士,安全,防御",
				},
				{
					name: "shield-star",
					desc: "police badge,safety,protect,盾牌,卫士,安全,防御,星星,警徽",
				},
				{
					name: "shield-user",
					desc: "safety,protect,user protected,guarantor,盾牌,卫士,安全,防御,用户",
				},
				{
					name: "shield-keyhole",
					desc: "safety,protect,guarantor,盾牌,卫士,安全,防御,钥匙孔",
				},
				{
					name: "shield-check",
					desc: "safety,protect,盾牌,卫士,安全,防御",
				},
				{ name: "delete-back", desc: "backspace,删除,退格" },
				{ name: "delete-back-2", desc: "backspace,删除,退格" },
				{
					name: "delete-bin",
					desc: "trash,remove,ash-bin,garbage,dustbin,uninstall,卸载,删除,垃圾桶",
				},
				{
					name: "delete-bin-2",
					desc: "trash,remove,ash-bin,garbage,dustbin,uninstall,卸载,删除,垃圾桶",
				},
				{
					name: "delete-bin-3",
					desc: "trash,remove,ash-bin,garbage,dustbin,uninstall,卸载,删除,垃圾桶",
				},
				{
					name: "delete-bin-4",
					desc: "trash,remove,ash-bin,garbage,dustbin,uninstall,卸载,删除,垃圾桶",
				},
				{
					name: "delete-bin-5",
					desc: "trash,remove,ash-bin,garbage,dustbin,uninstall,卸载,删除,垃圾桶",
				},
				{
					name: "delete-bin-6",
					desc: "trash,remove,ash-bin,garbage,dustbin,uninstall,卸载,删除,垃圾桶",
				},
				{
					name: "delete-bin-7",
					desc: "trash,remove,ash-bin,garbage,dustbin,uninstall,卸载,删除,垃圾桶",
				},
				{ name: "lock", desc: "security,password,锁子,安全,密码" },
				{ name: "lock-2", desc: "security,password,锁子,安全,密码" },
				{ name: "lock-password", desc: "security,锁子,安全,密码" },
				{
					name: "lock-unlock",
					desc: "security,password,锁子,安全,密码",
				},
				{
					name: "lock-star",
					desc: "security,premium,锁子,安全,密码,会员,高级",
				},
				{ name: "eye", desc: "watch,view,眼睛,查看" },
				{ name: "eye-off", desc: "slash,眼睛,不可见,关闭,禁止" },
				{ name: "eye-2", desc: "watch,view,眼睛,查看" },
				{ name: "eye-close", desc: "x,闭眼" },
				{ name: "search", desc: "搜索,放大镜" },
				{ name: "search-2", desc: "搜索,放大镜" },
				{ name: "search-eye", desc: "搜索,放大镜,眼睛" },
				{ name: "zoom-in", desc: "放大,放大镜" },
				{ name: "zoom-out", desc: "缩小,放大镜" },
				{ name: "find-replace", desc: "查找,搜索,替换" },
				{ name: "share", desc: "sharing,分享,转发" },
				{ name: "share-2", desc: "sharing,分享,转发" },
				{ name: "share-box", desc: "sharing,分享,转发" },
				{ name: "share-circle", desc: "sharing,分享,转发" },
				{ name: "share-forward", desc: "sharing,分享,转发" },
				{ name: "share-forward-2", desc: "sharing,分享,转发" },
				{ name: "share-forward-box", desc: "sharing,分享,转发" },
				{ name: "external-link", desc: "外链" },
				{ name: "side-bar", desc: "侧边栏" },
				{ name: "sidebar-unfold", desc: "expend,展开侧边栏" },
				{ name: "sidebar-fold", desc: "收起侧边栏" },
				{ name: "time", desc: "clock,时间,时钟,钟表" },
				{ name: "timer", desc: "chronograph,stopwatch,秒表,计时器" },
				{ name: "timer-2", desc: "chronograph,stopwatch,秒表,计时器" },
				{
					name: "timer-flash",
					desc: "chronograph,stopwatch,秒表,计时器,闪电",
				},
				{ name: "alarm", desc: "闹钟" },
				{
					name: "history",
					desc: "record,recent,time machine,历史记录,最近",
				},
				{
					name: "hourglass-2",
					desc: "time,history,recent,duration,沙漏,时间,历史记录,最近",
				},
				{
					name: "hourglass",
					desc: "time,history,recent,duration,沙漏,时间,历史记录,最近",
				},
				{ name: "thumb-up", desc: "like,good,喜欢,好" },
				{ name: "thumb-down", desc: "dislike,bad,不喜欢,不好" },
				{
					name: "alarm-warning",
					desc: "alert,report,police light,告警,举报,警灯",
				},
				{ name: "notification-badge", desc: "red dot,通知,小红点" },
				{ name: "toggle", desc: "switch,开关,触发器" },
				{ name: "filter", desc: "filtration,筛选,过滤" },
				{ name: "filter-2", desc: "filtration,筛选,过滤" },
				{ name: "filter-3", desc: "filtration,筛选,过滤" },
				{
					name: "filter-off",
					desc: "filtration,clear-filter,筛选,过滤",
				},
				{
					name: "loader",
					desc: "loader,spinner,ajax,waiting,delay,加载中,载入中,正在加载",
				},
				{
					name: "loader-2",
					desc: "loader,spinner,ajax,waiting,delay,加载中,载入中,正在加载",
				},
				{
					name: "loader-3",
					desc: "loader,spinner,ajax,waiting,delay,加载中,载入中,正在加载",
				},
				{
					name: "loader-4",
					desc: "loader,spinner,ajax,waiting,delay,加载中,载入中,正在加载",
				},
				{
					name: "loader-5",
					desc: "loader,spinner,ajax,waiting,delay,加载中,载入中,正在加载",
				},
				{
					name: "refresh",
					desc: "reload,repeat,replace,reset,restart,synchronization,spinner,loader,update,刷新,重新加载,重复,重置,替换,重启,同步,更新",
				},
				{
					name: "loop-left",
					desc: "reload,repeat,replace,reset,restart,synchronization,spinner,loader,update,刷新,重新加载,重复,重置,替换,重启,同步,更新",
				},
				{
					name: "loop-right",
					desc: "reload,repeat,replace,reset,restart,synchronization,spinner,loader,update,刷新,重新加载,重复,重置,替换,重启,同步,更新",
				},
				{ name: "progress-1", desc: "persent,进度,百分比" },
				{ name: "progress-2", desc: "persent,进度,百分比" },
				{ name: "progress-3", desc: "persent,进度,百分比" },
				{ name: "progress-4", desc: "persent,进度,百分比" },
				{ name: "progress-5", desc: "persent,进度,百分比" },
				{ name: "progress-6", desc: "persent,进度,百分比" },
				{ name: "progress-7", desc: "persent,进度,百分比" },
				{ name: "progress-8", desc: "persent,进度,百分比" },
			],
			size: 147,
		},
		{
			name: "表情",
			namee: "User & Faces",
			icons: [
				{ name: "user", desc: "用户,person,people" },
				{ name: "user-2", desc: "用户,person,people" },
				{ name: "user-3", desc: "用户,person,people" },
				{ name: "user-4", desc: "用户,person,people" },
				{ name: "user-5", desc: "用户,person,people" },
				{ name: "user-6", desc: "用户,person,people" },
				{ name: "user-smile", desc: "用户,微笑,person,people" },
				{ name: "account-box", desc: "用户,账户,person,people" },
				{ name: "account-circle", desc: "用户,账户,person,people" },
				{ name: "account-pin-box", desc: "用户,账户,person,people" },
				{ name: "account-pin-circle", desc: "用户,账户,person,people" },
				{ name: "user-add", desc: "用户,添加,新增,person,people" },
				{ name: "user-follow", desc: "关注,person,people" },
				{
					name: "user-unfollow",
					desc: "person,people,rejected,用户,取消关注,拒绝,错误",
				},
				{
					name: "user-shared",
					desc: "transfer,用户,我分享的,发送,person,people",
				},
				{
					name: "user-shared-2",
					desc: "transfer,用户,我分享的,发送,person,people",
				},
				{
					name: "user-received",
					desc: "用户,我接收的,收取,person,people",
				},
				{
					name: "user-received-2",
					desc: "用户,我接收的,收取,person,people",
				},
				{ name: "user-location", desc: "用户,定位,person,people" },
				{ name: "user-search", desc: "用户,查找,person,people" },
				{
					name: "user-settings",
					desc: "admin,用户,设置,管理员,person,people",
				},
				{ name: "user-star", desc: "用户,关注,person,people" },
				{ name: "user-heart", desc: "用户,关注,person,people" },
				{ name: "admin", desc: "admin,用户,管理员,person,people" },
				{ name: "user-forbid", desc: "terminated,禁止,终止" },
				{ name: "contacts", desc: "联系人" },
				{ name: "group", desc: "team,团队,群组,person,people" },
				{ name: "group-2", desc: "team,团队,群组,person,people" },
				{ name: "team", desc: "团队,小组,群主,person,people" },
				{ name: "user-voice", desc: "用户,录音,演讲" },
				{ name: "emotion", desc: "表情,笑脸" },
				{ name: "emotion-2", desc: "表情,笑脸" },
				{ name: "emotion-happy", desc: "表情,开心" },
				{ name: "emotion-normal", desc: "表情,一般" },
				{ name: "emotion-unhappy", desc: "表情,不开心" },
				{
					name: "emotion-laugh",
					desc: "comedy,happy,表情,大笑,笑脸,开心,喜剧",
				},
				{ name: "emotion-sad", desc: "drama,tears,悲剧,哭泣,泪" },
				{ name: "skull", desc: "ghost,骷髅,鬼怪" },
				{
					name: "skull-2",
					desc: "ghost,horror,thriller,骷髅,鬼怪,恐惧,恐怖",
				},
				{ name: "men", desc: "gender,man,male,男人,男性" },
				{ name: "women", desc: "gender,woman,female,女人,女性" },
				{ name: "travesti", desc: "女人,女性" },
				{ name: "genderless", desc: "女人,女性" },
				{ name: "open-arm", desc: "张开双臂" },
				{
					name: "body-scan",
					desc: "gesture recognition,body,扫描身体,体态识别,动作之别,手势识别",
				},
				{ name: "parent", desc: "patriarch,父母,亲子,家长" },
				{ name: "robot", desc: "AI,mechanic,机器人" },
				{ name: "robot-2", desc: "AI,mechanic,机器人" },
				{ name: "robot-3", desc: "AI,mechanic,机器人" },
				{ name: "aliens", desc: "science fiction,ET,外星人,科幻小说" },
				{
					name: "bear-smile",
					desc: "cartoon,anime,cartoon,小熊,微笑,儿童,动画片,卡通,动漫",
				},
				{
					name: "mickey",
					desc: "cartoon,disney,迪士尼,米老鼠,微笑,儿童,动画片",
				},
				{ name: "criminal", desc: "horror,thriller,罪犯,犯罪,恐怖" },
				{ name: "ghost", desc: "horror,thriller,鬼怪,恐怖,恐惧" },
				{ name: "ghost-2", desc: "horror,鬼怪,恐怖,恐惧" },
				{ name: "ghost-smile", desc: "鬼怪,笑" },
				{ name: "star-smile", desc: "animation,动画,微笑,星星" },
				{
					name: "spy",
					desc: "incognito mode,detective,secret,间谍,侦探,无痕模式,隐私模式",
				},
			],
			size: 58,
		},
		{
			name: "天气",
			namee: "Weather",
			icons: [
				{ name: "sun", desc: "light mode,sunny,太阳,白天模式,晴天" },
				{ name: "moon", desc: "dark mode,night,月亮,夜间模式,月牙" },
				{ name: "flashlight", desc: "闪电" },
				{ name: "cloudy", desc: "多云" },
				{ name: "cloudy-2", desc: "多云" },
				{ name: "mist", desc: "雾气,雾霾" },
				{ name: "foggy", desc: "大雾" },
				{ name: "cloud-windy", desc: "风" },
				{ name: "windy", desc: "大风,刮风" },
				{ name: "rainy", desc: "下雨,雨天" },
				{ name: "drizzle", desc: "小雨" },
				{ name: "showers", desc: "中雨" },
				{ name: "heavy-showers", desc: "大雨" },
				{ name: "thunderstorms", desc: "雷暴,雷阵雨" },
				{ name: "hail", desc: "冰雹" },
				{ name: "snowy", desc: "下雪,雪天" },
				{ name: "sun-cloudy", desc: "晴转多云" },
				{ name: "moon-cloudy", desc: "夜间多云" },
				{ name: "tornado", desc: "龙卷风" },
				{ name: "typhoon", desc: "cyclone,tornado,龙卷风,旋风,台风" },
				{ name: "haze", desc: "阴霾,薄雾" },
				{ name: "haze-2", desc: "阴霾,薄雾" },
				{ name: "sun-foggy", desc: "薄雾" },
				{ name: "moon-foggy", desc: "薄雾" },
				{ name: "moon-clear", desc: "夜间模式,夜间无云" },
				{ name: "temp-hot", desc: "temperature,温度,高温,热" },
				{ name: "temp-cold", desc: "temperature,温度,低温,冷" },
				{ name: "celsius", desc: "temperature,温度,摄氏度" },
				{ name: "fahrenheit", desc: "temperature,温度,华氏度" },
				{ name: "water-percent", desc: "humidity,水,百分比,湿度" },
				{ name: "fire", desc: "flame,hot,火,热门" },
				{ name: "blaze", desc: "flame,火灾" },
				{ name: "earthquake", desc: "地震" },
				{ name: "flood", desc: "洪水" },
				{ name: "meteor", desc: "流星,陨石" },
				{ name: "rainbow", desc: "彩虹" },
				{
					name: "shining",
					desc: "star,magic,ai,twinkle,星星,魔法,闪烁",
				},
				{
					name: "shining-2",
					desc: "star,magic,ai,twinkle,星星,魔法,闪烁",
				},
				{
					name: "sparkling",
					desc: "shining,star,magic,ai,twinkle,星星,魔法,闪烁",
				},
				{
					name: "sparkling-2",
					desc: "shining,star,magic,ai,twinkle,星星,魔法,闪烁",
				},
			],
			size: 40,
		},
		{
			name: "其它",
			namee: "Others",
			icons: [
				{ name: "basketball", desc: "sports,篮球,运动,体育" },
				{
					name: "bell",
					desc: "cartoon,anime,doraemon,铃铛,哆啦A梦,卡通,动漫",
				},
				{ name: "billiards", desc: "sports,运动,台球,8,体育" },
				{ name: "boxing", desc: "sports,运动,拳击,体育" },
				{ name: "door-lock", desc: "门锁" },
				{ name: "door-lock-box", desc: "门锁" },
				{ name: "football", desc: "sports,运动,足球,体育" },
				{ name: "game", desc: "pac man,游戏,吃豆人,体育" },
				{ name: "handbag", desc: "fashion,时尚,手提包,女包" },
				{ name: "key", desc: "password,钥匙,密码" },
				{ name: "key-2", desc: "password,钥匙,密码" },
				{
					name: "lightbulb",
					desc: "energy,creativity,灯泡,能源,白炽灯,能源,电子产品",
				},
				{
					name: "lightbulb-flash",
					desc: "energy,creativity,idea,灯泡,白炽灯,能源,闪电,创意,灵感",
				},
				{ name: "outlet", desc: "二脚插座" },
				{ name: "outlet-2", desc: "三脚插座" },
				{ name: "plug", desc: "plugin,二脚插头" },
				{ name: "plug-2", desc: "plugin,三脚插头" },
				{
					name: "ping-pong",
					desc: "sports,table tennis,运动,乒乓球,球拍,体育",
				},
				{ name: "reserved", desc: "已预定,会议室屏幕,电视,显示器" },
				{ name: "shirt", desc: "clothes,衬衫,衣服,服饰,西装,西服" },
				{ name: "sword", desc: "war,刀剑,战争,战斗,玄幻,对抗" },
				{ name: "t-shirt", desc: "skin,theme,T恤,皮肤,主题,服饰" },
				{ name: "t-shirt-2", desc: "skin,theme,T恤,皮肤,主题,服饰" },
				{ name: "t-shirt-air", desc: "dry,T恤,风干,烘干,服饰" },
				{ name: "umbrella", desc: "protect,雨伞,保护,保险" },
				{ name: "character-recognition", desc: "ocr,文字识别" },
				{ name: "voice-recognition", desc: "asr,语音识别,音频" },
				{ name: "leaf", desc: "energy,ecology,树叶,节能,环保,草,植物" },
				{ name: "plant", desc: "植物,叶子,草,花盆" },
				{ name: "seedling", desc: "树苗,植物,叶子,草" },
				{ name: "tree", desc: "植物,树木" },
				{ name: "recycle", desc: "recyclable,可回收,循环" },
				{ name: "scales-2", desc: "厨房称" },
				{ name: "scales", desc: "balance,称,天平,天秤" },
				{ name: "scales-3", desc: "balance,称,天平,天秤" },
				{ name: "fridge", desc: "refrigerator,电冰箱,柜子,服务器" },
				{
					name: "wheelchair",
					desc: "accessbility,轮椅,可访问性,辅助功能,残疾人",
				},
				{ name: "cactus", desc: "desertr,仙人掌,沙漠,植物" },
				{ name: "door", desc: "门,建筑" },
				{ name: "door-open", desc: "开门,建筑" },
				{ name: "door-closed", desc: "关门,建筑" },
				{
					name: "graduation-cap",
					desc: "cap,school,student,毕业,帽子,学校,学生",
				},
				{ name: "box-1", desc: "instance,盒子,实例" },
				{ name: "box-2", desc: "instance,盒子,实例" },
				{ name: "box-3", desc: "instance,3d,盒子,实例,立体" },
				{ name: "candle", desc: "蜡烛" },
				{ name: "cross", desc: "tomb,十字架,坟墓" },
				{
					name: "infinity",
					desc: "infinite,endless,loop,forever,math,eternal,无限,循环,永远,永久,永恒",
				},
				{ name: "goggles", desc: "vr,vision,护目镜" },
				{ name: "glasses", desc: "vision,spectacles,眼镜" },
				{ name: "glasses-2", desc: "vision,spectacles,眼镜" },
				{ name: "dice-1", desc: "random,骰子" },
				{ name: "dice-2", desc: "random,骰子" },
				{ name: "dice-4", desc: "random,骰子" },
				{ name: "dice-6", desc: "random,骰子" },
				{ name: "dice-5", desc: "random,骰子" },
				{ name: "dice-3", desc: "random,骰子" },
				{ name: "dice", desc: "random,骰子" },
				{ name: "flower", desc: "plant,植物,花" },
				{ name: "armchair", desc: "sofa,seat,手扶椅,沙发,座位" },
				{ name: "sofa", desc: "armchair,seat,手扶椅,沙发,座位" },
			],
			size: 61,
		},
	],
};
