//图标选择器配置
export default {
	icons: [
		{
			name: "箭头",
			namee: "Arrows",
			icons: [
				{
					name: "corner-right-down",
					desc: "arrow,箭头,右下",
					type: "both",
				},
				{
					name: "corner-left-up",
					desc: "arrow,箭头,左上",
					type: "both",
				},
				{
					name: "corner-left-down",
					desc: "arrow,箭头,左下",
					type: "both",
				},
				{
					name: "corner-down-left",
					desc: "arrow,箭头,下左",
					type: "both",
				},
				{
					name: "contract-up-down",
					desc: "arrow,fold,收起",
					type: "both",
				},
				{
					name: "contract-right",
					desc: "arrow,slide,pull,fold,展开,收起,右",
					type: "both",
				},
				{
					name: "contract-left-right",
					desc: "arrow,fold,收起",
					type: "both",
				},
				{
					name: "contract-left",
					desc: "slide,pull,fold,arrow",
					type: "both",
				},
				{
					name: "drag-move",
					desc: "arrow,拖拽,移动,箭头",
					type: "both",
				},
				{
					name: "expand-left-right",
					desc: "arrow,unfold,dropdown,switch",
					type: "both",
				},
				{
					name: "drag-move-2",
					desc: "arrow,拖拽,移动,箭头",
					type: "both",
				},
				{
					name: "corner-up-left-double",
					desc: "arrow,replay-all,回复全部",
					type: "both",
				},
				{
					name: "corner-up-right-double",
					desc: "arrow,forward-all,转发全部",
					type: "both",
				},
				{
					name: "corner-up-left",
					desc: "arrow,箭头,上左",
					type: "both",
				},
				{
					name: "corner-up-right",
					desc: "arrow,箭头,上右",
					type: "both",
				},
				{
					name: "corner-right-up",
					desc: "arrow,箭头,右上",
					type: "both",
				},
				{
					name: "corner-down-right",
					desc: "arrow,箭头,下右",
					type: "both",
				},
				{
					name: "skip-right",
					desc: "arrow,unfold,next,expend,跳过,展开,收起",
					type: "both",
				},
				{
					name: "skip-up",
					desc: "arrow,unfold,top,expend,置顶,展开,收起",
					type: "both",
				},
				{
					name: "skip-left",
					desc: "arrow,unfold,expend,bottom,展开,收起",
					type: "both",
				},
				{
					name: "expand-up-down",
					desc: "arrow,unfold,dropdown,switch,展开",
					type: "both",
				},
				{
					name: "skip-down",
					desc: "arrow,unfold,next,expend,跳过,展开,收起",
					type: "both",
				},
				{
					name: "expand-right",
					desc: "arrow,展开,收起,右",
					type: "both",
				},
				{
					name: "expand-left",
					desc: "slide,pull,unfold,arrow",
					type: "both",
				},
				{
					name: "arrow-left-right",
					desc: "exchange,swap,箭头,左右,交换,换算,兑换",
					type: "both",
				},
				{ name: "arrow-left-up", desc: "corner,左上", type: "both" },
				{
					name: "arrow-right-circle",
					desc: "forward,箭头,向右",
					type: "both",
				},
				{
					name: "arrow-right-up",
					desc: "send,corner,右上,发送",
					type: "both",
				},
				{ name: "arrow-right-down", desc: "corner,右下", type: "both" },
				{ name: "arrow-turn-forward", desc: "箭头,掉头", type: "both" },
				{ name: "arrow-turn-back", desc: "箭头,掉头", type: "both" },
				{ name: "arrow-up-circle", desc: "箭头,向上", type: "both" },
				{
					name: "arrow-up-down",
					desc: "exchange,swap,箭头,上下,交换,换算,兑换",
					type: "both",
				},
				{
					name: "arrow-down-circle",
					desc: "箭头,向下,下载",
					type: "both",
				},
				{
					name: "arrow-go-forward",
					desc: "redo,箭头,重做,撤销,撤回",
					type: "both",
				},
				{
					name: "arrow-go-back",
					desc: "undo,箭头,返回,撤销,撤回",
					type: "both",
				},
				{
					name: "arrow-left-circle",
					desc: "backward,箭头,向左,返回",
					type: "both",
				},
				{
					name: "arrow-left-down",
					desc: "receive,corner,箭头,左下,接收,收款",
					type: "both",
				},
			],
			size: 38,
		},
		{
			name: "建筑",
			namee: "Buildings",
			icons: [
				{
					name: "home-heart",
					desc: "house,心,房子,家,主页,孤儿院",
					type: "both",
				},
				{ name: "home-6", desc: "house,房子,家,主页", type: "both" },
				{ name: "home-8", desc: "house,房子,家,主页", type: "both" },
				{ name: "home-7", desc: "house,房子,家,主页", type: "both" },
				{ name: "home-2", desc: "house,房子,家,主页", type: "both" },
				{ name: "home-4", desc: "house,房子,家,主页", type: "both" },
				{
					name: "home-smile",
					desc: "house,smart home,smile,房子,智能家居,微笑",
					type: "both",
				},
				{ name: "home-office", desc: "居家办公", type: "both" },
				{ name: "home", desc: "house,房子,家,主页", type: "both" },
				{
					name: "school",
					desc: "college,university,学校,学院",
					type: "both",
				},
				{ name: "home-5", desc: "house,房子,家,主页", type: "both" },
				{
					name: "home-smile-2",
					desc: "house,smart home,smile,房子,智能家居,微笑",
					type: "both",
				},
				{
					name: "home-wifi",
					desc: "smart home,房子,家具,智能家居",
					type: "both",
				},
				{
					name: "store-3",
					desc: "shop,mall,supermarket,retail,商店,超市,店铺,商家",
					type: "both",
				},
				{ name: "home-gear", desc: "house,房子,工厂", type: "both" },
				{ name: "hospital", desc: "medical,health,医院", type: "both" },
				{ name: "home-3", desc: "house,房子,家,主页", type: "both" },
				{
					name: "store-2",
					desc: "shop,mall,supermarket,retail,商店,超市,店铺,商家",
					type: "both",
				},
				{ name: "tent", desc: "camping,帐篷,露营,营地", type: "both" },
				{
					name: "ancient-pavilion",
					desc: "historical,genre,scenic,trip,travel,旅行,旅游,凉亭,古代,历史,景区",
					type: "both",
				},
				{
					name: "ancient-gate",
					desc: "historical,genre,scenic,trip,travel,旅行,旅游,城门,古代,历史,景区",
					type: "both",
				},
				{
					name: "government",
					desc: "building,政府,建筑,大会堂",
					type: "both",
				},
				{
					name: "building-2",
					desc: "city,office,construction,enterprise,城市,建筑,楼,企业",
					type: "both",
				},
				{
					name: "building",
					desc: "city,office,enterprise,建筑,城市,楼,办公楼,写字楼,企业",
					type: "both",
				},
				{
					name: "community",
					desc: "building,hotel,社区,建筑,酒店",
					type: "both",
				},
				{
					name: "building-4",
					desc: "city,office,enterprise,建筑,城市,楼,办公楼,写字楼,企业",
					type: "both",
				},
				{
					name: "bank",
					desc: "bank,finance,savings,banking,银行,交易所",
					type: "both",
				},
				{
					name: "store",
					desc: "shop,mall,supermarket,retail,商店,超市,店铺,商家",
					type: "both",
				},
			],
			size: 28,
		},
		{
			name: "商务",
			namee: "Business",
			icons: [
				{
					name: "attachment",
					desc: "annex,paperclip,附件,曲别针",
					type: "",
				},
				{ name: "printer", desc: "打印机", type: "both" },
				{
					name: "archive-drawer",
					desc: "night table,收纳,抽屉,归档,存档,床头柜",
					type: "both",
				},
				{
					name: "bar-chart-horizontal",
					desc: "statistics,rhythm,柱状图,统计,韵律,节奏",
					type: "both",
				},
				{
					name: "briefcase-2",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
					type: "both",
				},
				{
					name: "bar-chart",
					desc: "statistics,rhythm,柱状图,统计,韵律,节奏",
					type: "both",
				},
				{
					name: "bar-chart-2",
					desc: "statistics,rhythm,柱状图,统计,排行,节奏",
					type: "both",
				},
				{
					name: "award",
					desc: "medal,achievement,badge,成就,奖牌,金牌,勋章",
					type: "both",
				},
				{ name: "ad-square", desc: "ad,广告,推广", type: "both" },
				{ name: "at", desc: "@,mention,提到,在", type: "both" },
				{
					name: "archive",
					desc: "box,收纳,归档,存档,盒子,纸箱",
					type: "both",
				},
				{
					name: "bar-chart-grouped",
					desc: "statistics,rhythm,柱状图,统计,分组",
					type: "both",
				},
				{
					name: "archive-stack",
					desc: "box,收纳,归档,存档,盒子,纸箱,堆叠",
					type: "both",
				},
				{
					name: "archive-2",
					desc: "box,收纳,归档,存档,盒子,纸箱",
					type: "both",
				},
				{
					name: "calendar-close",
					desc: "date,plan,schedule,agenda,error,cancel,日历,日期,月份,计划,日程,时间表,取消,错误",
					type: "both",
				},
				{
					name: "bar-chart-square",
					desc: "statistics,rhythm,柱状图,统计,节奏",
					type: "both",
				},
				{
					name: "briefcase-5",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
					type: "both",
				},
				{
					name: "briefcase",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
					type: "both",
				},
				{
					name: "calendar",
					desc: "date,plan,schedule,agenda,日历,日期,月份,计划,日程,时间表",
					type: "both",
				},
				{
					name: "bubble-chart",
					desc: "data,analysis,statistics,circles,气泡图,统计",
					type: "both",
				},
				{
					name: "briefcase-3",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
					type: "both",
				},
				{ name: "bookmark-2", desc: "tag,书签,标记", type: "both" },
				{ name: "bookmark", desc: "tag,书签,标记", type: "both" },
				{
					name: "bookmark-3",
					desc: "tag,书签,标记,荣誉",
					type: "both",
				},
				{
					name: "calendar-check",
					desc: "date,plan,schedule,agenda,check-in,punch,日历,日期,月份,计划,日程,时间表,签到,打卡",
					type: "both",
				},
				{ name: "copyright", desc: "版权", type: "line" },
				{
					name: "calendar-2",
					desc: "date,plan,schedule,agenda,日历,日期,月份,计划,日程,时间表",
					type: "both",
				},
				{
					name: "calendar-schedule",
					desc: "date,plan,schedule,agenda,date,time,日历,日期,月份,计划,日程,时间表,预定,预约",
					type: "both",
				},
				{
					name: "calendar-event",
					desc: "date,plan,schedule,agenda,日历,日期,月份,计划,日程,时间表",
					type: "both",
				},
				{
					name: "briefcase-4",
					desc: "bag,baggage,公文包,行李箱,旅行箱,皮包",
					type: "both",
				},
				{
					name: "customer-service-2",
					desc: "headset,headphones,earphones,smile,客服,售后,耳机,耳麦",
					type: "both",
				},
				{ name: "creative-commons", desc: "知识共享", type: "both" },
				{
					name: "creative-commons-nd",
					desc: "no derivative works,copyright,版权,知识共享,禁止演绎",
					type: "both",
				},
				{
					name: "cloud-off",
					desc: "offline mode,connection fail,slash,weather,云端,断网,无信号,连接失败",
					type: "both",
				},
				{
					name: "creative-commons-by",
					desc: "attribution,copyright,版权,知识共享,署名",
					type: "both",
				},
				{
					name: "calendar-todo",
					desc: "date,plan,schedule,agenda,日历,日期,月份,计划,日程,时间表",
					type: "both",
				},
				{
					name: "flag",
					desc: "banner,pin,旗帜,旗子,国旗,标记",
					type: "both",
				},
				{
					name: "global",
					desc: "earth,union,world,language,地球,联合,世界,全球,语言",
					type: "both",
				},
				{ name: "inbox", desc: "收件箱", type: "both" },
				{
					name: "creative-commons-zero",
					desc: "cc0,copyright,版权,知识共享",
					type: "both",
				},
				{ name: "copyleft", desc: "著佐权", type: "both" },
				{
					name: "creative-commons-nc",
					desc: "noncommercial,copyright,版权,知识共享,非商业用途",
					type: "both",
				},
				{ name: "cloud", desc: "weather,云端", type: "both" },
				{
					name: "creative-commons-sa",
					desc: "share alike,copyright,版权,知识共享,相同方式共享",
					type: "both",
				},
				{
					name: "inbox-unarchive",
					desc: "unzip,unpack,extract,收件箱,取消归档,还原,解压缩",
					type: "both",
				},
				{
					name: "inbox-archive",
					desc: "收件箱,归档,收纳",
					type: "both",
				},
				{
					name: "mail-close",
					desc: "envelope,email,inbox,failed,x,信封,邮箱,邮件,失败",
					type: "both",
				},
				{
					name: "flag-2",
					desc: "banner,pin,旗帜,旗子,国旗,标记",
					type: "both",
				},
				{
					name: "line-chart",
					desc: "data,analysis,stats,折线图,数据,分析",
					type: "both",
				},
				{
					name: "mail-add",
					desc: "envelope,email,inbox,add,信封,邮箱,邮件,新增,添加",
					type: "both",
				},
				{
					name: "mail-download",
					desc: "envelope,email,inbox,download,信封,邮箱,邮件,下载",
					type: "both",
				},
				{
					name: "mail-open",
					desc: "envelope,email,inbox,信封,邮箱,邮件,收件箱",
					type: "both",
				},
				{
					name: "mail-check",
					desc: "envelope,email,inbox,read,信封,邮箱,邮件,已读",
					type: "both",
				},
				{
					name: "mail",
					desc: "envelope,email,inbox,信封,邮箱,邮件,收件箱",
					type: "both",
				},
				{
					name: "links",
					desc: "connection,address,联系,链接,地址",
					type: "both",
				},
				{
					name: "customer-service",
					desc: "headset,headphones,earphones,客服,售后,耳机,耳麦",
					type: "both",
				},
				{
					name: "mail-star",
					desc: "envelope,email,inbox,favorite,信封,邮箱,邮件,收藏,喜欢",
					type: "both",
				},
				{
					name: "mail-volume",
					desc: "envelope,email,inbox,promotional email,email campaign,subscription,sound,信封,邮箱,邮件,收件箱,推广,订阅",
					type: "both",
				},
				{
					name: "mail-send",
					desc: "envelope,email,inbox,zoom,whoosh,信封,邮箱,邮件,发送,发件箱",
					type: "both",
				},
				{
					name: "pie-chart-2",
					desc: "data,analysis,饼图,饼状图,数据,分析",
					type: "both",
				},
				{
					name: "megaphone",
					desc: "bullhorn,loudspeaker,commercial,campaign,扩音器,喇叭,广告,活动",
					type: "both",
				},
				{
					name: "donut-chart",
					desc: "data,analysis,circle,pie,环形图,数据,分析",
					type: "both",
				},
				{
					name: "honour",
					desc: "honor,glory,锦旗,荣誉,荣耀,军衔",
					type: "both",
				},
				{
					name: "medal-2",
					desc: "award,achievement,badge,成就,奖牌,金牌,勋章",
					type: "both",
				},
				{
					name: "pass-expired",
					desc: "passport,护照过期",
					type: "both",
				},
				{
					name: "mail-lock",
					desc: "envelope,email,inbox,lock,信封,邮箱,邮件,加密",
					type: "both",
				},
				{
					name: "printer-cloud",
					desc: "network,打印机,云打印",
					type: "both",
				},
				{ name: "send-plane-2", desc: "发送,纸飞机", type: "both" },
				{
					name: "mail-unread",
					desc: "envelope,email,inbox,信封,邮箱,邮件,未读",
					type: "both",
				},
				{
					name: "medal",
					desc: "award,achievement,badge,成就,奖牌,金牌,勋章",
					type: "both",
				},
				{ name: "pass-valid", desc: "passport,护照有效", type: "both" },
				{ name: "send-plane", desc: "发送,纸飞机", type: "both" },
				{
					name: "reply",
					desc: "forward,回复全部,回复所有",
					type: "both",
				},
				{
					name: "record-mail",
					desc: "voice mail,tape,录音,留言,语音信箱,磁带",
					type: "both",
				},
				{
					name: "mail-settings",
					desc: "envelope,email,inbox,settings,信封,邮箱,邮件,设置",
					type: "both",
				},
				{
					name: "pie-chart",
					desc: "data,analysis,饼图,饼状图,数据,分析",
					type: "both",
				},
				{
					name: "profile",
					desc: "id,档案,资料,身份证,证件",
					type: "both",
				},
				{
					name: "presentation",
					desc: "teaching,training,演讲,老师,培训",
					type: "both",
				},
				{
					name: "slideshow",
					desc: "presentation,meeting,PPT,keynote,投影,放映,演示,演讲,幻灯片,会议室",
					type: "both",
				},
				{
					name: "mail-forbid",
					desc: "envelope,email,inbox,privacy,信封,邮箱,邮件,禁止",
					type: "both",
				},
				{
					name: "slideshow-2",
					desc: "presentation,meeting,投影,放映,演示,演讲,幻灯片,会议室",
					type: "both",
				},
				{
					name: "slideshow-3",
					desc: "presentation,meeting,投影,放映,演示,演讲,视频会议,幻灯片,会议室",
					type: "both",
				},
				{ name: "trademark", desc: "注册,商标", type: "both" },
				{ name: "registered", desc: "注册,商标", type: "both" },
				{
					name: "reply-all",
					desc: "forward,回复,答复,留言,转发",
					type: "both",
				},
				{
					name: "pass-pending",
					desc: "passport,护照等待",
					type: "both",
				},
				{
					name: "window",
					desc: "browser,program,web,窗口,浏览器,程序,网站",
					type: "both",
				},
				{
					name: "service",
					desc: "heart,handshake,cooperation,client,服务,握手,心,合作",
					type: "both",
				},
				{
					name: "window-2",
					desc: "browser,program,web,窗口,浏览器,程序,网站",
					type: "both",
				},
				{ name: "seo", desc: "搜索引擎优化", type: "both" },
				{
					name: "shake-hands",
					desc: "cooperation,business,握手,合作,商务",
					type: "both",
				},
				{ name: "verified-badge", desc: "认证标志", type: "both" },
			],
			size: 92,
		},
		{
			name: "社交",
			namee: "Communication",
			icons: [
				{
					name: "chat-4",
					desc: "message,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "chat-quote",
					desc: "message,reply,comment,消息,引用回复",
					type: "both",
				},
				{
					name: "chat-off",
					desc: "message,reply,comment,slash,消息,聊天,回复,评论,禁止,关闭",
					type: "both",
				},
				{
					name: "chat-new",
					desc: "message,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "chat-delete",
					desc: "message,comment,消息,聊天,回复,评论,清除,删除",
					type: "both",
				},
				{
					name: "chat-history",
					desc: "message,历史消息,消息记录",
					type: "both",
				},
				{
					name: "chat-download",
					desc: "message,comment,消息,下载",
					type: "both",
				},
				{
					name: "chat-2",
					desc: "message,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "chat-follow-up",
					desc: "message,reply,comment,消息,+1,跟帖",
					type: "both",
				},
				{
					name: "chat-3",
					desc: "message,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "chat-check",
					desc: "message,reply,comment,消息,聊天,回复,评论,已阅",
					type: "both",
				},
				{
					name: "chat-heart",
					desc: "message,reply,comment,消息,聊天,回复,评论,心,点赞,收藏",
					type: "both",
				},
				{
					name: "chat-smile-2",
					desc: "message,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "chat-forward",
					desc: "message,comment,消息,聊天,转发",
					type: "both",
				},
				{
					name: "chat-thread",
					desc: "topic,hashtag,话题,井号,哈希",
					type: "both",
				},
				{
					name: "chat-private",
					desc: "message,私密消息,密聊",
					type: "both",
				},
				{
					name: "chat-smile",
					desc: "message,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "chat-upload",
					desc: "message,comment,消息,聊天,上传",
					type: "both",
				},
				{
					name: "chat-poll",
					desc: "message,vote,questionnaire,消息,投票,问卷调查",
					type: "both",
				},
				{
					name: "message-3",
					desc: "chat,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "message",
					desc: "chat,comment,reply,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "chat-smile-3",
					desc: "message,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "message-2",
					desc: "chat,reply,comment,消息,聊天,回复,评论",
					type: "both",
				},
				{
					name: "chat-voice",
					desc: "message,comment,消息,语音消息",
					type: "both",
				},
				{
					name: "discuss",
					desc: "message,reply,comment,消息,聊天,回复,评论,讨论,群聊",
					type: "both",
				},
				{
					name: "feedback",
					desc: "message,comment,消息,聊天,回复,评论,反馈",
					type: "both",
				},
				{
					name: "video-chat",
					desc: "message,comment,消息,视频聊天",
					type: "both",
				},
				{
					name: "questionnaire",
					desc: "message,comment,help,消息,聊天,回复,评论,讨论,调查问卷,帮助",
					type: "both",
				},
				{
					name: "question-answer",
					desc: "message,reply,comment,消息,聊天,回复,评论,讨论,群聊",
					type: "both",
				},
				{ name: "emoji-sticker", desc: "表情,贴纸", type: "both" },
				{ name: "speak", desc: "voice,讲话,声音", type: "both" },
			],
			size: 31,
		},
		{
			name: "设计",
			namee: "Design",
			icons: [
				{ name: "edit", desc: "pencil,铅笔,编辑", type: "both" },
				{ name: "artboard", desc: "grid,crop,画板,裁切", type: "both" },
				{ name: "collage", desc: "瀑布流布局,拼贴画", type: "both" },
				{ name: "ball-pen", desc: "圆珠笔", type: "both" },
				{
					name: "blur-off",
					desc: "water,drop,slash,模糊,水,滴,禁止,关闭",
					type: "both",
				},
				{
					name: "clockwise",
					desc: "rotate,right,右翻转,右旋转",
					type: "both",
				},
				{
					name: "clockwise-2",
					desc: "rotate,right,右翻转,右旋转",
					type: "both",
				},
				{
					name: "anticlockwise",
					desc: "rotate,left,counterclockwise,左翻转,左旋转",
					type: "both",
				},
				{ name: "brush-4", desc: "刷子", type: "both" },
				{
					name: "anticlockwise-2",
					desc: "rotate,left,counterclockwise,左翻转,左旋转",
					type: "both",
				},
				{ name: "brush-3", desc: "刷子", type: "both" },
				{ name: "compasses", desc: "圆规", type: "both" },
				{ name: "brush-2", desc: "刷子", type: "both" },
				{ name: "brush", desc: "笔刷,画笔,刷子", type: "both" },
				{ name: "circle", desc: "圆形", type: "both" },
				{ name: "crop-2", desc: "裁切", type: "both" },
				{
					name: "contrast-2",
					desc: "moon,dark,brightness,tonalit,月亮,夜间,对比度,亮度,色调",
					type: "both",
				},
				{
					name: "contrast-drop-2",
					desc: "water,brightness,tonalit,水,对比度,亮度,色调,滴",
					type: "both",
				},
				{ name: "compasses-2", desc: "圆规", type: "both" },
				{
					name: "contrast",
					desc: "brightness,tonalit,对比度,亮度,色调",
					type: "both",
				},
				{ name: "crop", desc: "裁切", type: "both" },
				{
					name: "contrast-drop",
					desc: "water,brightness,tonalit,水,对比度,亮度,色调,滴",
					type: "both",
				},
				{
					name: "color-filter",
					desc: "effect,滤镜,特效",
					type: "both",
				},
				{
					name: "crosshair-2",
					desc: "aim,target,goal,bullseye,crosshair,locate,焦点,聚焦,目标,靶心,瞄准镜,准心,定位",
					type: "both",
				},
				{
					name: "eraser",
					desc: "remove formatting,橡皮,擦除,清除格式",
					type: "both",
				},
				{
					name: "focus-2",
					desc: "aim,target,goal,bullseye,焦点,聚焦,目标,靶心",
					type: "both",
				},
				{
					name: "focus",
					desc: "aim,target,goal,焦点,聚焦,目标,靶心",
					type: "both",
				},
				{ name: "edit-square", desc: "编辑", type: "both" },
				{ name: "drop", desc: "water,blur,模糊,水,滴", type: "both" },
				{
					name: "drag-drop",
					desc: "drag and drop,mouse,拖拽,鼠标",
					type: "both",
				},
				{ name: "hexagon", desc: "六边形", type: "both" },
				{ name: "edit-circle", desc: "编辑", type: "both" },
				{ name: "input-method", desc: "输入法,文字", type: "both" },
				{ name: "edit-2", desc: "pencil,铅笔,编辑", type: "both" },
				{ name: "hammer", desc: "tool,锤子", type: "both" },
				{
					name: "focus-3",
					desc: "aim,target,goal,bullseye,crosshair,locate,焦点,聚焦,目标,靶心,瞄准镜,准心,定位",
					type: "both",
				},
				{ name: "layout-6", desc: "collage,布局,拼贴画", type: "both" },
				{ name: "layout-3", desc: "collage,布局,拼贴画", type: "both" },
				{ name: "layout-5", desc: "collage,布局,拼贴画", type: "both" },
				{ name: "ink-bottle", desc: "墨水瓶", type: "both" },
				{ name: "grid", desc: "table,网格,表格", type: "both" },
				{ name: "layout", desc: "布局", type: "both" },
				{
					name: "crosshair",
					desc: "aim,target,goal,bullseye,crosshair,locate,焦点,聚焦,目标,靶心,瞄准镜,准心,定位",
					type: "both",
				},
				{
					name: "layout-right",
					desc: "右侧布局,右侧导航",
					type: "both",
				},
				{ name: "layout-2", desc: "collage,布局,拼贴画", type: "both" },
				{ name: "layout-4", desc: "collage,布局,拼贴画", type: "both" },
				{ name: "layout-column", desc: "左右布局", type: "both" },
				{ name: "layout-grid", desc: "卡片布局,网格", type: "both" },
				{
					name: "layout-bottom",
					desc: "底部布局,底部导航",
					type: "both",
				},
				{ name: "layout-top", desc: "顶部布局,顶部导航", type: "both" },
				{ name: "layout-row", desc: "上下布局", type: "both" },
				{
					name: "layout-left",
					desc: "左侧布局,左侧导航",
					type: "both",
				},
				{
					name: "layout-masonry",
					desc: "collage,瀑布流布局,拼贴画",
					type: "both",
				},
				{ name: "pencil", desc: "edit,铅笔,编辑", type: "both" },
				{ name: "mark-pen", desc: "马克笔", type: "both" },
				{ name: "octagon", desc: "八边形", type: "both" },
				{ name: "pen-nib", desc: "钢笔,笔尖", type: "both" },
				{ name: "quill-pen", desc: "羽毛笔,钢笔,编辑", type: "both" },
				{
					name: "magic",
					desc: "fantasy,magic stick,beautify,wand,魔法棒,美化,幻想,魔幻",
					type: "both",
				},
				{ name: "paint-brush", desc: "填色,填充,刷子", type: "both" },
				{ name: "markup", desc: "标记,马克", type: "both" },
				{ name: "palette", desc: "color,调色盘,色板", type: "both" },
				{ name: "paint", desc: "fill,填色,填充,油漆桶", type: "both" },
				{
					name: "pantone",
					desc: "color,色板,潘通色,色号",
					type: "both",
				},
				{ name: "scissors-2", desc: "剪刀,裁剪,截屏", type: "both" },
				{ name: "ruler", desc: "尺子", type: "both" },
				{ name: "pentagon", desc: "五边形,五角形", type: "both" },
				{ name: "scissors-cut", desc: "剪刀,裁剪", type: "both" },
				{ name: "scissors", desc: "剪刀,裁剪", type: "both" },
				{
					name: "screenshot",
					desc: "capture,屏幕截图,截屏",
					type: "both",
				},
				{ name: "shadow", desc: "投影,影子", type: "both" },
				{ name: "rectangle", desc: "长方形,矩形", type: "both" },
				{ name: "square", desc: "正方形", type: "both" },
				{ name: "table-alt", desc: "表格", type: "both" },
				{
					name: "shape-2",
					desc: "border,形状,描边,边框",
					type: "both",
				},
				{ name: "shape", desc: "border,形状,描边,边框", type: "both" },
				{ name: "sip", desc: "吸管,取色器", type: "both" },
				{ name: "slice", desc: "knife,切图,切片,刀", type: "both" },
				{ name: "shapes", desc: "形状,模块", type: "both" },
				{
					name: "screenshot-2",
					desc: "capture,屏幕截图,截屏",
					type: "both",
				},
				{
					name: "tools",
					desc: "settings,screwdriver,configuration,工具,设置",
					type: "both",
				},
				{ name: "t-square", desc: "文字,字体,字号", type: "both" },
				{ name: "table", desc: "表格", type: "both" },
				{ name: "triangle", desc: "三角形", type: "both" },
			],
			size: 84,
		},
		{
			name: "开发",
			namee: "Development",
			icons: [
				{ name: "bug-2", desc: "虫子", type: "both" },
				{ name: "css3", desc: "css,web,styles", type: "both" },
				{ name: "code-square", desc: "代码,编程", type: "both" },
				{ name: "code", desc: "代码,编程", type: "both" },
				{
					name: "braces",
					desc: "code,math,大括号,花括号",
					type: "both",
				},
				{ name: "bug", desc: "虫子", type: "both" },
				{ name: "brackets", desc: "code,math,中括号", type: "both" },
				{
					name: "git-merge",
					desc: "combine,unite,branch,split,diverge,合并",
					type: "both",
				},
				{ name: "git-fork", desc: "", type: "both" },
				{
					name: "cursor",
					desc: "mouse,pointer,arrow,指针,鼠标",
					type: "both",
				},
				{
					name: "git-close-pull-request",
					desc: "取消,关闭",
					type: "both",
				},
				{
					name: "command",
					desc: "apple key,place of interest,modified key,花键,苹果键",
					type: "both",
				},
				{
					name: "git-branch",
					desc: "combine,unite,split,diverge,分支",
					type: "both",
				},
				{
					name: "git-commit",
					desc: "node,onewheel,circle line,dot line,history point,提交",
					type: "both",
				},
				{ name: "html5", desc: "html,h5,web", type: "both" },
				{
					name: "git-repository-commits",
					desc: "book,upload,仓库,提交",
					type: "both",
				},
				{ name: "git-pull-request", desc: "合并申请", type: "both" },
				{
					name: "git-repository",
					desc: "book,bookmark,仓库",
					type: "both",
				},
				{
					name: "git-repository-private",
					desc: "lock,secure,私密仓库,私人仓库",
					type: "both",
				},
				{ name: "parentheses", desc: "code,math,小括号", type: "both" },
				{
					name: "terminal-square",
					desc: "code,command line,prompt,终端,代码,命令行",
					type: "both",
				},
				{
					name: "terminal",
					desc: "code,command line,prompt,终端,代码,命令行",
					type: "both",
				},
				{ name: "puzzle", desc: "plugins,拼图,插件", type: "both" },
				{ name: "javascript", desc: "js,脚本", type: "both" },
				{ name: "puzzle-2", desc: "plugins,拼图,插件", type: "both" },
				{
					name: "terminal-window",
					desc: "code,command line,browser,app,ui,终端,代码,命令行",
					type: "both",
				},
			],
			size: 26,
		},
		{
			name: "设备",
			namee: "Device",
			icons: [
				{ name: "keyboard", desc: "input,键盘,输入", type: "both" },
				{ name: "u-disk", desc: "U盘,优盘", type: "both" },
				{ name: "cpu", desc: "中央处理器", type: "both" },
				{ name: "phone", desc: "电话", type: "both" },
				{ name: "cellphone", desc: "手机,电话", type: "both" },
				{
					name: "barcode",
					desc: "scan,扫码,条形码,条码",
					type: "both",
				},
				{ name: "airplay", desc: "mirroring,投屏,无线", type: "both" },
				{
					name: "database-2",
					desc: "storage,discs,silo,platter,数据库,存储",
					type: "both",
				},
				{
					name: "bluetooth-connect",
					desc: "wireless,蓝牙,连接,无线",
					type: "both",
				},
				{
					name: "base-station",
					desc: "wifi,signal tower,router,cast,基站,信号塔,路由器,广播,流量",
					type: "both",
				},
				{
					name: "computer",
					desc: "pc,monitor,display,screen,电脑,显示器",
					type: "both",
				},
				{ name: "bluetooth", desc: "wireless,蓝牙,无线", type: "both" },
				{
					name: "database",
					desc: "storage,resource,bars,progress,数据库,存储",
					type: "both",
				},
				{ name: "device-recover", desc: "恢复出厂设置", type: "both" },
				{ name: "dashboard-3", desc: "仪表盘", type: "both" },
				{ name: "dashboard-2", desc: "仪表盘", type: "both" },
				{
					name: "dual-sim-2",
					desc: "sim card,电话卡,卡槽,双卡双待",
					type: "both",
				},
				{
					name: "dual-sim-1",
					desc: "sim card,电话卡,卡槽,双卡双待",
					type: "both",
				},
				{ name: "gradienter", desc: "水平仪", type: "both" },
				{ name: "fingerprint", desc: "指纹", type: "both" },
				{ name: "device", desc: "设备", type: "both" },
				{ name: "fingerprint-2", desc: "指纹", type: "both" },
				{
					name: "instance",
					desc: "box,nft,cvm,实例,盒子,虚拟机",
					type: "both",
				},
				{
					name: "macbook",
					desc: "laptop,computer,笔记本",
					type: "both",
				},
				{ name: "gps", desc: "signal,定位,信号", type: "both" },
				{ name: "install", desc: "安装", type: "both" },
				{ name: "hotspot", desc: "手机热点", type: "both" },
				{
					name: "hard-drive-3",
					desc: "disc,server,storage,硬盘,服务器,存储",
					type: "both",
				},
				{
					name: "gamepad",
					desc: "consoles,controller,游戏手柄",
					type: "both",
				},
				{ name: "mouse", desc: "鼠标", type: "both" },
				{ name: "qr-scan", desc: "二维码,扫描", type: "both" },
				{ name: "qr-code", desc: "二维码", type: "both" },
				{
					name: "mac",
					desc: "monitor,imac,display,computer,screen,显示器",
					type: "both",
				},
				{ name: "qr-scan-2", desc: "二维码,扫描", type: "both" },
				{
					name: "remote-control",
					desc: "controller,遥控器",
					type: "both",
				},
				{ name: "restart", desc: "reload,refresh,重启", type: "both" },
				{
					name: "radar",
					desc: "satellite receiver,雷达,卫星接收器,锅",
					type: "both",
				},
				{
					name: "rfid",
					desc: "radio,frequency,identification,devices,无线,射频识别",
					type: "both",
				},
				{
					name: "remote-control-2",
					desc: "controller,遥控器",
					type: "both",
				},
				{
					name: "router",
					desc: "wifi,signal tower,radio,station,路由器,信号塔,广播,基站,流量",
					type: "both",
				},
				{ name: "save-2", desc: "floppy,保存,软盘", type: "both" },
				{ name: "scan-2", desc: "扫描", type: "both" },
				{ name: "rss", desc: "feed,subscribe,订阅", type: "both" },
				{ name: "save-3", desc: "floppy,保存,软盘", type: "both" },
				{ name: "sd-card", desc: "内存卡", type: "both" },
				{ name: "server", desc: "服务器", type: "both" },
				{ name: "sd-card-mini", desc: "内存卡", type: "both" },
				{ name: "shut-down", desc: "power off,关机", type: "both" },
				{ name: "rotate-lock", desc: "锁定旋转屏幕", type: "both" },
				{ name: "scan", desc: "扫描", type: "both" },
				{
					name: "sensor",
					desc: "capacitor,传感器,电容器",
					type: "both",
				},
				{ name: "sim-card", desc: "电话卡", type: "both" },
				{
					name: "signal-wifi-off",
					desc: "cellular,slash,offline,connection-fail,无线网,关闭,断网,链接失败",
					type: "both",
				},
				{
					name: "signal-wifi",
					desc: "cellular,strength,无线网,信号",
					type: "both",
				},
				{
					name: "signal-wifi-3",
					desc: "cellular,strength,无线网,信号",
					type: "both",
				},
				{
					name: "signal-wifi-2",
					desc: "cellular,strength,无线网,信号",
					type: "both",
				},
				{
					name: "signal-wifi-1",
					desc: "cellular,strength,无线网,信号",
					type: "both",
				},
				{ name: "usb", desc: "优盘", type: "both" },
				{ name: "smartphone", desc: "mobile,手机", type: "both" },
				{
					name: "tv-2",
					desc: "monitor,display,screen,television,电视,显示器",
					type: "both",
				},
				{ name: "uninstall", desc: "卸载", type: "both" },
				{
					name: "signal-wifi-error",
					desc: "cellular,offline,connection-fail,无线网,断网,链接失败,无信号",
					type: "both",
				},
				{ name: "tablet", desc: "平板电脑", type: "both" },
				{ name: "sim-card-2", desc: "电话卡", type: "both" },
				{
					name: "wifi-off",
					desc: "slash,offline,connection-fail,无线网,关闭,断网,链接失败",
					type: "both",
				},
				{
					name: "wireless-charging",
					desc: "power,flash,无线充电,闪充",
					type: "both",
				},
				{ name: "wifi", desc: "无线网", type: "both" },
				{
					name: "tv",
					desc: "television,antenna,rabbet ears,电视",
					type: "both",
				},
				{ name: "save", desc: "floppy,保存,软盘", type: "both" },
			],
			size: 69,
		},
		{
			name: "文档",
			namee: "Document",
			icons: [
				{
					name: "folder-open",
					desc: "directory,file,文件夹,目录,文档,打开",
					type: "both",
				},
				{
					name: "book-3",
					desc: "read,dictionary,booklet,书,阅读,字典,小册子",
					type: "both",
				},
				{
					name: "book-read",
					desc: "booklet,magazine,书,阅读,小册子,杂志",
					type: "both",
				},
				{
					name: "article",
					desc: "newspaper,document,publisher,print,page,word,file,publication,文章,报纸",
					type: "both",
				},
				{
					name: "book",
					desc: "read,dictionary,booklet,书,阅读,字典,小册子",
					type: "both",
				},
				{ name: "bill", desc: "账单", type: "both" },
				{
					name: "book-2",
					desc: "read,dictionary,booklet,书,阅读,字典,小册子",
					type: "both",
				},
				{
					name: "contacts-book-2",
					desc: "通讯录,联系人",
					type: "both",
				},
				{
					name: "book-marked",
					desc: "read,dictionary,booklet,书,阅读,字典,小册子,书签",
					type: "both",
				},
				{
					name: "contacts-book-upload",
					desc: "upload,通讯录,联系人,上传",
					type: "both",
				},
				{ name: "contacts-book", desc: "通讯录,联系人", type: "both" },
				{ name: "clipboard", desc: "copy,复制,剪切板", type: "both" },
				{
					name: "contract",
					desc: "examine,apporove,合约,合同,考试,审批通过",
					type: "both",
				},
				{
					name: "file-2",
					desc: "new,paper,文件,文档,新建",
					type: "both",
				},
				{
					name: "file-4",
					desc: "new,paper,文件,文档,新建",
					type: "both",
				},
				{
					name: "contacts-book-3",
					desc: "通讯录,联系人",
					type: "both",
				},
				{
					name: "book-open",
					desc: "read,booklet,magazine,书,阅读,小册子,杂志",
					type: "both",
				},
				{
					name: "file-copy-2",
					desc: "duplicate,clone,复制,克隆",
					type: "both",
				},
				{
					name: "file-close",
					desc: "文件,文档,关闭,删除,错误",
					type: "both",
				},
				{
					name: "file-chart",
					desc: "page,document,report,文件,文档,柱状图,报表",
					type: "both",
				},
				{
					name: "file-add",
					desc: "page,document,new,plus,add,文件,文档,新建",
					type: "both",
				},
				{ name: "draft", desc: "草稿箱,文件,文档,编辑", type: "both" },
				{
					name: "file-chart-2",
					desc: "report,文件,文档,饼图,报表",
					type: "both",
				},
				{
					name: "file-3",
					desc: "new,paper,文件,文档,新建",
					type: "both",
				},
				{ name: "file-check", desc: "文件,文档,对勾", type: "both" },
				{
					name: "file-code",
					desc: "config,文件,文档,代码,脚本,配置文件",
					type: "both",
				},
				{ name: "file-forbid", desc: "文件,文档,禁用", type: "both" },
				{
					name: "file-damage",
					desc: "breakdown,broken,corrupt,文件,文档,损坏,破损,破裂",
					type: "both",
				},
				{
					name: "file-copy",
					desc: "duplicate,clone,复制,克隆",
					type: "both",
				},
				{
					name: "file-cloud",
					desc: "network,文件,文档,云",
					type: "both",
				},
				{ name: "file-edit", desc: "文件,文档,编辑", type: "both" },
				{
					name: "file",
					desc: "new,paper,文件,文档,新建",
					type: "both",
				},
				{
					name: "file-history",
					desc: "record,文件,文档,记录,历史",
					type: "both",
				},
				{
					name: "file-download",
					desc: "page,document,文件,文档,下载",
					type: "both",
				},
				{ name: "file-excel-2", desc: "文档,表单", type: "both" },
				{
					name: "file-hwp",
					desc: "文件,文档,hangul word processor",
					type: "both",
				},
				{ name: "file-gif", desc: "文件,文档,动图", type: "both" },
				{ name: "file-image", desc: "文件,文档,图片", type: "both" },
				{
					name: "file-lock",
					desc: "page,document,文件,文档,锁",
					type: "both",
				},
				{ name: "file-marked", desc: "文件,文档,标记", type: "both" },
				{ name: "file-music", desc: "文件,文档,音乐", type: "both" },
				{ name: "file-list", desc: "清单,列表", type: "both" },
				{ name: "file-info", desc: "文件,文档,信息", type: "both" },
				{
					name: "file-list-3",
					desc: "newspaper,清单,列表,报纸",
					type: "both",
				},
				{ name: "file-paper-2", desc: "文件,文档,纸,谱", type: "both" },
				{ name: "file-list-2", desc: "清单,列表", type: "both" },
				{ name: "file-search", desc: "文件,文档,搜索", type: "both" },
				{
					name: "file-upload",
					desc: "page,document,文件,文档,上传",
					type: "both",
				},
				{
					name: "file-warning",
					desc: "page,document,paper,!,alert,important,exclamation,文件,文档,警告,提醒",
					type: "both",
				},
				{ name: "file-word-2", desc: "文档", type: "both" },
				{ name: "file-pdf-2", desc: "文件,文档", type: "both" },
				{ name: "file-paper", desc: "文件,文档,纸,谱", type: "both" },
				{
					name: "file-transfer",
					desc: "page,document,文件,文档,传输",
					type: "both",
				},
				{ name: "file-user", desc: "文件,文档,用户", type: "both" },
				{ name: "file-pdf", desc: "文件,文档", type: "both" },
				{ name: "file-zip", desc: "7z,rar,压缩包", type: "both" },
				{
					name: "file-reduce",
					desc: "page,document,subtract,delete,文件,文档,减",
					type: "both",
				},
				{ name: "file-text", desc: "文件,文档,文本", type: "both" },
				{
					name: "file-shield",
					desc: "protected,secured,文件,文档,盾牌,保护,安全",
					type: "both",
				},
				{ name: "file-ppt", desc: "文件,文档", type: "both" },
				{
					name: "file-shield-2",
					desc: "protected,secured,文件,文档,盾牌,保护,安全",
					type: "both",
				},
				{
					name: "file-unknow",
					desc: "文件,文档,未知,问号",
					type: "both",
				},
				{
					name: "folder-download",
					desc: "directory,file,文件夹,目录,文档,下载",
					type: "both",
				},
				{
					name: "folder-close",
					desc: "directory,file,文件夹,目录,文档,错误",
					type: "both",
				},
				{
					name: "folder-music",
					desc: "directory,file,audio,sound,文件夹,目录,文档,音乐",
					type: "both",
				},
				{
					name: "folder",
					desc: "directory,file,文件夹,目录,文档",
					type: "both",
				},
				{ name: "file-video", desc: "文件,文档,视频", type: "both" },
				{
					name: "folder-3",
					desc: "directory,file,文件夹,目录,文档",
					type: "line",
				},
				{
					name: "folder-forbid",
					desc: "directory,file,文件夹,目录,文档,禁用",
					type: "both",
				},
				{
					name: "folder-chart-2",
					desc: "report,文件夹,目录,文档,饼图,报表",
					type: "fill",
				},
				{
					name: "folder-history",
					desc: "directory,file,record,文件夹,目录,文档,记录,历史",
					type: "both",
				},
				{
					name: "folder-keyhole",
					desc: "directory,encryption,file,文件夹,目录,文档,打开,加密文档",
					type: "both",
				},
				{ name: "file-ppt-2", desc: "文件,文档", type: "both" },
				{
					name: "folder-add",
					desc: "directory,file,文件夹,目录,文档,添加",
					type: "both",
				},
				{
					name: "folder-cloud",
					desc: "directory,file,云文件夹,目录,云文档",
					type: "both",
				},
				{
					name: "folder-lock",
					desc: "directory,file,文件夹,目录,文档,锁",
					type: "both",
				},
				{
					name: "folder-image",
					desc: "directory,file,文件夹,目录,文档,图片",
					type: "both",
				},
				{
					name: "folder-received",
					desc: "directory,file,文件夹,目录,文档,接收",
					type: "both",
				},
				{
					name: "folder-shared",
					desc: "directory,file,文件夹,目录,文档,分享",
					type: "both",
				},
				{
					name: "folder-settings",
					desc: "directory,file,文件夹,目录,文档,设置",
					type: "both",
				},
				{
					name: "folder-5",
					desc: "directory,file,文件夹,目录,文档",
					type: "line",
				},
				{
					name: "folder-unknow",
					desc: "directory,file,文件夹,目录,文档,未知",
					type: "both",
				},
				{
					name: "folder-check",
					desc: "directory,file,文件夹,目录,文档,对勾",
					type: "line",
				},
				{
					name: "folder-shield-2",
					desc: "directory,file,protected,secured,文件夹,目录,文档,保护,盾牌,安全",
					type: "both",
				},
				{
					name: "folder-video",
					desc: "directory,file,文件夹,目录,文档,视频",
					type: "both",
				},
				{
					name: "folder-shield",
					desc: "directory,file,protected,secured,文件夹,目录,文档,保护,盾牌,安全",
					type: "fill",
				},
				{
					name: "folder-reduce",
					desc: "directory,file,remove,subtract,文件夹,目录,文档,减",
					type: "both",
				},
				{
					name: "folder-transfer",
					desc: "directory,file,文件夹,目录,文档,传输",
					type: "line",
				},
				{
					name: "folder-info",
					desc: "directory,file,文件夹,目录,文档,信息",
					type: "line",
				},
				{
					name: "folder-user",
					desc: "directory,file,文件夹,目录,文档,用户",
					type: "both",
				},
				{
					name: "folder-chart",
					desc: "report,文件夹,目录,文档,柱状图,报表",
					type: "fill",
				},
				{
					name: "file-settings",
					desc: "page,document,cog,gear,文件,文档,设置",
					type: "fill",
				},
				{
					name: "folder-zip",
					desc: "directory,file,文件夹,目录,文档,打开,压缩",
					type: "both",
				},
				{ name: "receipt", desc: "收据,凭据", type: "both" },
				{
					name: "folder-warning",
					desc: "!,alert,important,exclamation,alert,directory,file,文件夹,目录,文档,警告,提醒",
					type: "both",
				},
				{ name: "markdown", desc: "arrow,箭头,下", type: "both" },
				{
					name: "folder-upload",
					desc: "directory,file,文件夹,目录,文档,上传",
					type: "both",
				},
				{
					name: "folders",
					desc: "directory,file,文件夹,目录,文档,批量",
					type: "fill",
				},
				{ name: "keynote", desc: "演示文稿,幻灯片,讲演", type: "both" },
				{ name: "news", desc: "blog,新闻,博客", type: "both" },
				{ name: "todo", desc: "待办", type: "both" },
				{ name: "task", desc: "todo,任务,待办", type: "both" },
				{ name: "newspaper", desc: "新闻,报纸", type: "both" },
				{
					name: "sticky-note",
					desc: "new,paper,文件,文档,新建,便签纸,便利贴",
					type: "both",
				},
				{
					name: "survey",
					desc: "research,questionnaire,clipboard,checkboxes,form,census,调查,问卷,调研",
					type: "both",
				},
				{
					name: "sticky-note-2",
					desc: "new,paper,文件,文档,新建,便签纸,便利贴",
					type: "both",
				},
				{
					name: "sticky-note-add",
					desc: "new,paper,文件,文档,新建,便签纸,便利贴,添加",
					type: "both",
				},
			],
			size: 107,
		},
		{
			name: "编辑",
			namee: "Editor",
			icons: [
				{
					name: "indent-increase",
					desc: "indent less,quote,缩进",
					type: "both",
				},
				{ name: "align-right", desc: "ragged left,右对齐", type: "" },
				{
					name: "align-bottom",
					desc: "two arrows down,double-down,end,底部对齐",
					type: "",
				},
				{ name: "align-left", desc: "ragged right,左对齐", type: "" },
				{ name: "ai-generate", desc: "AI自动生成", type: "" },
				{
					name: "asterisk",
					desc: "*,all,everything,wildcard,星号",
					type: "",
				},
				{
					name: "bring-to-front",
					desc: "arrange,层级,移到最前面",
					type: "",
				},
				{
					name: "align-top",
					desc: "two arrows up,double-up,start,顶部对齐",
					type: "",
				},
				{ name: "align-center", desc: "居中对齐", type: "" },
				{ name: "font-mono", desc: "等宽字体", type: "" },
				{
					name: "bring-forward",
					desc: "arrange,层级,向上一层",
					type: "",
				},
				{ name: "font-sans-serif", desc: "衬线体", type: "" },
				{ name: "draggable", desc: "move,reorder,拖拽,排序", type: "" },
				{ name: "calendar-view", desc: "日历视图", type: "" },
				{ name: "font-color", desc: "文字色", type: "" },
				{ name: "bold", desc: "加粗", type: "" },
				{ name: "dropdown-list", desc: "下拉菜单", type: "" },
				{ name: "font-size", desc: "字号,字体大小", type: "" },
				{ name: "font-sans", desc: "非衬线体", type: "" },
				{ name: "h-2", desc: "heading,一级标题", type: "" },
				{
					name: "double-quotes-r",
					desc: "right,quotaion marks,双引号",
					type: "",
				},
				{ name: "h-6", desc: "heading,一级标题", type: "" },
				{ name: "h-3", desc: "heading,一级标题", type: "" },
				{ name: "emphasis-cn", desc: "着重号", type: "" },
				{
					name: "align-justify",
					desc: "four,lines,ruled,left-right,full width,排列对齐",
					type: "",
				},
				{ name: "italic", desc: "斜体", type: "fill" },
				{ name: "font-family", desc: "字体", type: "" },
				{ name: "focus-mode", desc: "聚焦模式,沉浸模式", type: "" },
				{ name: "hand", desc: "手,拖拽", type: "" },
				{ name: "input-field", desc: "cursor,输入框,光标", type: "" },
				{ name: "hashtag", desc: "#,pound,number,井号", type: "" },
				{ name: "kanban-view", desc: "看板视图", type: "" },
				{ name: "kanban-view-2", desc: "看板视图", type: "" },
				{ name: "gallery-view", desc: "画廊视图", type: "" },
				{
					name: "list-ordered",
					desc: "numbered list,有序列表",
					type: "",
				},
				{ name: "h-4", desc: "heading,一级标题", type: "" },
				{ name: "h-1", desc: "heading,一级标题", type: "" },
				{ name: "code-block", desc: "代码块", type: "" },
				{ name: "functions", desc: "Σ,sum,sigma,功能", type: "" },
				{
					name: "align-vertically",
					desc: "centered,middle,balance,垂直对齐",
					type: "",
				},
				{ name: "list-view", desc: "列表视图", type: "" },
				{ name: "list-check-2", desc: "check list,清单列表", type: "" },
				{
					name: "link",
					desc: "connection,address,联系,链接,地址",
					type: "fill",
				},
				{
					name: "link-unlink",
					desc: "connection,remove address,去除链接",
					type: "fill",
				},
				{ name: "line-height", desc: "leading,行高", type: "" },
				{ name: "gallery-view-2", desc: "画廊视图", type: "" },
				{ name: "h-5", desc: "heading,一级标题", type: "" },
				{ name: "input-cursor-move", desc: "移动输入光标", type: "" },
				{ name: "list-radio", desc: "vote,投票,列表", type: "" },
				{ name: "number-1", desc: "1,一,数字", type: "" },
				{ name: "omega", desc: "Ω,horseshoe,特殊符号", type: "" },
				{
					name: "format-clear",
					desc: "remove formatting,清除格式",
					type: "",
				},
				{ name: "heading", desc: "标题", type: "" },
				{
					name: "list-check-3",
					desc: "check list,清单列表,问卷,task",
					type: "",
				},
				{ name: "number-7", desc: "7,七,数字", type: "" },
				{
					name: "indent-decrease",
					desc: "indent more,quote,缩进",
					type: "line",
				},
				{
					name: "list-ordered-2",
					desc: "numbered list,有序列表",
					type: "",
				},
				{ name: "rounded-corner", desc: "圆角", type: "" },
				{ name: "list-check", desc: "check list,清单列表", type: "" },
				{ name: "number-3", desc: "3,三,数字", type: "" },
				{ name: "list-indefinite", desc: "列表", type: "" },
				{
					name: "double-quotes-l",
					desc: "left,quotaion marks,双引号",
					type: "",
				},
				{ name: "mind-map", desc: "mindmap,脑图,思维导图", type: "" },
				{
					name: "merge-cells-horizontal",
					desc: "合并单元格",
					type: "",
				},
				{ name: "number-6", desc: "6,六,数字", type: "" },
				{
					name: "send-backward",
					desc: "arrange,层级,向下一层",
					type: "",
				},
				{
					name: "page-separator",
					desc: "insert,分页符,插入",
					type: "",
				},
				{
					name: "single-quotes-l",
					desc: "left,quotaion marks,单引号",
					type: "",
				},
				{ name: "number-5", desc: "5,五,数字", type: "" },
				{ name: "number-2", desc: "2,二,数字", type: "" },
				{ name: "paragraph", desc: "¶,pilcrow,段落", type: "" },
				{
					name: "send-to-back",
					desc: "arrange,层级,移到最后面",
					type: "",
				},
				{
					name: "split-cells-horizontal",
					desc: "拆分单元格",
					type: "",
				},
				{
					name: "sort-alphabet-desc",
					desc: "ranking,ordering,降序排列,字母排序,倒序,倒序",
					type: "",
				},
				{ name: "slideshow-view", desc: "幻灯片视图", type: "" },
				{ name: "merge-cells-vertical", desc: "合并单元格", type: "" },
				{
					name: "sort-desc",
					desc: "ranking,ordering,降序排列,排序",
					type: "",
				},
				{
					name: "sort-asc",
					desc: "ranking,ordering,sorting,ascending,descending,升序排列,排序,顺序",
					type: "",
				},
				{
					name: "single-quotes-r",
					desc: "right,quotaion marks,单引号",
					type: "",
				},
				{ name: "number-9", desc: "9,九,数字", type: "" },
				{ name: "number-8", desc: "8,八,数字", type: "" },
				{ name: "separator", desc: "分割线", type: "" },
				{ name: "number-4", desc: "4,四,数字", type: "" },
				{
					name: "sort-alphabet-asc",
					desc: "ranking,ordering,升序排列,数字排序,顺序",
					type: "",
				},
				{ name: "number-0", desc: "0,零,数字", type: "" },
				{
					name: "sort-number-desc",
					desc: "ranking,ordering,降序排列,数字排序,倒序",
					type: "",
				},
				{ name: "text-direction-l", desc: "文本左对齐", type: "" },
				{
					name: "text-spacing",
					desc: "letter spacing,character spacing,kerning,tracking,字间距",
					type: "",
				},
				{
					name: "sort-number-asc",
					desc: "ranking,ordering,升序排列,数字排序,顺序",
					type: "",
				},
				{ name: "table-view", desc: "表格视图", type: "" },
				{ name: "superscript-2", desc: "角标,上标", type: "" },
				{
					name: "strikethrough",
					desc: "remove formatting,del,删除线",
					type: "",
				},
				{ name: "slash-commands", desc: "命令,斜线", type: "" },
				{ name: "subscript-2", desc: "角标,下标,脚注", type: "" },
				{ name: "overline", desc: "上划线", type: "" },
				{ name: "split-cells-vertical", desc: "拆分单元格", type: "" },
				{ name: "space", desc: "空格", type: "" },
				{ name: "text-direction-r", desc: "文本左对齐", type: "" },
				{ name: "superscript", desc: "角标,上标", type: "" },
				{ name: "text", desc: "字体", type: "" },
				{ name: "timeline-view", desc: "时间轴视图,甘特图", type: "" },
				{
					name: "sketching",
					desc: "signature,手写,手绘,签名",
					type: "",
				},
				{ name: "question-mark", desc: "?,问号", type: "" },
				{
					name: "strikethrough-2",
					desc: "remove formatting,del,删除线",
					type: "",
				},
				{ name: "flow-chart", desc: "流程图", type: "" },
				{ name: "translate-2", desc: "translator,翻译", type: "" },
				{ name: "subscript", desc: "角标,下标,脚注", type: "" },
				{ name: "text-block", desc: "文字块,文字片段", type: "" },
				{ name: "text-snippet", desc: "文字片段,剪切板", type: "" },
				{ name: "text-wrap", desc: "return,文本换行", type: "" },
				{ name: "translate", desc: "translator,翻译", type: "" },
				{ name: "table-2", desc: "表格", type: "" },
				{ name: "underline", desc: "下划线", type: "" },
				{ name: "stacked-view", desc: "堆叠视图", type: "" },
				{ name: "table-3", desc: "表格", type: "" },
			],
			size: 115,
		},
		{
			name: "金融",
			namee: "Finance",
			icons: [
				{ name: "gift", desc: "present,礼物", type: "both" },
				{
					name: "auction",
					desc: "hammer,gavel,拍卖,锤子",
					type: "both",
				},
				{
					name: "bank-card-2",
					desc: "credit,purchase,payment,cc,银行卡,信用卡,购买,消费,支付",
					type: "both",
				},
				{
					name: "bnb",
					desc: "cryptocurrency,数字货币,binance,币安币",
					type: "both",
				},
				{
					name: "bit-coin",
					desc: "currency,payment,货币,钱,比特币",
					type: "both",
				},
				{
					name: "bank-card",
					desc: "credit,purchase,payment,cc,银行卡,信用卡,购买,消费,支付",
					type: "both",
				},
				{
					name: "coupon-2",
					desc: "ticket,票,优惠券,代金券",
					type: "both",
				},
				{
					name: "coupon-3",
					desc: "ticket,票,优惠券,代金券",
					type: "both",
				},
				{ name: "coupon-5", desc: "优惠券,代金券", type: "both" },
				{
					name: "exchange-2",
					desc: "swap,交换,换算,兑换,交易",
					type: "both",
				},
				{
					name: "btc",
					desc: "cryptocurrency,数字货币,bitcoin,比特币",
					type: "both",
				},
				{ name: "coupon-4", desc: "优惠券,代金券", type: "both" },
				{
					name: "discount-percent",
					desc: "promotion,sale,折扣,促销,打折",
					type: "both",
				},
				{
					name: "copper-coin",
					desc: "currency,payment,铜币,硬币,货币,钱,支付",
					type: "both",
				},
				{ name: "coins", desc: "金币,硬币", type: "both" },
				{ name: "coin", desc: "金币,硬币", type: "both" },
				{
					name: "money-cny-circle",
					desc: "currency,coins,金币,payment,货币,钱,支付,人民币",
					type: "both",
				},
				{ name: "gift-2", desc: "present,礼物", type: "both" },
				{
					name: "exchange-square",
					desc: "swap,交换,换算,兑换,交易",
					type: "both",
				},
				{
					name: "funds-square",
					desc: "foundation,stock,基金,股票",
					type: "both",
				},
				{
					name: "coupon",
					desc: "ticket,票,优惠券,代金券",
					type: "both",
				},
				{
					name: "exchange-cny",
					desc: "swap,transfer,交换,换算,兑换,人民币,转账,交易",
					type: "both",
				},
				{
					name: "money-cny-square",
					desc: "currency,payment,货币,钱,支付,人民币",
					type: "both",
				},
				{
					name: "exchange",
					desc: "swap,交换,换算,兑换,交易",
					type: "both",
				},
				{
					name: "exchange-funds",
					desc: "swap,transfer,交换,换算,兑换,基金,股票,转账,交易",
					type: "both",
				},
				{
					name: "money-dollar-circle",
					desc: "currency,coins,金币,payment,cent,penny,货币,钱,支付,美元,美分,便士",
					type: "both",
				},
				{
					name: "exchange-dollar",
					desc: "swap,transfer,交换,换算,兑换,美元,转账,交易",
					type: "both",
				},
				{
					name: "money-dollar-square",
					desc: "currency,payment,货币,钱,支付,美元",
					type: "both",
				},
				{ name: "price-tag-2", desc: "label,标签,价签", type: "both" },
				{
					name: "money-pound-circle",
					desc: "currency,coins,金币,payment,货币,钱,支付,英镑",
					type: "both",
				},
				{ name: "increase-decrease", desc: "计算器", type: "both" },
				{
					name: "eth",
					desc: "cryptocurrency,数字货币,ethereum,以太坊",
					type: "both",
				},
				{ name: "nft", desc: "token", type: "both" },
				{ name: "red-packet", desc: "红包", type: "both" },
				{
					name: "hand-heart",
					desc: "help,donate,volunteer,welfare,帮助,爱心,捐赠,志愿者,公益",
					type: "both",
				},
				{
					name: "funds",
					desc: "foundation,stock,基金,股票",
					type: "both",
				},
				{
					name: "currency",
					desc: "cash,payment,货币,钱",
					type: "both",
				},
				{
					name: "copper-diamond",
					desc: "currency,coins,金币,钻石,货币,钱,支付",
					type: "both",
				},
				{
					name: "hand-coin",
					desc: "donate,business,捐赠",
					type: "both",
				},
				{ name: "price-tag", desc: "label,标签,价签", type: "both" },
				{
					name: "secure-payment",
					desc: "credit,purchase,payment,cc,银行卡,信用卡,购买,消费,支付,安全",
					type: "both",
				},
				{
					name: "money-euro-square",
					desc: "currency,payment,货币,钱,支付,欧元",
					type: "both",
				},
				{
					name: "money-pound-square",
					desc: "currency,payment,货币,钱,支付,英镑",
					type: "both",
				},
				{ name: "price-tag-3", desc: "label,标签,价签", type: "both" },
				{ name: "p2p", desc: "trade,点对点,交易", type: "both" },
				{ name: "percent", desc: "百分之,百分比", type: "both" },
				{
					name: "money-euro-circle",
					desc: "currency,coins,金币,payment,货币,钱,支付,欧元",
					type: "both",
				},
				{
					name: "shopping-basket-2",
					desc: "购物篮,购买,消费,商城",
					type: "both",
				},
				{
					name: "shopping-basket",
					desc: "购物篮,购买,消费,商城",
					type: "both",
				},
				{
					name: "refund",
					desc: "credit card,repayment,cc,银行卡,信用卡还款",
					type: "both",
				},
				{
					name: "shopping-bag-2",
					desc: "购物袋,购买,消费,商城",
					type: "both",
				},
				{
					name: "shopping-cart",
					desc: "购物车,购买,消费,商城",
					type: "both",
				},
				{
					name: "refund-2",
					desc: "credit card,repayment,cc,银行卡,信用卡还款",
					type: "both",
				},
				{
					name: "money-rupee-circle",
					desc: "currency,coins,金币,payment,货币,钱,支付,卢比",
					type: "both",
				},
				{
					name: "swap-square",
					desc: "exchange,交换,换算,兑换,交易",
					type: "both",
				},
				{ name: "trophy", desc: "奖品,奖杯,金杯", type: "both" },
				{
					name: "ticket",
					desc: "coupon,票,优惠券,代金券",
					type: "both",
				},
				{
					name: "shopping-cart-2",
					desc: "购物车,购买,消费,商城",
					type: "both",
				},
				{
					name: "swap-3",
					desc: "flow direction,exchange,交换,换算,兑换,交易",
					type: "both",
				},
				{
					name: "shopping-bag-3",
					desc: "购物袋,购买,消费,商城",
					type: "both",
				},
				{
					name: "ticket-2",
					desc: "coupon,票,优惠券,代金券",
					type: "both",
				},
				{
					name: "wallet-2",
					desc: "money clip,钱包,卡包",
					type: "both",
				},
				{ name: "stock", desc: "股票", type: "both" },
				{
					name: "swap-2",
					desc: "flow direction,exchange,交换,换算,兑换,交易",
					type: "both",
				},
				{
					name: "wallet-3",
					desc: "money clip,钱包,卡包",
					type: "both",
				},
				{
					name: "swap",
					desc: "exchange,交换,换算,兑换,交易",
					type: "both",
				},
				{
					name: "token-swap",
					desc: "cryptocurrency,数字货币,代币,兑换",
					type: "both",
				},
				{ name: "wallet", desc: "pocketbook,钱包,卡包", type: "both" },
				{ name: "water-flash", desc: "水电费", type: "both" },
				{ name: "vip", desc: "会员", type: "fill" },
				{
					name: "xtz",
					desc: "cryptocurrency,数字货币,tezos,兔子币",
					type: "both",
				},
				{
					name: "xrp",
					desc: "cryptocurrency,数字货币,ripple,瑞波币",
					type: "both",
				},
			],
			size: 72,
		},
		{
			name: "食物",
			namee: "Food",
			icons: [
				{ name: "cake", desc: "anniversary,蛋糕", type: "both" },
				{
					name: "cake-2",
					desc: "anniversary,蛋糕,生日,蜡烛",
					type: "both",
				},
				{ name: "cake-3", desc: "蛋糕,生日,蜡烛", type: "both" },
				{ name: "beer", desc: "cup,啤酒杯", type: "both" },
				{ name: "bowl", desc: "soup,碗,汤", type: "both" },
				{ name: "restaurant", desc: "餐厅,饭店", type: "both" },
				{ name: "drinks", desc: "coffee,饮料,咖啡", type: "both" },
				{
					name: "goblet",
					desc: "cup,wine glass,高脚杯,酒杯",
					type: "both",
				},
				{
					name: "knife-blood",
					desc: "crime,菜刀,犯罪,血,杀人",
					type: "both",
				},
				{ name: "knife", desc: "菜刀", type: "both" },
				{ name: "drinks-2", desc: "juice,饮料,果汁", type: "both" },
				{ name: "restaurant-2", desc: "餐厅,饭店", type: "both" },
				{ name: "cup", desc: "tea,coffee,杯子,咖啡,茶", type: "both" },
			],
			size: 13,
		},
		{
			name: "医药",
			namee: "Health & Medical",
			icons: [
				{ name: "capsule", desc: "medicine, 胶囊,药", type: "both" },
				{ name: "dossier", desc: "病例", type: "both" },
				{
					name: "dislike",
					desc: "like,love,remove favorite,心,不喜欢,取消收藏",
					type: "both",
				},
				{ name: "first-aid-kit", desc: "case,急救箱", type: "both" },
				{
					name: "empathize",
					desc: "care,heart,同理心,关爱,心",
					type: "both",
				},
				{
					name: "hand-sanitizer",
					desc: "alcohol,酒精消毒洗手液",
					type: "both",
				},
				{ name: "brain", desc: "think,大脑,思考", type: "both" },
				{
					name: "flask",
					desc: "testing,experimental,experiment,烧瓶,实验,试验",
					type: "both",
				},
				{
					name: "heart-add",
					desc: "like,love,favorite,心,喜欢,爱,收藏",
					type: "both",
				},
				{
					name: "heart-2",
					desc: "like,love,favorite,心,喜欢,爱,收藏",
					type: "both",
				},
				{
					name: "heart-pulse",
					desc: "heart rate,脉搏,心率",
					type: "both",
				},
				{
					name: "heart-3",
					desc: "like,love,favorite,心,喜欢,爱,收藏",
					type: "both",
				},
				{ name: "medicine-bottle", desc: "药瓶", type: "both" },
				{
					name: "health-book",
					desc: "健康手册,医疗手册",
					type: "both",
				},
				{
					name: "heart",
					desc: "like,love,favorite,心,喜欢,爱,收藏",
					type: "both",
				},
				{ name: "lungs", desc: "肺部", type: "both" },
				{ name: "surgical-mask", desc: "外科医用口罩", type: "both" },
				{ name: "hearts", desc: "romance,爱情,浪漫,心", type: "both" },
				{ name: "psychotherapy", desc: "心理治疗", type: "both" },
				{ name: "mental-health", desc: "心理健康", type: "both" },
				{ name: "nurse", desc: "doctors,医生,护士", type: "both" },
				{
					name: "rest-time",
					desc: "close,休息时间,打烊",
					type: "both",
				},
				{
					name: "microscope",
					desc: "testing,experimental,experiment,显微镜,实验,试验",
					type: "both",
				},
				{
					name: "pulse",
					desc: "wave,heart rate,脉搏,心率,波",
					type: "both",
				},
				{ name: "thermometer", desc: "体温计", type: "both" },
				{
					name: "test-tube",
					desc: "testing,experimental,experiment,试管,实验,试验",
					type: "both",
				},
				{ name: "zzz", desc: "睡觉", type: "both" },
				{ name: "stethoscope", desc: "听诊器", type: "both" },
				{ name: "syringe", desc: "注射器", type: "both" },
				{ name: "virus", desc: "病毒", type: "both" },
			],
			size: 30,
		},
		{
			name: "商标",
			namee: "Logos",
			icons: [
				{ name: "windows", desc: "microsoft,窗户,微软", type: "line" },
				{
					name: "android",
					desc: "applications,安卓,应用",
					type: "both",
				},
				{ name: "apple", desc: "苹果", type: "" },
				{ name: "alipay", desc: "zhifubao,支付宝", type: "both" },
				{ name: "behance", desc: "behance", type: "both" },
				{ name: "baidu", desc: "du,claw,百度,爪", type: "both" },
				{ name: "amazon", desc: "亚马逊", type: "both" },
				{ name: "blogger", desc: "博客", type: "both" },
				{
					name: "angularjs",
					desc: "angular,programing framework",
					type: "both",
				},
				{ name: "bilibili", desc: "哔哩哔哩", type: "both" },
				{ name: "disqus", desc: "comments", type: "both" },
				{
					name: "app-store",
					desc: "applications,苹果应用商店",
					type: "both",
				},
				{ name: "bootstrap", desc: "bootstrap", type: "both" },
				{ name: "centos", desc: "linux,system,系统", type: "both" },
				{ name: "coreos", desc: "linux,system,系统", type: "both" },
				{ name: "dropbox", desc: "多宝箱", type: "both" },
				{
					name: "bard",
					desc: "google,ai,magic,star,shining,sparkling,twinkle,人工智能,魔法,星星,闪烁",
					type: "both",
				},
				{
					name: "drive",
					desc: "google drive,谷歌云端硬盘",
					type: "both",
				},
				{ name: "gatsby", desc: "gatsby", type: "both" },
				{ name: "discord", desc: "game,chat", type: "both" },
				{ name: "douban", desc: "豆瓣", type: "both" },
				{ name: "dingding", desc: "钉钉", type: "both" },
				{ name: "facebook-square", desc: "脸书", type: "both" },
				{ name: "copilot", desc: "github,飞行员", type: "both" },
				{ name: "blender", desc: "3d", type: "both" },
				{ name: "facebook", desc: "脸书", type: "both" },
				{ name: "dribbble", desc: "追波", type: "both" },
				{ name: "google", desc: "google,谷歌", type: "both" },
				{ name: "codepen", desc: "代码笔", type: "both" },
				{ name: "evernote", desc: "印象笔记", type: "both" },
				{ name: "chrome", desc: "谷歌浏览器", type: "both" },
				{ name: "github", desc: "github", type: "both" },
				{ name: "firefox", desc: "火狐浏览器", type: "both" },
				{
					name: "edge",
					desc: "microsoft edge,edge浏览器",
					type: "both",
				},
				{ name: "flutter", desc: "flutter", type: "both" },
				{ name: "facebook-circle", desc: "脸书", type: "both" },
				{ name: "gitlab", desc: "gitlab", type: "both" },
				{
					name: "linkedin-square",
					desc: "linkedin,领英",
					type: "both",
				},
				{ name: "invision", desc: "invision", type: "both" },
				{ name: "honor-of-kings", desc: "game,王者荣耀", type: "both" },
				{ name: "finder", desc: "macintosh,仿达", type: "both" },
				{ name: "mastercard", desc: "bank card,银行卡", type: "both" },
				{ name: "line", desc: "line,连我", type: "both" },
				{ name: "flickr", desc: "flickr", type: "both" },
				{ name: "ie", desc: "internet explorer,浏览器", type: "both" },
				{ name: "kakao-talk", desc: "kakao talk,chat", type: "both" },
				{ name: "linkedin", desc: "linkedin,领英", type: "both" },
				{ name: "kick", desc: "kick", type: "both" },
				{ name: "mastodon", desc: "mastodon,长毛象", type: "both" },
				{ name: "microsoft-loop", desc: "Doc,笔记", type: "both" },
				{ name: "medium", desc: "medium,媒体", type: "both" },
				{
					name: "google-play",
					desc: "applications,谷歌应用商店",
					type: "both",
				},
				{ name: "messenger", desc: "facebook,脸书,信使", type: "both" },
				{ name: "microsoft", desc: "windows,窗户,微软", type: "both" },
				{ name: "instagram", desc: "instagram,照片墙", type: "both" },
				{ name: "meta", desc: "meta,元宇宙", type: "both" },
				{ name: "notion", desc: "notes,doc,笔记,文档", type: "both" },
				{ name: "openbase", desc: "openbase", type: "both" },
				{
					name: "netease-cloud-music",
					desc: "netease cloud music,网易云音乐",
					type: "both",
				},
				{ name: "open-source", desc: "opensource,开源", type: "both" },
				{ name: "openai", desc: "人工智能", type: "both" },
				{
					name: "patreon",
					desc: "donate,money,捐赠,打赏",
					type: "both",
				},
				{ name: "netflix", desc: "网飞", type: "both" },
				{
					name: "pixelfed",
					desc: "photography,pixelfed",
					type: "both",
				},
				{ name: "playstation", desc: "ps", type: "both" },
				{ name: "pinterest", desc: "拼趣", type: "both" },
				{ name: "npmjs", desc: "npm,nodejs", type: "both" },
				{ name: "spotify", desc: "music,音乐", type: "both" },
				{ name: "mini-program", desc: "微信小程序", type: "both" },
				{ name: "safari", desc: "safari浏览器", type: "both" },
				{ name: "slack", desc: "slack", type: "both" },
				{ name: "stackshare", desc: "share,分享,技术栈", type: "both" },
				{ name: "reddit", desc: "reddit", type: "both" },
				{ name: "svelte", desc: "svelte", type: "both" },
				{ name: "qq", desc: "penguin,tencent,腾讯,企鹅", type: "both" },
				{
					name: "stack-overflow",
					desc: "stack overflow",
					type: "both",
				},
				{ name: "paypal", desc: "贝宝", type: "both" },
				{ name: "skype", desc: "skype", type: "both" },
				{
					name: "reactjs",
					desc: "react,programing framework,facebook",
					type: "both",
				},
				{ name: "telegram", desc: "telegram", type: "both" },
				{ name: "steam", desc: "game,store", type: "both" },
				{ name: "spectrum", desc: "spectrum", type: "both" },
				{ name: "twitter", desc: "twitter,推特", type: "both" },
				{ name: "supabase", desc: "supabase", type: "both" },
				{ name: "threads", desc: "threads", type: "both" },
				{ name: "tiktok", desc: "tiktok,抖音", type: "both" },
				{ name: "tumblr", desc: "tumblr", type: "both" },
				{ name: "vimeo", desc: "vimeo,视频", type: "both" },
				{ name: "snapchat", desc: "ghost,色拉布,幽灵", type: "both" },
				{ name: "opera", desc: "欧朋浏览器", type: "both" },
				{ name: "trello", desc: "trello", type: "both" },
				{ name: "wechat-2", desc: "微信", type: "both" },
				{ name: "ubuntu", desc: "linux,system,系统", type: "both" },
				{
					name: "vuejs",
					desc: "vue,programing framework",
					type: "both",
				},
				{ name: "vk", desc: "vk", type: "both" },
				{ name: "switch", desc: "nintendo,任天堂", type: "both" },
				{ name: "xbox", desc: "xbox", type: "both" },
				{ name: "wechat-channels", desc: "微信视频号", type: "both" },
				{ name: "visa", desc: "bank card,银行卡", type: "both" },
				{ name: "wechat", desc: "wechat,微信", type: "both" },
				{ name: "weibo", desc: "新浪微博", type: "both" },
				{ name: "yuque", desc: "yuque,语雀", type: "both" },
				{ name: "youtube", desc: "youtube,优兔,油管", type: "both" },
				{ name: "xing", desc: "xing", type: "both" },
				{ name: "taobao", desc: "taobao,淘宝", type: "both" },
				{ name: "wordpress", desc: "blog,博客", type: "both" },
				{ name: "zcool", desc: "zcool,站酷", type: "both" },
				{ name: "whatsapp", desc: "瓦次艾普", type: "both" },
				{ name: "zhihu", desc: "zhihu,知乎", type: "both" },
			],
			size: 109,
		},
		{
			name: "地图",
			namee: "Map",
			icons: [
				{
					name: "suitcase-2",
					desc: "travel,旅行,行李箱,拉杆箱",
					type: "both",
				},
				{ name: "guide", desc: "path,指引,路线", type: "fill" },
				{ name: "bus-2", desc: "大巴,巴士", type: "both" },
				{ name: "bike", desc: "自行车", type: "both" },
				{ name: "charging-pile", desc: "充电桩", type: "both" },
				{ name: "anchor", desc: "锚", type: "both" },
				{ name: "barricade", desc: "路障", type: "both" },
				{ name: "bus", desc: "大巴,巴士", type: "both" },
				{ name: "car", desc: "汽车", type: "both" },
				{ name: "car-washing", desc: "汽车,洗车", type: "both" },
				{
					name: "compass-3",
					desc: "navigation,safari,direction,discover,指南针,导航,方向,发现,探索",
					type: "both",
				},
				{
					name: "compass-2",
					desc: "navigation,direction,discover,指南针,导航,方向,发现,探索",
					type: "both",
				},
				{ name: "china-railway", desc: "中铁,铁路,火车", type: "both" },
				{
					name: "compass-discover",
					desc: "navigation,direction,指南针,导航,方向,发现,探索",
					type: "both",
				},
				{ name: "charging-pile-2", desc: "充电桩", type: "both" },
				{
					name: "compass-4",
					desc: "navigation,direction,discover,指南针,导航,方向,发现,探索",
					type: "both",
				},
				{
					name: "e-bike-2",
					desc: "take out,takeaway,电动车,外卖",
					type: "both",
				},
				{
					name: "flight-land",
					desc: "airplane,plane,destination,着陆,到达,抵达,终点,飞机",
					type: "both",
				},
				{
					name: "compass",
					desc: "navigation,safari,direction,discover,指南针,导航,方向,发现,探索",
					type: "both",
				},
				{
					name: "e-bike",
					desc: "take out,takeaway,电动车,外卖",
					type: "both",
				},
				{
					name: "flight-takeoff",
					desc: "airplane,plane,origin,起飞,出发,始发,起点,飞机",
					type: "both",
				},
				{ name: "direction", desc: "right,方向,右转", type: "both" },
				{ name: "hotel-bed", desc: "酒店,床", type: "both" },
				{
					name: "earth",
					desc: "global,union,world,language,地球,全球,联合,世界,语言",
					type: "both",
				},
				{ name: "globe", desc: "earth,地球仪", type: "both" },
				{ name: "lifebuoy", desc: "life ring,救生圈", type: "both" },
				{ name: "gas-station", desc: "加气站,加油站", type: "both" },
				{
					name: "map-pin-user",
					desc: "location,navigation,地图,坐标,定位,导航,位置,用户",
					type: "both",
				},
				{
					name: "map-2",
					desc: "location,navigation,travel,地图,定位,导航,旅行",
					type: "both",
				},
				{ name: "footprint", desc: "脚印,足迹", type: "both" },
				{
					name: "map-pin-2",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
					type: "both",
				},
				{
					name: "map-pin-3",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
					type: "both",
				},
				{
					name: "map-pin",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
					type: "both",
				},
				{
					name: "luggage-deposit",
					desc: "consignment,行李箱,行李寄存,托运",
					type: "both",
				},
				{
					name: "map-pin-4",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
					type: "both",
				},
				{ name: "plane", desc: "fight,飞机,航班", type: "both" },
				{
					name: "map",
					desc: "navigation,travel,地图,导航,旅行",
					type: "both",
				},
				{
					name: "map-pin-add",
					desc: "location,navigation,地图,坐标,定位,导航,位置,新增,添加",
					type: "both",
				},
				{
					name: "map-pin-5",
					desc: "location,navigation,地图,坐标,定位,导航,位置",
					type: "both",
				},
				{
					name: "map-pin-range",
					desc: "location,navigation,地图,坐标,定位,导航,位置,范围",
					type: "both",
				},
				{ name: "motorbike", desc: "摩托车", type: "both" },
				{ name: "parking", desc: "停车场", type: "both" },
				{ name: "navigation", desc: "gps,导航", type: "both" },
				{ name: "passport", desc: "passports,护照", type: "both" },
				{
					name: "map-pin-time",
					desc: "location,navigation,地图,坐标,定位,导航,位置,时间",
					type: "both",
				},
				{ name: "pushpin-2", desc: "图钉", type: "both" },
				{ name: "pushpin", desc: "图钉", type: "both" },
				{ name: "pin-distance", desc: "坐标,距离", type: "both" },
				{ name: "police-car", desc: "汽车,警车", type: "both" },
				{ name: "parking-square", desc: "停车场", type: "both" },
				{ name: "oil", desc: "汽油,机油", type: "both" },
				{ name: "route", desc: "path,路线", type: "both" },
				{
					name: "planet",
					desc: "space,discover,星球,宇宙,探索,发现",
					type: "both",
				},
				{ name: "roadster", desc: "car,汽车,跑车", type: "both" },
				{
					name: "rocket-2",
					desc: "space ship,火箭,太空飞船",
					type: "both",
				},
				{ name: "riding", desc: "bike,骑行,自行车", type: "both" },
				{
					name: "signpost",
					desc: "mailestone,路标,路牌,里程碑",
					type: "both",
				},
				{ name: "rocket", desc: "火箭", type: "both" },
				{ name: "sailboat", desc: "帆船", type: "both" },
				{ name: "run", desc: "奔跑,跑步", type: "both" },
				{
					name: "signal-tower",
					desc: "base station,antenna,信号塔,基站,天线",
					type: "both",
				},
				{ name: "ship", desc: "轮船,航海,海运", type: "both" },
				{ name: "steering-2", desc: "drive,方向盘,驾车", type: "both" },
				{
					name: "road-map",
					desc: "navigation,travel,地图,导航,旅行",
					type: "both",
				},
				{ name: "ship-2", desc: "轮船", type: "both" },
				{ name: "space-ship", desc: "太空飞船", type: "both" },
				{ name: "suitcase", desc: "travel,旅行,行李箱", type: "both" },
				{ name: "steering", desc: "drive,方向盘,驾车", type: "both" },
				{ name: "subway", desc: "地铁", type: "both" },
				{ name: "train", desc: "火车", type: "both" },
				{ name: "traffic-light", desc: "交通,信号灯", type: "both" },
				{ name: "taxi", desc: "car,出租车,汽车", type: "both" },
				{
					name: "time-zone",
					desc: "global,地球,时区,时间",
					type: "both",
				},
				{
					name: "truck",
					desc: "van,delivery,卡车,货车,运输",
					type: "both",
				},
				{ name: "unpin", desc: "图钉,取消固定", type: "both" },
				{
					name: "treasure-map",
					desc: "thriller,adventure,地图,藏宝图",
					type: "both",
				},
				{ name: "walk", desc: "步行", type: "both" },
			],
			size: 77,
		},
		{
			name: "媒体",
			namee: "Media",
			icons: [
				{ name: "play-circle", desc: "start,播放,开始", type: "both" },
				{ name: "pause-circle", desc: "暂停", type: "both" },
				{
					name: "fullscreen-exit",
					desc: "minimize,退出全屏,最小化",
					type: "",
				},
				{ name: "fullscreen", desc: "maximize,全屏,最大化", type: "" },
				{ name: "video", desc: "视频", type: "both" },
			],
			size: 5,
		},
		{
			name: "系统",
			namee: "System",
			icons: [
				{ name: "zoom-out", desc: "缩小,放大镜", type: "both" },
				{
					name: "lock-unlock",
					desc: "security,password,锁子,安全,密码",
					type: "both",
				},
				{
					name: "lock",
					desc: "security,password,锁子,安全,密码",
					type: "both",
				},
				{ name: "question", desc: "help,问号,帮助", type: "" },
				{
					name: "close-circle",
					desc: "cancel,remove,delete,empty,x,关闭,取消,移除,删除,清空",
					type: "both",
				},
				{
					name: "settings-3",
					desc: "edit,gear,preferences,偏好设置,编辑,齿轮",
					type: "both",
				},
				{
					name: "menu",
					desc: "navigation,hamburger,导航,菜单,汉堡包",
					type: "both",
				},
				{ name: "search", desc: "搜索,放大镜", type: "" },
				{
					name: "settings",
					desc: "edit,gear,preferences,偏好设置,编辑,齿轮",
					type: "both",
				},
				{ name: "share", desc: "sharing,分享,转发", type: "fill" },
				{ name: "upload", desc: "send,上传,发送", type: "" },
				{ name: "eye", desc: "watch,view,眼睛,查看", type: "fill" },
				{ name: "zoom-in", desc: "放大,放大镜", type: "both" },
			],
			size: 13,
		},
		{
			name: "表情",
			namee: "User & Faces",
			icons: [
				{ name: "user", desc: "用户,person,people", type: "both" },
				{ name: "user-2", desc: "用户,person,people", type: "both" },
				{
					name: "team",
					desc: "团队,小组,群主,person,people",
					type: "fill",
				},
				{
					name: "user-unfollow",
					desc: "person,people,rejected,用户,取消关注,拒绝,错误",
					type: "both",
				},
				{
					name: "skull-2",
					desc: "ghost,horror,thriller,骷髅,鬼怪,恐惧,恐怖",
					type: "line",
				},
				{
					name: "user-shared",
					desc: "transfer,用户,我分享的,发送,person,people",
					type: "both",
				},
				{
					name: "user-location",
					desc: "用户,定位,person,people",
					type: "both",
				},
				{
					name: "user-heart",
					desc: "用户,关注,person,people",
					type: "line",
				},
				{ name: "user-voice", desc: "用户,录音,演讲", type: "fill" },
				{
					name: "criminal",
					desc: "horror,thriller,罪犯,犯罪,恐怖",
					type: "line",
				},
				{
					name: "user-smile",
					desc: "用户,微笑,person,people",
					type: "line",
				},
				{
					name: "user-settings",
					desc: "admin,用户,设置,管理员,person,people",
					type: "fill",
				},
				{
					name: "user-follow",
					desc: "关注,person,people",
					type: "line",
				},
				{
					name: "user-received",
					desc: "用户,我接收的,收取,person,people",
					type: "both",
				},
				{
					name: "user-add",
					desc: "用户,添加,新增,person,people",
					type: "line",
				},
				{ name: "travesti", desc: "女人,女性", type: "line" },
			],
			size: 16,
		},
		{
			name: "天气",
			namee: "Weather",
			icons: [{ name: "fire", desc: "flame,hot,火,热门", type: "both" }],
			size: 1,
		},
		{
			name: "其它",
			namee: "Others",
			icons: [
				{ name: "bad", desc: "bad", type: "both" },
				{ name: "good", desc: "good", type: "both" },
				{ name: "eye-hide", desc: "eye-hide", type: "" },
				{ name: "warning", desc: "warning", type: "both" },
				{ name: "brightness-2", desc: "brightness-2", type: "both" },
				{ name: "brightness-1", desc: "brightness-1", type: "both" },
				{ name: "pictures", desc: "pictures", type: "both" },
				{ name: "windows_line", desc: "windows_line", type: "" },
				{ name: "office", desc: "office", type: "both" },
				{ name: "location", desc: "location", type: "both" },
				{ name: "delete-2", desc: "delete-2", type: "both" },
				{ name: "place", desc: "place", type: "" },
				{ name: "pear", desc: "pear", type: "" },
				{ name: "error", desc: "error", type: "" },
				{ name: "info", desc: "info", type: "fill" },
				{ name: "remove", desc: "remove", type: "" },
				{ name: "success", desc: "success", type: "" },
				{ name: "suitcase-1", desc: "suitcase-1", type: "" },
				{ name: "toilet-paper", desc: "toilet-paper", type: "" },
				{ name: "postcard", desc: "postcard", type: "" },
				{
					name: "bell",
					desc: "cartoon,anime,doraemon,铃铛,哆啦A梦,卡通,动漫",
					type: "both",
				},
				{ name: "close-square", desc: "close-square", type: "both" },
				{
					name: "arrow-down-square",
					desc: "arrow-down-square",
					type: "both",
				},
				{
					name: "arrow-left-square",
					desc: "arrow-left-square",
					type: "both",
				},
				{ name: "play-square", desc: "play-square", type: "both" },
				{ name: "minus-square", desc: "minus-square", type: "both" },
				{ name: "plus-square", desc: "plus-square", type: "both" },
				{
					name: "arrow-right-square",
					desc: "arrow-right-square",
					type: "both",
				},
				{
					name: "arrow-up-square",
					desc: "arrow-up-square",
					type: "both",
				},
				{ name: "check-square", desc: "check-square", type: "both" },
				{ name: "api", desc: "api", type: "both" },
				{
					name: "connect-disconnect",
					desc: "connect-disconnect",
					type: "",
				},
				{ name: "connect", desc: "connect", type: "" },
				{ name: "phone-3", desc: "phone-3", type: "both" },
				{ name: "minus-circle", desc: "minus-circle", type: "both" },
				{ name: "frown", desc: "frown", type: "both" },
				{ name: "check-circle", desc: "check-circle", type: "both" },
				{ name: "info-circle", desc: "info-circle", type: "both" },
				{ name: "meh", desc: "meh", type: "both" },
				{ name: "plus-circle", desc: "plus-circle", type: "both" },
				{
					name: "question-circle",
					desc: "question-circle",
					type: "both",
				},
				{ name: "time-circle", desc: "time-circle", type: "both" },
				{
					name: "money-yuan-circle",
					desc: "money-yuan-circle",
					type: "both",
				},
				{
					name: "warning-circle",
					desc: "warning-circle",
					type: "both",
				},
				{ name: "fullpage", desc: "fullpage", type: "" },
				{ name: "fullpage-exit", desc: "fullpage-exit", type: "" },
				{
					name: "arrow-down-circle-2",
					desc: "arrow-down-circle-2",
					type: "both",
				},
				{
					name: "arrow-right-circle-2",
					desc: "arrow-right-circle-2",
					type: "both",
				},
				{
					name: "arrow-left-circle-2",
					desc: "arrow-left-circle-2",
					type: "both",
				},
				{ name: "wangwang", desc: "wangwang", type: "" },
				{ name: "windows-2", desc: "windows-2", type: "line" },
				{ name: "wangxin", desc: "wangxin", type: "" },
				{ name: "setings-2", desc: "setings-2", type: "fill" },
				{ name: "goblet-3", desc: "goblet-3", type: "fill" },
				{ name: "goblet-4", desc: "goblet-4", type: "fill" },
				{ name: "grape", desc: "grape", type: "" },
				{ name: "microphone", desc: "microphone", type: "" },
				{ name: "position", desc: "position", type: "" },
				{ name: "ice-tea", desc: "ice-tea", type: "" },
				{ name: "help-1", desc: "help-1", type: "both" },
				{ name: "monitor", desc: "monitor", type: "" },
				{ name: "goods", desc: "goods", type: "both" },
				{ name: "baseball", desc: "baseball", type: "" },
				{ name: "coffee", desc: "coffee", type: "fill" },
				{ name: "coffee-cup", desc: "coffee-cup", type: "fill" },
				{
					name: "presentation-2",
					desc: "presentation-2",
					type: "fill",
				},
				{
					name: "presentation-1",
					desc: "presentation-1",
					type: "fill",
				},
				{ name: "copy-document", desc: "copy-document", type: "" },
				{
					name: "presentation-3",
					desc: "presentation-3",
					type: "fill",
				},
				{ name: "goblet-2", desc: "goblet-2", type: "fill" },
				{ name: "goblet-1", desc: "goblet-1", type: "fill" },
				{
					name: "football",
					desc: "sports,运动,足球,体育",
					type: "fill",
				},
				{ name: "food", desc: "food", type: "fill" },
				{ name: "menu-hide", desc: "menu-hide", type: "" },
				{ name: "menu-show", desc: "menu-show", type: "" },
				{
					name: "indent-decrease-2",
					desc: "indent-decrease-2",
					type: "",
				},
				{ name: "spread-down", desc: "spread-down", type: "fill" },
				{ name: "spread-left", desc: "spread-left", type: "fill" },
				{ name: "spread-right", desc: "spread-right", type: "fill" },
				{ name: "spread-up", desc: "spread-up", type: "fill" },
				{ name: "retract-left", desc: "retract-left", type: "fill" },
				{ name: "retract-up", desc: "retract-up", type: "fill" },
				{ name: "retract-down", desc: "retract-down", type: "fill" },
				{ name: "retract-right", desc: "retract-right", type: "fill" },
				{ name: "key", desc: "password,钥匙,密码", type: "both" },
				{ name: "alarm-clock", desc: "alarm-clock", type: "both" },
				{ name: "user-1", desc: "user-1", type: "both" },
				{ name: "crown-1", desc: "crown-1", type: "both" },
				{ name: "delete", desc: "delete", type: "both" },
				{
					name: "format-painter",
					desc: "format-painter",
					type: "both",
				},
				{ name: "setting-1", desc: "setting-1", type: "both" },
				{ name: "cherry", desc: "cherry", type: "" },
				{ name: "apple-inc", desc: "apple-inc", type: "both" },
				{
					name: "parking-circle",
					desc: "parking-circle",
					type: "both",
				},
				{ name: "tenpay", desc: "tenpay", type: "both" },
				{ name: "x", desc: "x", type: "both" },
				{ name: "route-2", desc: "route-2", type: "line" },
				{ name: "guide-2", desc: "guide-2", type: "fill" },
				{ name: "file-xls", desc: "file-xls", type: "both" },
				{ name: "file-doc", desc: "file-doc", type: "both" },
				{ name: "bar-chart-3", desc: "bar-chart-3", type: "both" },
				{ name: "input-english", desc: "input-english", type: "" },
				{ name: "font-case", desc: "font-case", type: "" },
				{ name: "emphasis-en", desc: "emphasis-en", type: "" },
				{ name: "list-dot", desc: "list-dot", type: "" },
				{ name: "input-pinyin", desc: "input-pinyin", type: "" },
				{ name: "tree-2", desc: "tree-2", type: "" },
				{ name: "tree-1", desc: "tree-1", type: "" },
				{
					name: "slash-commands-square",
					desc: "slash-commands-square",
					type: "",
				},
				{ name: "input-wubi", desc: "input-wubi", type: "" },
				{ name: "hours-24", desc: "hours-24", type: "both" },
				{ name: "gift-1", desc: "gift-1", type: "both" },
				{
					name: "shopping-bag-1",
					desc: "shopping-bag-1",
					type: "both",
				},
				{ name: "crown-2", desc: "crown-2", type: "both" },
				{ name: "diamond-1", desc: "diamond-1", type: "both" },
				{ name: "vip-fill1", desc: "vip-fill1", type: "" },
				{ name: "code-2", desc: "code-2", type: "both" },
				{ name: "code-1", desc: "code-1", type: "both" },
				{ name: "battery-h-low", desc: "battery-h-low", type: "both" },
				{
					name: "battery-h-charge",
					desc: "battery-h-charge",
					type: "both",
				},
				{
					name: "battery-v-share",
					desc: "battery-v-share",
					type: "both",
				},
				{ name: "battery-v", desc: "battery-v", type: "both" },
				{
					name: "battery-v-charge",
					desc: "battery-v-charge",
					type: "both",
				},
				{
					name: "battery-v-saver",
					desc: "battery-v-saver",
					type: "both",
				},
				{ name: "battery-h", desc: "battery-h", type: "both" },
				{ name: "phone-1", desc: "phone-1", type: "both" },
				{ name: "save-1", desc: "save-1", type: "both" },
				{ name: "store-4", desc: "store-4", type: "both" },
				{
					name: "copyright-line-copy",
					desc: "copyright-line-copy",
					type: "",
				},
				{
					name: "customer-service-fill1",
					desc: "customer-service-fill1",
					type: "",
				},
				{ name: "printer-1", desc: "printer-1", type: "both" },
				{ name: "arrow-up-1", desc: "arrow-up-1", type: "both" },
				{ name: "arrow-up-2", desc: "arrow-up-2", type: "both" },
				{ name: "arrow-left-1", desc: "arrow-left-1", type: "both" },
				{ name: "arrow-left-3", desc: "arrow-left-3", type: "both" },
				{ name: "arrow-left-2", desc: "arrow-left-2", type: "both" },
				{ name: "arrow-right-3", desc: "arrow-right-3", type: "both" },
				{ name: "arrow-right-1", desc: "arrow-right-1", type: "both" },
				{ name: "arrow-right-2", desc: "arrow-right-2", type: "both" },
				{ name: "arrow-up-3", desc: "arrow-up-3", type: "both" },
				{ name: "arrow-down-3", desc: "arrow-down-3", type: "both" },
				{ name: "arrow-down-1", desc: "arrow-down-1", type: "both" },
				{ name: "arrow-down-2", desc: "arrow-down-2", type: "both" },
				{ name: "help", desc: "help", type: "fill" },
				{ name: "remind", desc: "remind", type: "both" },
				{ name: "remind-circle", desc: "remind-circle", type: "both" },
				{
					name: "right-double-arrow",
					desc: "right-double-arrow",
					type: "",
				},
				{ name: "smile", desc: "smile", type: "both" },
				{
					name: "sorting-horizontal",
					desc: "sorting-horizontal",
					type: "",
				},
				{
					name: "sorting-vertical",
					desc: "sorting-vertical",
					type: "",
				},
				{ name: "suspend", desc: "suspend", type: "" },
				{
					name: "arrow-up-circle-2",
					desc: "arrow-up-circle-2",
					type: "both",
				},
				{ name: "company", desc: "company", type: "both" },
				{
					name: "customer-service-24hour",
					desc: "customer-service-24hour",
					type: "line",
				},
				{ name: "customization", desc: "customization", type: "both" },
				{
					name: "format-painter-2",
					desc: "format-painter-2",
					type: "both",
				},
				{ name: "discount", desc: "discount", type: "both" },
				{ name: "email", desc: "email", type: "both" },
				{ name: "fair", desc: "fair", type: "" },
				{ name: "global-2", desc: "global-2", type: "fill" },
				{ name: "honor", desc: "honor", type: "fill" },
				{ name: "palette-1", desc: "palette-1", type: "both" },
				{ name: "crown", desc: "crown", type: "both" },
				{ name: "layers", desc: "layers", type: "both" },
				{ name: "phone-2", desc: "phone-2", type: "both" },
				{ name: "picture", desc: "picture", type: "both" },
				{ name: "pin", desc: "pin", type: "both" },
				{ name: "protection", desc: "protection", type: "line" },
				{ name: "response", desc: "response", type: "both" },
				{ name: "shopping", desc: "shopping", type: "both" },
				{ name: "security-1", desc: "security-1", type: "fill" },
				{ name: "book-1", desc: "book-1", type: "fill" },
				{
					name: "presentation-4",
					desc: "presentation-4",
					type: "fill",
				},
				{ name: "top-raning", desc: "top-raning", type: "both" },
				{ name: "arrow-up-4", desc: "arrow-up-4", type: "fill" },
				{ name: "degree", desc: "degree", type: "fill" },
				{ name: "picture-1", desc: "picture-1", type: "fill" },
				{ name: "security", desc: "security", type: "fill" },
				{ name: "database-3", desc: "database-3", type: "fill" },
				{ name: "diamond-2", desc: "diamond-2", type: "fill" },
				{ name: "services-icon", desc: "services-icon", type: "" },
				{ name: "remind-2", desc: "remind-2", type: "fill" },
			],
			size: 182,
		},
	],
};